Pass callback enpoint when setting nonce cookies
trinodb/trino pull request #10203
Opened 2021-12-06 18:05 UTC by wendigo

2021-12-07 09:03 UTC, lukasz-walkiewicz approved these changes

2021-12-07 11:35 UTC, kokosing approved these changes

2021-12-08 11:00 UTC, 11xor6 requested changes
This change is improper. If customization of the OAuth2/OIDC flow is necessary the state and/or query parameters on the redirect URI are the proper place to put that information.

2021-12-08 18:25 UTC, dain requested changes

2021-12-08 18:25 UTC, dain commented on core/trino-main/src/main/java/io/trino/server/security/oauth2/NonceCookie.java
> +        }
I don't see how this would ever happen in Trino.  If this is happening, please fix the source as this is just masking a bug.

2022-01-17 10:03 UTC, closed without merging