Clarify duration values as integers
trinodb/trino pull request #10356
Opened 2021-12-20 17:16 UTC by jhlodin

Clarify that `duration` type values must be integers.

2021-12-20 21:37 UTC, mosabua reviewed
Currently it seems decimal values actually work. I suggest that we update the docs like this and then as a follow up also change the code so that only integer values are supported.

This is necessary to avoid confusion such as what is 0.5 months? Or even others like 1.30m ... is that one minute and 30 seconds .. so really 1.5m ? E.g. in this case users should just use 90s. 

Wdyt @electrum ?

2022-01-04 20:00 UTC, hashhar requested changes
The existing docs are correct.

Changing allowed values is not feasible due to multiple reasons IMO:

1. It's a breaking change without a good-enough justification.
2. It might not be straightforward to limit to only integer values since a Duration object can constructed in many ways - only one of which is via human readable string.

I'll defer to @electrum for a decision on this.

2022-01-04 23:50 UTC, martint commented
> This is necessary to avoid confusion such as what is 0.5 months

Duration only supports units up to days, for that specific reason. So there's no confusion there.

>  1.30m

Not sure what's ambiguous about that. It's 1.3 minutes (just a fractional number), not 1:30 minutes.

> one minute and 30 seconds .. so really 1.5m ? E.g. in this case users should just use 90s.

What's wrong with using 1.5 minutes? The natural magnitude of a setting (what you intuitively think about) might be in terms of minutes, or hours, or days. For instance, what if you want to represent "a tenth of a day"? If you can't use fractional numbers, you can't say "0.1d", or even the equivalent in hours (i.e., "2.4h"). You'd need to say "144m", which is hard to mentally relate to the length of a day.

> Also .. this might have to be done in Airlift..

No, that was an intentional design choice in Airlift, and it needs to be that way for may other reasons.

2022-01-06 15:38 UTC, jhlodin commented
Closing this PR, will follow up shortly with another PR that clarifies how decimal duration values are handled.

2022-01-06 15:38 UTC, closed without merging