Correct log retention properties
trinodb/trino pull request #10461
Opened 2022-01-04 16:56 UTC by jhlodin

The `log.max-history` property is not a count of log files to keep, but rather a maximum age to retain old files.

2022-01-04 23:57 UTC, martint requested changes
This is incorrect. `log.max-history` is the "Maximum number of log files to retain". See https://github.com/airlift/airlift/blob/master/log-manager/src/main/java/io/airlift/log/LoggingConfiguration.java#L118

2022-01-04 23:59 UTC, rosewms approved these changes
GtG after addressing Martin's edit.

2022-01-05 00:23 UTC, jhlodin commented
> This is incorrect. `log.max-history` is the "Maximum number of log files to retain". See https://github.com/airlift/airlift/blob/master/log-manager/src/main/java/io/airlift/log/LoggingConfiguration.java#L118

@bitweld Can you jump in? This came up because the `log.max-history` property doesn't appear to follow that description in practice, and instead describes the max age to keep any log file. It may make sense to update this in airlift as well.

2022-01-05 07:25 UTC, hashhar commented
The number of days thing could be a co-incidence because the logger (used to, not anymore IIRC) rolled new files once date changes. So number of files retained would happen to be close to number of days (provided you only generated one log file per day - true only for low volume clusters).

2022-01-07 06:42 UTC, hashhar commented
I'll reinvestigate what the current logger behaviour is regarding those configs. Lots of things have changed in Airlift logging since the original motivation for this documentation change.

2022-01-13 22:39 UTC, Ordinant approved these changes
No room to improve.

2022-01-31 17:46 UTC, jhlodin commented
@hashhar Any update on whether logger behavior reflects current documentation, or if this PR is needed? Would be great to get that sorted for 370.

2022-03-09 20:12 UTC, jhlodin commented
Looks like the current docs are correct, or at least more investigation is needed to see what changes are required. Closing this PR for the time being.

2022-03-09 20:12 UTC, closed without merging