Document allow-drop-table property in JDBC connectors
trinodb/trino pull request #10795
Opened 2022-01-25 18:10 UTC by jhlodin

As of Trino 368 at least, the `allow-drop-table` property must be enabled to allow `DROP TABLE` statements. This is at least true for JDBC connectors, need clarification if this applies to others.

2022-01-25 18:15 UTC, hashhar reviewed
Correct. Only applies to JDBC connectors.

Note that we will revisit this once/if https://github.com/trinodb/trino/pull/588 makes in.

I have yet to check the list of JDBC connectors that support this.

2022-01-25 18:15 UTC, hashhar commented on docs/src/main/sphinx/connector/drop-table-property.fragment
> +    alter-table-enabled=true
```suggestion
    allow-drop-table=true
```

2022-01-25 18:15 UTC, hashhar commented on docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
> +    - Enable :doc:`/sql/drop-table` statements if supported by the connector
```suggestion
    - Enable :doc:`/sql/drop-table` statements if supported by the connector.
```

2022-01-25 18:24 UTC, jhlodin commented on docs/src/main/sphinx/connector/drop-table-property.fragment
> +    alter-table-enabled=true
Whoops 😅

2022-01-25 19:15 UTC, hashhar reviewed
Add `phoenix` - but it has the default value set to `true`.

Other than that only `druid` is missing in this PR.

2022-01-25 19:16 UTC, hashhar commented
Note that other connectors (like Hive and Cassandra) have "equivalent" configs (e.g. `hive.allow-drop-table` and `cassandra.allow-drop-table`) but they just happen to have the similar name as this config and are unrelated otherwise.

2022-01-25 20:17 UTC, jhlodin commented
@hashhar Added a custom version of the fragment to Phoenix, noting that it's enabled by default but can be disabled.

I skipped over adding the fragment to Druid because it's read-only, so there's no point in enabling the property.

2022-01-25 20:23 UTC, electrum requested changes
We're going to drop this property. I need to update and merge #588.

2022-01-25 20:28 UTC, jhlodin commented
> We're going to drop this property. I need to update and merge #588.

Thanks @electrum . Do you have a target release for that PR? If that's still TBD, I think for the sake of user experience we ought to document this behavior and revert once #588 is live.

2022-01-25 20:45 UTC, mosabua commented
I am in favour of dropping the property, but given that we keep getting questions on slack and other forums we should get either the docs updated or the code changed merged asap.

2022-01-28 19:00 UTC, jhlodin commented
Chatted with @electrum , the goal is to get #588 merged for 370. If it doesn't make that release, we agreed to merge this docs PR. So this can sit tight until it's either merged or closed with 370.

2022-02-02 18:09 UTC, jhlodin commented
Looks like https://github.com/trinodb/trino/pull/588 is merged! @electrum Should I take that as confirmation that it's ok to close this PR?

2022-02-02 20:02 UTC, jhlodin commented
Closing as the PR to remove this property has been merged.

2022-02-02 20:02 UTC, closed without merging

2022-02-03 21:16 UTC, electrum commented
Thanks @jhlodin for reminding me to get this change in. This legacy and confusing property is finally gone!