Add client and source tags to resource group documentation
trinodb/trino pull request #11287
Opened 2022-03-02 22:47 UTC by Jessie212

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

Improvement.

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Addition to documentation.

> How would you describe this change to a non-technical end user or system administrator?

Add client and source tags to resource group documentation

## Related issues, pull requests, and links

## Documentation

( ) No documentation is needed.
(x) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

2022-03-02 23:47 UTC, mosabua commented on docs/src/main/sphinx/admin/resource-groups.rst
> +* JDBC: set the ``ApplicationName`` client info property on the ``Connection``
This is for Java programming using the JDBC drvier.

2022-03-02 23:48 UTC, mosabua requested changes
Needs a bunch of updates..

2022-03-02 23:48 UTC, mosabua commented on docs/src/main/sphinx/admin/resource-groups.rst
> +* Driver properties: add the ``source`` tag when using a Java application that
These are the JDBC driver properties to use in applications using the driver. Add this as a third bullet in the list and maybe even link to the JDBC driver properties table.

2022-03-02 23:48 UTC, mosabua commented on docs/src/main/sphinx/admin/resource-groups.rst
> +* Driver properties: add the ``client`` tag when using a Java application that
Same as above .. and check the correct property name..

2022-03-16 19:35 UTC, mosabua approved these changes

2022-03-16 19:59 UTC, hashhar approved these changes
LGTM % nit

nit: `JDBC used in` -> `JDBC driver as used in`/`JDBC driver when used in/with`?

2022-03-17 21:03 UTC, merged