Add Trino 373 release notes
trinodb/trino pull request #11290
Opened 2022-03-03 00:16 UTC by mosabua

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

> How would you describe this change to a non-technical end user or system administrator?

## Related issues, pull requests, and links

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-03-04 20:42 UTC, mosabua commented on docs/src/main/sphinx/release/release-373.md
> +* Prevent failure for queries with the final number of partitions
how about that @Praveen2112 ?

2022-03-04 20:49 UTC, mosabua commented on docs/src/main/sphinx/release/release-373.md
> +* Support access to S3 via a HTTP proxy. ({issue}`11255`)
Is this rewording okay @losipiuk  ..

2022-03-09 20:01 UTC, martint requested changes

2022-03-09 21:04 UTC, hashhar commented on docs/src/main/sphinx/release/release-373.md
> +* Prevent writing incorrect results by failing a query when the Phoenix JDBC
Not under our control. It's a bug in driver. It replaces them unconditionally.

2022-03-09 21:15 UTC, mosabua commented on docs/src/main/sphinx/release/release-373.md
> +* Add CPU time, scheduled time, and cumulative memory statistics regarding
done

2022-03-09 21:16 UTC, mosabua commented on docs/src/main/sphinx/release/release-373.md
> +* Add support for killing individual tasks of queries run with ``retry-mode``
done

2022-03-09 21:17 UTC, mosabua commented on docs/src/main/sphinx/release/release-373.md
> +  computation the underlying database. ({issue}`7994`, {issue}`11354`,
both addressed

2022-03-09 21:59 UTC, merged