Fix Dev Guide references to new locations
trinodb/trino pull request #11906
Opened 2022-04-11 21:57 UTC by Ordinant

## Description

The Developer Guide chapter has a few references to sub-projects “at the root of the Trino source tree”. But since the reorganization of that tree, these references are one layer off.

> Is this change a fix, improvement, new feature, refactoring, or other?

Fix.

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Docs only.

> How would you describe this change to a non-technical end user or system administrator?

Doc correction.

## Related issues, pull requests, and links

## Documentation

( ) No documentation is needed.
(x) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

2022-04-12 05:02 UTC, aakashnand requested changes

2022-04-12 05:02 UTC, aakashnand commented on docs/src/main/sphinx/develop/spi-overview.rst
> +The SPI source can be found in the ``core/trino-spi`` directory in the
```suggestion
The SPI source can be found in the `core/trino-spi <https://github.com/trinodb/trino/tree/master/core/trino-spi>`_  directory in the
```

2022-04-12 05:02 UTC, aakashnand commented on docs/src/main/sphinx/develop/spi-overview.rst
> +``plugin/trino-example-http`` directory in the Trino source tree.
```suggestion
`plugin/trino-example-http <https://github.com/trinodb/trino/tree/master/plugin/trino-example-http>`_  directory in the Trino source tree.
```

2022-04-13 18:52 UTC, Ordinant commented
@aakashnand, thanks for the suggestion to link to the referenced code, but even more for doing the work! I bravely clicked the Commit changes buttons here in GitHub. Can you SQUASH and merge?

2022-04-14 00:46 UTC, aakashnand commented
@Ordinant sure will do it today.

2022-04-14 04:17 UTC, Ordinant commented
@aakashnand, I squashed all commits to one. Thanks for your help!

2022-04-14 21:30 UTC, mosabua reviewed
I like the corrections in terms of paths to modules and such. I am not sure I like linking to the source code repo.

2022-04-14 23:31 UTC, aakashnand commented
@mosabua I thought it would be more better user experience to directly click the links rather than going to repo and find that file manually

2022-04-15 05:24 UTC, mosabua commented
> @mosabua I thought it would be more better user experience to directly click the links rather than going to repo and find that file manually

I understand .. but I also think I disagree .. if you are reading this dev guide you would typically have the whole codebase open in an IDE already and just jump to the class with shortcut key...  at least thtats what I would do.

2022-05-10 06:24 UTC, hashhar requested changes
Let's remove links to source code since they are easy to break while the class names or module names can generally be searched for and they'll lead you to correct place even if things have been renamed.

Rest of it looks good.

2022-05-12 23:04 UTC, mosabua approved these changes
Awesome .. merge time ;-)

2022-05-13 05:48 UTC, hashhar approved these changes
Thanks.

2022-05-13 05:48 UTC, merged