Add Delta synchronizer for GCS
trinodb/trino pull request #12309
Opened 2022-05-10 10:14 UTC by findinpath

This implementation is an adaptation of what has been done
in delta OSS.

Writing of the log entry is done in a separate thread in
order to avoid uploading incomplete files by the gcs-connector.
See for more details:

https://github.com/delta-io/delta/commit/7a3f1e8ec626e80880d524c2b897a969c8b4d63a

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

Improvement

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Delta Lake connector

> How would you describe this change to a non-technical end user or system administrator?

Add the ability to perform DML statements of tables backed by Google Cloud Storage

## Related issues, pull requests, and links

Fixes: #12264

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(x) Release notes entries required with the following suggested text:

```markdown
# Delta Lake
* Add support for DML statements on tables backed by GCS
```

2022-05-10 11:02 UTC, findepi commented
> Writing of the log entry is done in a separate thread in
> order to avoid uploading incomplete files by the gcs-connector.
> See for more details:

As discussed offline: that's a concern. Does it mean that some other application can see partial transaction log files, mid-write?

(ref https://github.com/delta-io/delta/issues/956 and https://github.com/delta-io/delta/commit/225e2bbf9ecaf034d08ef8d2fee1929e51c951bf for posterity)

cc @alexjo2144 @vkorukanti

2022-05-14 05:01 UTC, findinpath commented
> Does it mean that some other application can see partial transaction log files, mid-write?

Answer from Shixiong Zhu, author of https://github.com/delta-io/delta/commit/7a3f1e8ec626e80880d524c2b897a969c8b4d63a

> The current rename implementation of GCS FileSystem is not atomic. We did some stress test and noticed that when renames are executed in parallel, they can overwrite each other. But writing directly is atomic. Currently GCS’s create output stream API ensures that if close is not called, the file will not be visible. And if a concurrent file is written, it will fail.


Still unclear to me:

> When writing a file on GCS, if the current thread is interrupted, GCS may close the partial write and upload the incomplete file.

When would the current thread get interrupted and why is the workaround of creating a separate writing thread effective.

2022-05-19 10:26 UTC, findepi requested changes
Pending discussion https://trinodb.slack.com/archives/C03E2DYAS0J/p1652955982462199?thread_ts=1652361711.683369&cid=C03E2DYAS0J

2022-05-21 22:47 UTC, findinpath commented
Updated implementation by making use directly of  Storage Cloud Storage API client instead of the letting `hadoop-connectors` library to create a `FSDataOutputStream` .
The client is used for fine-tuning an API Insert call in order to be able to create the blob corresponding to
the transaction log file.

2022-08-16 13:34 UTC, findinpath commented
Opt for the https://github.com/trinodb/trino/pull/12523 implementation because it doesn't use reflection.

2022-08-16 13:34 UTC, closed without merging