Document client timeout in query management properties
trinodb/trino pull request #12327
Opened 2022-05-10 19:26 UTC by Colebow

## Description

This is a simple fix to include the property for client timeout. We decided not to editorialize with the message that this shouldn't be changed.

> Is this change a fix, improvement, new feature, refactoring, or other?
Improvement

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
Documentation

> How would you describe this change to a non-technical end user or system administrator?
We are adding documentation!

## Related issues, pull requests, and links

## Documentation

( ) No documentation is needed.
(x) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-05-10 19:27 UTC, Colebow commented
<img width="778" alt="image" src="https://user-images.githubusercontent.com/104291808/167706839-774b8e97-d30f-4ff1-a0d0-e08b03478666.png">

2022-05-10 19:28 UTC, Colebow commented
<img width="778" alt="image" src="https://user-images.githubusercontent.com/104291808/167706839-774b8e97-d30f-4ff1-a0d0-e08b03478666.png">

2022-05-12 19:32 UTC, mosabua requested changes

2022-05-12 19:32 UTC, mosabua commented on docs/src/main/sphinx/admin/properties-query-management.rst
> +Configures how long the cluster will run without contact from the client before
also maybe use "client application, such as the CLI, before"

2022-05-16 21:10 UTC, mosabua approved these changes

2022-05-20 17:42 UTC, electrum approved these changes

2022-05-20 17:42 UTC, electrum commented on docs/src/main/sphinx/admin/properties-query-management.rst
> +* **Default value:** ``10m``
Should be `5m`

2022-05-23 19:21 UTC, colebow commented
@electrum updated the value, can we get this merged?

2022-05-23 20:16 UTC, jhlodin approved these changes

2022-05-25 19:16 UTC, mosabua commented
@martint can we get this merged?

2022-05-26 00:35 UTC, merged