Document JSON value constructors
trinodb/trino pull request #12677
Opened 2022-06-03 11:54 UTC by kasiafi

Documentation for https://github.com/trinodb/trino/pull/12049.

2022-06-03 14:39 UTC, mosabua requested changes
Great job. Just minor things. 

One question I have .. you chose to not use sql for the code blocks but text instead .. and also did not rely on the the :: before the snippets. Is that on purpose because it does not work somehow for you? If not .. we might want to change them all

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +Trino also supports two functions for generating JSON data:
either make it a sentence without a : .. or keep the : but then actually enumerate them in a list. In this case I would probably just replace : with -

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +You can also nest other json-returning functions. In that case, the ``FORMAT``
JSON-returning

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +    SELECT json_array(json_query('{"key" : [  "value"  ]}', 'lax $.key'))
should we break the nested json_query in separate line below with indentation?

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +``null`` is added to the result. ``ABSENT ON NULL`` is default.
is the default.

or 

is the default configuration.

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +    SELECT json_array(true, null, 1)                --> '[true,1]'
should we put result in next line and add empty line after like in other snippets below .. it make it nicer to read and to cut and paste from..

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +By default, the ``json_array`` function returns varchar containing textual
containing the textual

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +The ``json_object`` function Creates a JSON object containing given key-value pairs.
creates

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +into a JSON item according to its type and optional ``FORMAT`` and ``ENCODING``
type, and

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +binary strings with specified format and optional encoding:
with a specified

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +You can also nest other json-returning functions. In that case, the ``FORMAT``
JSON-returning

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +    SELECT json_object('x' : null, 'y' : 1)                --> '{"x":null,"y":1}'
Again .. maybe break up

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +
remove empty line

2022-06-03 14:39 UTC, mosabua commented on docs/src/main/sphinx/functions/json.rst
> +Note that this option is not supported if any of the arguments has
has a

2022-06-06 11:19 UTC, losipiuk approved these changes

2022-06-08 07:15 UTC, merged