Attach weights to DeltaLakeSplits
trinodb/trino pull request #12755
Opened 2022-06-09 05:50 UTC by ebyhr

## Description

Attach weights to DeltaLakeSplits.

## Documentation

(x) Sufficient documentation is included in this PR.

## Release notes

(x) Release notes entries required with the following suggested text:

```markdown
# Delta Lake
* Use split weights to improve scheduling and query performance on tables with many small files.  ({issue}`xxx`)
```

2022-06-09 13:50 UTC, alexjo2144 requested changes

2022-06-09 13:50 UTC, alexjo2144 commented on plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplit.java
> +    private final SplitWeight splitWeight;
Nit: match the order from the constr, put this between addresses and statisticsPredicate

2022-06-09 13:50 UTC, alexjo2144 commented on plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
> +                    SplitWeight.fromProportion(Math.min(Math.max((double) fileSize, minimumAssignedSplitWeight), 1.0)),
This is always going to be `1.0`. I think for non-splittable queries it's okay to just always set this as `SplitWeight.standard()`. This is only used for update/delete queries anyway

2022-06-09 13:50 UTC, alexjo2144 commented on plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
> +                    SplitWeight.fromProportion(Math.min(Math.max((double) fileSize / splitSize, minimumAssignedSplitWeight), 1.0)),
`fileSize / splitSize` I think what we want here is the `splitSize` divided by the intended split size. 

Tweaked from the code above:
```
            long maxSplitSize;
            if (remainingInitialSplits.get() > 0 && remainingInitialSplits.getAndDecrement() > 0) {
                maxSplitSize = getMaxInitialSplitSize(session).toBytes();
            }
            else {
                maxSplitSize = getMaxSplitSize(session).toBytes();
            }
            long splitSize = Math.min(maxSplitSize, fileSize - currentOffset);

            SplitWeight weight = SplitWeight.fromProportion(Math.min(Math.max((double) splitSize / maxSplitSize, minimumAssignedSplitWeight), 1.0))
```

2022-06-10 12:59 UTC, alexjo2144 approved these changes

2022-06-14 07:27 UTC, findepi approved these changes

2022-06-14 07:27 UTC, findepi commented on plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
> +                    SplitWeight.fromProportion(Math.min(Math.max((double) splitSize / maxSplitSize, minimumAssignedSplitWeight), 1.0)),
`Math.min( ..., 1)` is redundant per my understanding.

nit: static import min & max

2022-06-14 07:28 UTC, findepi commented on plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
> +                    SplitWeight.fromProportion(Math.min(Math.max((double) splitSize / maxSplitSize, minimumAssignedSplitWeight), 1.0)),
> `Math.min( ..., 1)` is redundant per my understanding.

ie if we somehow end up creating an oversized split, it's fine to let the engine know about that.

2022-06-14 07:32 UTC, findepi commented
@ebyhr you can merge this as is and i will update https://github.com/trinodb/trino/pull/12832 to cover Delta too.

2022-06-14 08:02 UTC, ebyhr commented
Let me merge this as-is. Thanks for your follow-up PR.

2022-06-14 08:02 UTC, merged