Add Trino 387 release notes
trinodb/trino pull request #12881
Opened 2022-06-16 21:02 UTC by colebow

## Description

Assemble the release notes for the upcoming Trino 387 release.

> Is this change a fix, improvement, new feature, refactoring, or other?

Improvement

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Docs only.

> How would you describe this change to a non-technical end user or system administrator?

Add the release notes for Trino 387 with sections for general, security, connectors and other topics as included in the release.

## Related issues, pull requests, and links

Fixes #12870

## Documentation

( ) No documentation is needed.
(✅) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(✅) No release notes entries required.
( ) Release notes entries required with the following suggested text:

## Verification for each commit

Format: commit, committer/maintainer, PR/issue number, ✅ / ❌ rn ✅ / ❌ docs
✅ rn - release note added and verified, or assessed to be not necessary, set to ❌ rn before completion
✅ docs - need for docs assessed and merged, or assessed to be not necessary, set to ❌ docs before completion

## 10 June 2022

2022-06-17 01:08 UTC, ebyhr commented on docs/src/main/sphinx/release/release-387.md
> +* Add support for `data_size` clause when analyzing a table. ({issue}`12814`)
`data_size` isn't clause. "Support collecting data size when analyzing a table" might be better.

2022-06-20 10:08 UTC, ebyhr commented on docs/src/main/sphinx/release/release-387.md
> +* Prevent modifying old snapshots. ({issue}`12860`)
Can we change to `Fail queries that attempt to modify old snapshots`?

cc: @findepi

2022-06-22 17:43 UTC, martint requested changes

2022-06-22 17:43 UTC, martint commented on docs/src/main/sphinx/release/release-387.md
> +* Add support for parameters in table function arguments.
> Add support for **query** parameters ...

2022-06-22 18:41 UTC, martint commented on docs/src/main/sphinx/release/release-387.md
> +* Add support for ORC bloom filters on `string`-typed columns. ({issue}`11757`)
"varchar" instead of "string", since `string` is not a proper Trino type.

2022-06-22 21:58 UTC, mosabua commented on docs/src/main/sphinx/release/release-387.md
> +* Deprecate using mangled table names for Iceberg snapshot access in favor of
what is a "mangled" table name

2022-06-22 21:59 UTC, mosabua commented on docs/src/main/sphinx/release/release-387.md
> +* Update minimum required Java version to 11.0.15. ({issue}`12841`)
uff

2022-06-22 22:00 UTC, mosabua commented on docs/src/main/sphinx/release/release-387.md
> +* Enable optimized Parquet writer by default. This can be disabled via the
```suggestion
* Enable the optimized Parquet writer by default. This can be disabled with the
```

2022-06-22 22:00 UTC, mosabua commented on docs/src/main/sphinx/release/release-387.md
> +* Add support for ORC bloom filters on `varchar`-typed columns. ({issue}`11757`)
I think we can omit "-typed"

2022-06-22 22:02 UTC, mosabua requested changes
A couple of minor things

2022-06-22 22:04 UTC, ebyhr commented on docs/src/main/sphinx/release/release-387.md
> +* Disallow adding a new column when a table has an unsupported writer version. ({issue}`12883`)
Delta Lake protocol has `minWriterVersion` field and the connector doesn't support writer versions > 2. 
https://github.com/delta-io/delta/blob/master/PROTOCOL.md#writer-version-requirements

2022-06-22 22:45 UTC, merged