Disable Ryuk testcontainer container
trinodb/trino pull request #13099
Opened 2022-07-06 09:29 UTC by kokosing

Disable Ryuk testcontainer container

We are closing all containers in tests, also we don't reuse CI
workers so ryuk for cleanup is not really needed.
Downloading ryuk image is flaky.

2022-07-06 09:37 UTC, nineinchnick approved these changes

2022-07-06 13:20 UTC, wendigo approved these changes

2022-07-08 12:06 UTC, ppalucha approved these changes

2022-07-18 07:46 UTC, hashhar approved these changes

2022-07-20 15:14 UTC, findepi requested changes
> Q: Don't we still need Ryuk in cases where we run multiple profiles or modules in single CI job?

We may implicitly depend on it

> We are closing all containers in tests

i hope this is true, but we have no means to verify that.
i've seen many tests where this **was not** the case (have fixed them), so I assume this may not be the case in the future

2022-07-20 15:14 UTC, findepi commented
> Downloading ryuk image is flaky.

i haven't seen ryuk being more flaky than other containers since they moved to docker hub.
but that's something we could perhaps fix

2022-07-21 03:11 UTC, kokosing commented
I have seen, hence the PR. It was a period where random jobs were failing being unable to download ryuk.

However if we see a problems with downloading ryuk, then skipping it is not helping much as we can likely hit same issue with next image to download.

This PR would make CI a bit faster as we don't need to download that image and setup a container. And potentially likelihood of flaky is lower.

2022-07-23 22:11 UTC, closed without merging