Add launcher command section
trinodb/trino pull request #13129
Opened 2022-07-08 16:40 UTC by Jessie212

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

Improvement.

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Changes were made to documentation only.

> How would you describe this change to a non-technical end user or system administrator?

Add launch command section to Trino deployment page.

## Related issues, pull requests, and links

## Documentation

( ) No documentation is needed.
(x) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-07-08 19:47 UTC, martint commented on docs/src/main/sphinx/installation/deployment.rst
> +   server_log      = /opt/starburst/var/log/server.log
Use /etc/trino, /opt/trino, etc.

2022-07-08 19:47 UTC, martint commented on docs/src/main/sphinx/installation/deployment.rst
> +accepts six commands:
> *these* commands

So that we don't have to keep it in sync with the list below.

2022-07-14 16:03 UTC, mosabua requested changes
Needs reorder and fix ups

2022-07-14 16:24 UTC, mosabua commented on docs/src/main/sphinx/installation/deployment.rst
> +The installation provides a ``bin/launcher`` utility, which requires Python in
lets call it "script" .. not "utility"

2022-07-14 16:28 UTC, mosabua commented on docs/src/main/sphinx/installation/deployment.rst
> +A number of additional options allow you to specify non-default configuration
Lets move this up and have the -v stuff afterwards

2022-07-14 17:05 UTC, mosabua commented on docs/src/main/sphinx/installation/deployment.rst
> +current settings before the command's usual output, much like the following
```suggestion
current settings before the command's usual output. For example, you can start a Trino installation in ``/opt/trino`` and get out similar to the following:
```

2022-07-14 17:07 UTC, mosabua commented on docs/src/main/sphinx/installation/deployment.rst
> +   config_path     = /etc/trino/config.properties
Replace this snippet with

```
$ cd /opt/trino
$ bin/launcher -v status
config_path     = /opt/trino/etc/config.properties
data_dir        = /opt/trino
etc_dir         = /opt/trino/etc
install_path    = /opt/trino
jvm_config      = /opt/trino/etc/jvm.config
jvm_options     = []
launcher_config = /opt/trino/bin/launcher.properties
launcher_log    = /opt/trino/var/log/launcher.log
log_levels      = /opt/trino/etc/log.properties
log_levels_set  = False
node_config     = /opt/trino/etc/node.properties
pid_file        = /opt/trino/var/run/launcher.pid
properties      = {'node.environment': 'mm_demo'}
server_log      = /opt/trino/var/log/server.log
verbose         = True

Not running
```

2022-07-14 17:08 UTC, mosabua reviewed
Clarified some more stuff in the comments.

2022-07-14 17:24 UTC, mosabua reviewed
Some of the stuff later down should be cleaned up as well .. ping me if you want to fine tune together @Jessie212

2022-07-14 18:00 UTC, Ordinant approved these changes
Looks fine to me, but I didn't check line wrapping issues.

2022-07-14 20:51 UTC, mosabua approved these changes
Nice addition.

2022-07-14 20:54 UTC, mosabua commented
This is ready now @martint  .. for merge right after the release is done ;-)

2022-07-21 22:49 UTC, mosabua commented
Build failure is wrong. I just built locally.

2022-07-21 22:57 UTC, merged