Test tableFunctions and tableProcedures in MockConnector
trinodb/trino pull request #13127
Opened 2022-07-08 14:01 UTC by ssheikin

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?
tests

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

> How would you describe this change to a non-technical end user or system administrator?

## Related issues, pull requests, and links

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-07-08 14:29 UTC, ksobolew approved these changes
Nice!

2022-07-08 15:25 UTC, ssheikin commented
Something happened with automation here.
Is it common issue? Can we do something about it?

2022-07-09 10:09 UTC, kasiafi requested changes
This PR is mostly about Table Procedures, as it adds support for testing them with the MockConnector.
Regarding Table Functions, it only tests the MockConnector, not the Table Functions themselves.
Please split the PR into 2 commits accordingly.

2022-07-09 10:09 UTC, kasiafi commented on testing/trino-tests/src/test/java/io/trino/function/TestingConnectorTableFunction.java
> +public class TestingConnectorTableFunction
We've got a class `TestingTableFunctions`. Currently it has one TF implementation. You can use te existing implementation or add your implementation there.

2022-07-10 09:40 UTC, ssheikin commented
That's because I had to rebase on your latest changes :)

2022-07-15 17:37 UTC, kokosing approved these changes
@kasiafi It looks like comments got addressed. It is all about tests so it is safe to merge. Please let me know if something is missing, @ssheikin will be more than happy to post another PR to address remaining comments. I will merge it to unblock the further work.

2022-07-17 08:47 UTC, kasiafi approved these changes

2022-07-17 08:49 UTC, kasiafi commented
CI failure: please update the expected message:
```
[ERROR] io.trino.tests.TestMockConnector.testTableFunction  Time elapsed: 0.052 s  <<< FAILURE!
2022-07-15T18:16:39.7278677Z java.lang.AssertionError: 
2022-07-15T18:16:39.7279090Z 
2022-07-15T18:16:39.7279334Z Expecting message to be:
2022-07-15T18:16:39.7279760Z   <"execution by operator is not yet implemented for table function testing_table_function">
2022-07-15T18:16:39.7280142Z but was:
2022-07-15T18:16:39.7280494Z   <"execution by operator is not yet implemented for table function simple_table_function">
```

2022-07-19 04:08 UTC, merged