Remove LIKE operator reference from regexp_like doc
trinodb/trino pull request #13419
Opened 2022-07-29 19:20 UTC by sheajamba

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

Improvement
> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Regular expressions documentation

> How would you describe this change to a non-technical end user or system administrator?

Removes references to the LIKE operator which can cause confusion for those who are familiar with the RLIKE operator from Hive and MySQL.

## Related issues, pull requests, and links

## Documentation

( ) No documentation is needed.
(x) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-07-29 19:49 UTC, mosabua requested changes

2022-07-29 19:49 UTC, mosabua commented on docs/src/main/sphinx/functions/regexp.rst
> -    needing to match all of ``string``. In other words, this performs a
You still need to have some of that info

2022-08-05 22:08 UTC, mosabua approved these changes
Looks good now and reduces the confusion with the SQL LIKE ..

2022-08-06 12:28 UTC, hashhar approved these changes

2022-08-06 12:29 UTC, merged