[doc] System property required for JMX setup
trinodb/trino pull request #13466
Opened 2022-08-02 15:18 UTC by honnix

## Description
System property required for JMX setup.

Without it, JVM throws an exception complaining:

```
java.lang.RuntimeException: System property 'com.sun.management.jmxremote.rmi.port=null' does match configured RMI server port 9081
```

> Is this change a fix, improvement, new feature, refactoring, or other?
A doc improvement.

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
No.

> How would you describe this change to a non-technical end user or system administrator?
NA

## Related issues, pull requests, and links
It was first reported by https://github.com/trinodb/trino/issues/7843

## Documentation

( ) No documentation is needed.
(x) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-08-02 15:27 UTC, honnix commented
_I'm working the CLA thing._

2023-07-07 18:08 UTC, mosabua approved these changes

2023-07-07 18:09 UTC, mosabua requested changes
Minor edit .. but we also need a signed CLA to merge. Could you send that?

2023-07-07 18:09 UTC, mosabua commented on docs/src/main/sphinx/admin/jmx.rst
> +:ref:`jvm.config file <jvm_config>`:
```suggestion
:ref:`jvm.config <jvm_config>` with the RMI server port:
```

2023-07-07 22:12 UTC, honnix commented
> Minor edit .. but we also need a signed CLA to merge. Could you send that?

Thank you for reminding me of this PR. I will try to get a CLA signed.

2023-07-10 17:11 UTC, mosabua commented
Please squash the commits if possible and make sure you send a CLA.

2023-08-11 22:32 UTC, mosabua commented
Can you rebase this into the new jmx.md file and submit a CLA?

2023-08-12 06:09 UTC, honnix commented
Sure I can do that. Unfortunately the CLA is taking too much time to get. If you think this PR is useful, I don't mind at all you applying the change in another PR. @mosabua

2023-08-15 19:32 UTC, closed without merging

2023-08-16 16:06 UTC, mosabua commented
Linked PR is merged @honnix so this will go live with the 424 release

2023-08-16 16:10 UTC, honnix commented
Thank you @mosabua !