Add fragments for Avro, ORC, and Parquet mappings
trinodb/trino pull request #13752
Opened 2022-08-19 14:03 UTC by Jessie212

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

Improvement.

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Changes made to documentation.

> How would you describe this change to a non-technical end user or system administrator?

Add fragments for Avro, ORC, and Parquet mappings to type mapping section.

## Related issues, pull requests, and links

## Documentation

( ) No documentation is needed.
(x) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-08-19 19:36 UTC, jhlodin requested changes
With this approach we're looking at up to 6 extremely vertical tables for three already long connector pages, are we sure there's not a more compact approach? Like the usual two tables for each direction, but with additional column(s) describing support for each file format?

2022-08-19 19:36 UTC, jhlodin commented on docs/src/main/sphinx/connector/avro-type-mapping.fragment
> +No to other types are supported.
No other

2022-08-19 19:36 UTC, jhlodin commented on docs/src/main/sphinx/connector/avro-type-mapping.fragment
> +The connector maps Trino| types to the corresponding Avro types following
Remove |

2022-08-22 16:02 UTC, jhlodin commented
> > With this approach we're looking at up to 6 extremely vertical tables for three already long connector pages, are we sure there's not a more compact approach? Like the usual two tables for each direction, but with additional column(s) describing support for each file format?
> 
> The tables, as they are, are already quite squished. Adding additional rows might make the text unreadable, especially if there's a notes column.

@Jessie212 Horizontally squished? We could just adjust the column widths if we need to give the text breathing room

2022-08-22 19:56 UTC, alexjo2144 commented
Can we just add links to
- Avro: https://iceberg.apache.org/spec/#avro
- Parquet: https://iceberg.apache.org/spec/#parquet
- ORC: https://iceberg.apache.org/spec/#orc 

And leave the existing table?

2022-08-22 20:04 UTC, Jessie212 commented
> Can we just add links to
> 
>     * Avro: https://iceberg.apache.org/spec/#avro
> 
>     * Parquet: https://iceberg.apache.org/spec/#parquet
> 
>     * ORC: https://iceberg.apache.org/spec/#orc
> 
> 
> And leave the existing table?

Are types in the **Type** column Trino data types?

2022-08-22 21:04 UTC, Jessie212 commented
To make sure I understand: 

1) The unspecified "Type" in the Apache link is actually Iceberg: Iceberg -> Avro, Iceberg -> Parquet, Iceberg -> ORC?

2) In our docs, we substitute the Trino types with Iceberg so the table shows Iceberg to file type only? No mention of Trino?

2022-08-22 21:04 UTC, Jessie212 commented
To make sure I understand: 

1) The unspecified "Type" in the Apache link is actually Iceberg: Iceberg -> Avro, Iceberg -> Parquet, Iceberg -> ORC?

2) In our docs, we substitute the Trino types with Iceberg so the table shows Iceberg to file type only? No mention of Trino?

2022-08-22 21:24 UTC, alexjo2144 commented
> The unspecified "Type" in the Apache link is actually Iceberg: Iceberg -> Avro, Iceberg -> Parquet, Iceberg -> ORC?

Yes

> In our docs, we substitute the Trino types with Iceberg so the table shows Iceberg to file type only? No mention of Trino?

The current documentation shows Trino <-> Iceberg

2022-08-22 21:36 UTC, Jessie212 commented
> The current documentation shows Trino <-> Iceberg

What I meant was, we should modify the current docs to show Iceberg in the place of Trino.

2022-09-12 17:15 UTC, alexjo2144 commented on docs/src/main/sphinx/connector/iceberg.rst
> +  * - ``MAP``
The k, v here was important, I'd leave that in
```suggestion
  * - ``MAP(k,v)``
```

2022-09-12 17:15 UTC, alexjo2144 commented on docs/src/main/sphinx/connector/iceberg.rst
> +    - ``BINARY``
Trino doesn't have a Binary type. No Trino types map to the Iceberg `Fixed` type.
```suggestion
```

2022-09-12 17:15 UTC, alexjo2144 commented on docs/src/main/sphinx/connector/iceberg.rst
> +    - ``MAP``
Here also, I think the k, v is important
```suggestion
    - ``MAP(k, v)``
```

2022-09-12 17:15 UTC, alexjo2144 commented on docs/src/main/sphinx/connector/iceberg.rst
> +    - ``BINARY``
```suggestion
    - ``VARBINARY``
```

2022-09-12 17:15 UTC, alexjo2144 commented on docs/src/main/sphinx/connector/iceberg.rst
> +    - ``BINARY``
This is a duplicate of the Binary -> Varbinary two lines above
```suggestion
```

2022-09-15 18:02 UTC, alexjo2144 approved these changes
Reads well to me

2022-10-04 08:07 UTC, findepi commented
Thanks @alexjo2144 for your review

2022-10-04 08:07 UTC, merged