Edit release notes checklist in PR template
trinodb/trino pull request #14018
Opened 2022-09-06 17:30 UTC by colebow

## Description

Update the PR template to use a GitHub task list in the release notes section, and also add an option for "this is a docs change and no release notes are required," because docs are user-visible but don't require release notes.

## Non-technical explanation

Update PR template.

## Release notes

(x) This is not user-visible and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

2022-09-06 17:32 UTC, colebow commented
Something worth pointing out:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/104291808/188701638-c6e85ea8-cc2c-40d4-b885-879aa9b779b0.png">

We're going to see lots of 1/4 tasks complete on PRs, not sure if that's necessarily an issue, but it's at least a little annoying/suboptimal.

2022-09-06 18:15 UTC, mosabua requested changes
We should NOT use `[]` since the interferes with the GitHub actions reporting for build and CLA check and so on. We tried that initially with the template and it did not go well.

2022-09-06 18:16 UTC, colebow commented
Are you sure? From the tests that @findepi and I have run, it doesn't seem like it's getting in the way?

2022-09-06 18:22 UTC, mosabua commented
> Are you sure? From the tests that @findepi and I have run, it doesn't seem like it's getting in the way?

Hm .. interesting.. maybe they updated how this works. In either case .. since this list is a choice and not a task list I still think the reporting is misleading and we are better off not doing that. Is there any issue with the current setup and e.g. use `(x)` or (✅ ) or even just suggesting usage of ✅ and ❌ ?

2022-09-06 19:06 UTC, colebow commented
I think I'm in agreement that task lists are not good, because GitHub integrates and visualizes them in a misleading way.

2022-09-06 19:36 UTC, findepi commented
@colebow i suggest checkboxes because

- it allows easy edit in an intuitive way. Placing `x` within misaligned (non-monosapce font rendered) braces is not intuitive
- it is very easy to read, as marked checkbox stands out


the interference with actions checkboxes or other aspects of PR status -- please do not worry about that. I'd let @trinodb/maintainers worry about that. It's their job to understand whether a thing is merge-ready.


**IF** we start to use checkboxes for things related to PR status **THEN** we may want to edit docs-related PR template, as it would **THEN** interfere with how we interpret the PR status / merge-readiness.

2022-09-06 19:36 UTC, findepi requested changes
.

2022-09-06 19:37 UTC, findepi commented on .github/pull_request_template.md
> +( ) This is a docs change and no release notes are required.
Don't add more bullet points. Just reword the first one.

2022-09-12 21:21 UTC, ebyhr approved these changes

2022-09-13 15:02 UTC, findepi commented on .github/pull_request_template.md
> +( ) This is not user-visible or docs only and no release notes are required.
```suggestion
- [ ] The change is not user-visible, or is docs only change, and no release notes are required.
```

?

2022-09-13 16:38 UTC, mosabua commented on .github/pull_request_template.md
> +( ) This is not user-visible or docs only and no release notes are required.
or affects documentation only

2022-09-19 18:01 UTC, colebow commented
So as far as the checkboxes are concerned:

- I think the upgrade they provide is minimal (instead of typing x, you click)
- I think the downside they provide (surfacing an entirely new element of the GitHub UI, which is then misleading - see my first comment on this PR) is suboptimal and worth avoiding unless there is a very convincing reason

2022-09-19 19:52 UTC, merged

2022-09-19 19:53 UTC, findepi commented
whether "(instead of typing x, you click" is "minimal" or "surfacing an entirely new element of the GitHub UI" is important sounds subjective

To me, "instead of typing x, you click" is non-negligible thing. How are you making sure you're subjective truth is more right?