Add stage details and query plan details to QueryCompletedEvent
trinodb/trino pull request #14143
Opened 2022-09-15 14:18 UTC by hiralbest

## Description

## Non-technical explanation

## Release notes

( ) This is not user-visible and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-09-16 07:49 UTC, hiralbest commented on core/trino-spi/pom.xml
> +            <scope>provided</scope>
@pr-reviewers : Is it okay to have scope provided?
If not added then the following error happens.
<img width="1351" alt="Screen Shot 2022-09-14 at 3 44 35 PM" src="https://user-images.githubusercontent.com/6665626/190585529-284ce7a4-5ddd-442e-9831-68f4a4b7705f.png">

2022-09-16 08:54 UTC, hiralbest commented
Submitted CLA to cla@trino.io with subject line as "Signed CLA for Trino - hiralbest Github User"

2022-09-19 13:43 UTC, assaf2 commented
Can you please describe the motivation for this change?

2022-09-27 17:54 UTC, electrum commented
@cla-bot check

2022-09-27 18:04 UTC, electrum requested changes

2022-09-27 18:04 UTC, electrum commented on core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
> +    private static BigDecimal toDecimalMillis(Duration dur)
Don't abbreviate

2022-09-27 18:04 UTC, electrum commented on core/trino-spi/src/main/java/io/trino/spi/eventlistener/TaskDetails.java
> +        return Objects.hash(id, nodeHost, state);
Why this definition? Why do we define equals/hashcode at all?

2022-09-27 18:11 UTC, martint commented on core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryPlanDetails.java
> +public class QueryPlanDetails
The event already contains query plan details (see io.trino.spi.eventlistener.QueryMetadata). Adding QueryPlanDetails and QueryPlanNodeInfo introduces duplication and makes the API more confusing.

2022-09-27 18:16 UTC, raunaqmorarka commented on core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
> +                createQueryPlanDetails(queryInfo));
We already provide a query plan in json format in `QueryCompletedEvent.metadata.jsonPlan`, can you use that instead of adding this ?

2022-09-27 18:45 UTC, raunaqmorarka commented on core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageDetails.java
> +    private final BigDecimal scheduledTime;
all the time fields should be Duration instead of BigDecimal

2022-09-27 18:45 UTC, raunaqmorarka commented on core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageStatistics.java
> +    private final int runningDrivers;
After a query has finished, we probably don't care about queued and running drivers

2022-09-27 18:45 UTC, raunaqmorarka commented on core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageStatistics.java
> +    private final DataSize userMemoryReservation;
Should be peakUserMemoryReservation, assuming we track that, since it is not useful to know userMemoryReservation at the end of a query

2022-09-27 18:45 UTC, raunaqmorarka commented on core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageStatistics.java
> +    private final DataSize rawInputDataSize;
raw -> physical

2022-09-27 18:45 UTC, raunaqmorarka commented on core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageStatistics.java
> +    private final boolean fullyBlocked;
Doesn't seem relevant once the query is finished

2022-09-27 18:45 UTC, raunaqmorarka commented on core/trino-spi/src/main/java/io/trino/spi/eventlistener/TaskDetails.java
> +    private final long bytesBuffered;
Should be peakBufferedDataSize, if we track that, since it is not useful to know bufferedDataSize at the end of a query

2022-10-03 09:20 UTC, hiralbest commented
Closing this PR since fields from newly added fields are already present in QueryMetadata. Thanks, everyone for reviewing and providing good pointers.

2022-10-03 09:20 UTC, closed without merging