Add verification step for HTTPS/TLS docs
trinodb/trino pull request #14297
Opened 2022-09-26 17:44 UTC by sheajamba

## Description
Adds a verification step to the Trino security overview page with a link to the steps to verify HTTPS/TLS configuration. 

## Non-technical explanation
Helps users verify if they have HTTPS/TLS configured correctly. 

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-09-26 17:54 UTC, dain approved these changes

2022-09-26 17:54 UTC, dain commented on docs/src/main/sphinx/security/tls.rst
> +To verify TLS/HTTPS configuration, log in to the :doc:`Web UI
may add a "you should" in here otherwise it reads as the instructions, which are below, and not a summary

2022-09-26 18:39 UTC, mosabua requested changes

2022-09-26 18:39 UTC, mosabua commented on docs/src/main/sphinx/security/tls.rst
> +  URL that begins with ``HTTPS``, such as ``https://example.net:8080``. Enter
dont use 8080 for https .. probably use 8443 .. or if behind a load balancer its just without port

also make it consistent with other example URLs on this page

2022-09-26 18:39 UTC, mosabua commented on docs/src/main/sphinx/security/tls.rst
> +  Note: The ``Password`` box is disabled while :doc:`authentication
just make this a sentence .. drop the "Note"

2022-09-26 18:39 UTC, mosabua commented on docs/src/main/sphinx/security/tls.rst
> +    trino> --server https://example.net:8080
wrong syntax and remote port

2022-10-18 16:59 UTC, mosabua requested changes

2022-10-18 16:59 UTC, mosabua commented on docs/src/main/sphinx/security/tls.rst
> +To verify TLS/HTTPS configuration, you should log in to the :doc:`Web UI
```suggestion
To verify TLS/HTTPS configuration, log in to the :doc:`Web UI
```

2022-10-18 16:59 UTC, mosabua commented on docs/src/main/sphinx/security/tls.rst
> +  ``HTTPS``, such as ``https://trino.example.com:8443``. Enter any username into
either https:// or say "uses HTTPS"

2022-10-18 16:59 UTC, mosabua commented on docs/src/main/sphinx/security/tls.rst
> +* Connect to the Trino CLI using a URL that begins with ``HTTPS``, such as
```suggestion
* Connect with the Trino CLI using a URL that uses HTTPS, such as
```

2022-10-18 20:04 UTC, mosabua approved these changes
Looks great now. Can you merge this @dain

2022-10-24 20:39 UTC, merged