Add verification step for authentication docs
trinodb/trino pull request #14353
Opened 2022-09-28 18:23 UTC by sheajamba

## Description
Adds a verification step to the Trino security overview page with a link to the steps to verify user/password configuration.

## Non-technical explanation

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-11-01 20:15 UTC, mosabua requested changes

2022-11-01 20:15 UTC, mosabua commented on docs/src/main/sphinx/security/password-file.rst
> +</admin/web-interface>`, and connect to the Trino :doc:`CLI </client/cli>`.
and connect with the Trino CLI to the cluster

2022-11-01 20:15 UTC, mosabua commented on docs/src/main/sphinx/security/password-file.rst
> +    Password:
remove that

2022-11-01 20:15 UTC, mosabua commented on docs/src/main/sphinx/security/password-file.rst
> +Send a query:
Once connected .. you can send query to test

2022-11-07 22:18 UTC, mosabua requested changes

2022-11-07 22:18 UTC, mosabua commented on docs/src/main/sphinx/security/password-file.rst
> +the cluster.
```suggestion
the cluster:
```

2022-11-07 22:18 UTC, mosabua commented on docs/src/main/sphinx/security/password-file.rst
> +  and password combination.
Add that the username is shown in the top right corner after logging in successfully.

2022-11-07 22:18 UTC, mosabua commented on docs/src/main/sphinx/security/password-file.rst
> +
Add that this quotes you for the password and after supplying you get the trino> prompt from the CLI and you can proceed to run a query

2022-12-06 22:06 UTC, mosabua approved these changes
Looks good now as well

2022-12-06 22:28 UTC, electrum approved these changes

2022-12-06 22:28 UTC, merged