Add verification step for authoirzation docs
trinodb/trino pull request #14379
Opened 2022-09-29 16:27 UTC by sheajamba

## Description

Adds a verification step to the Trino security overview page with a link to the steps to verify system-level rules file.

## Non-technical explanation

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-09-29 17:45 UTC, mosabua requested changes

2022-09-29 17:45 UTC, mosabua commented on docs/src/main/sphinx/security/file-system-access-control.rst
> +To verify the system-access control file is configured properly, you should set
you set the rules to the following configuration:

2022-09-29 17:45 UTC, mosabua commented on docs/src/main/sphinx/security/file-system-access-control.rst
> +From the Trino :doc:`CLI </client/cli>`, run query:
Restart your cluster to activate the cluster, and then from ...

2022-09-29 17:45 UTC, mosabua commented on docs/src/main/sphinx/security/file-system-access-control.rst
> +Remove these rules and restart the Trino server.
```suggestion
Remove these rules and restart the Trino cluster.
```

2022-11-15 21:22 UTC, mosabua approved these changes
Looks good now.

2022-11-15 21:22 UTC, mosabua commented
@dain can you give this a quick glance and merge?

2022-12-06 22:26 UTC, electrum approved these changes

2022-12-06 22:26 UTC, merged