Rewrite temporal casts comparation on ranges
trinodb/trino pull request #14390
Opened 2022-09-30 05:30 UTC by findinpath

## Description

This change allows the engine to infer that, for instance,
given t::timestamp(6)

```
    date_trunc('day', t) BETWEEN TIMESTAMP '2022-01-01 00:00:00' AND TIMESTAMP '2022-01-02 00:00:00'
```

or 

```
   cast(t as date) BETWEEN TIMESTAMP '2022-01-01 00:00:00' AND TIMESTAMP '2022-01-02 00:00:00'
```

can be rewritten as

```
    t BETWEEN TIMESTAMP '2022-01-01 00:00:00' AND TIMESTAMP '2022-01-02 23:59:59.999999'
```

The change applies for the temporal types:
- `date`
- `timestamp`
- `timestamp with time zone`

Range predicate BetweenPredicate can be transformed into a `TupleDomain`
and thus help with predicate pushdown.
Range-based `TupleDomain` representation is critical for connectors
which have min/max-based metadata (like Iceberg manifests lists which
play a key role in partition pruning or Iceberg data files), as ranges allow
for intersection tests, something that is hard
to do in a generic manner for `ConnectorExpression`.

## Non-technical explanation

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Main
* Improve partition and data pruning when comparing temporal casts  with ranges
```

2022-10-02 07:20 UTC, findinpath commented
CI hit https://github.com/trinodb/trino/issues/11140

2022-10-03 14:11 UTC, findepi requested changes

2022-10-03 14:11 UTC, findepi commented on core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapDateTruncInComparison.java
> +                long endInclusiveMicros = (long) calculateRangeEndInclusive(longTimestamp.getEpochMicros(), createTimestampType(TimestampType.MAX_SHORT_PRECISION), rangeUnit);
the variable name is "endInclusiveMicros"
the code used 6 and it's know that 10^(-6)s is a microsecond.

after the change the code  uses TimestampType.MAX_SHORT_PRECISION. it's not obvious that it's correct (is short precision actually microseconds?). Thus, actually this change decreases readability

2022-10-03 14:11 UTC, findepi commented on core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapDateTruncInComparison.java
> +                return new LongTimestamp(endInclusiveMicros, toIntExact(PICOSECONDS_PER_MICROSECOND - scaleFactor(timestampType.getPrecision(), TimestampType.MAX_PRECISION)));
similar here. the use PICOSECONDS_PER_MICROSECOND mandates that we know we're dealing with picoseconds, i.e. 10^(-12)s, so it matched the corresponding 12 on this line

after the change, we invoke "max precision" constant, but we still rely on it having an actual value of 12

2022-10-03 14:14 UTC, findepi commented on core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java
> +            if (sourceType instanceof TimestampType && minType == DATE) {
These conditions aren't necessary

1. decompose between like in `io.trino.sql.planner.DomainTranslator.Visitor#visitBetweenPredicate`
2. delegate to `unwrapCast(ComparisonExpression)`

2022-10-03 14:14 UTC, findepi commented on core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java
> +        public Expression rewriteBetweenPredicate(BetweenPredicate node, Void context, ExpressionTreeRewriter<Void> treeRewriter)
Please update all three `TestUnwrapCastInComparison` classes.

2022-10-03 14:14 UTC, findepi commented on core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java
> +import io.trino.spi.type.DateType;
the commit title

> Unwrap casts in temporal range comparison expressions

-- can it include "between" somewhere in the title?

perhaps "Unwrap casts in BETWEEN predicate"

2022-10-03 14:15 UTC, findepi commented
@findinpath let's have unwrapping of CASTs and date_trunc as separate PRs.
I'd like to focus on casts first.

2022-10-04 06:20 UTC, findinpath commented
Continuing the work on #14451 and #14452

2022-10-04 06:20 UTC, closed without merging