Make Compiler cache to soft value reference to reduce metaspace oom
trinodb/trino pull request #15237
Opened 2022-11-29 12:46 UTC by zhangminglei

## Description
This PR can reduces metaspace oom issues, make some compiler that use guava value from strong reference to soft reference.

Fixes #15232 

## Additional context and related issues

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2022-11-30 12:01 UTC, findepi requested changes
> Make Compiler cache to soft value reference to reduce metaspace oom

Trino caches do not use soft references, to avoid "invalidation storm" when system would otherwise OOM.
Instead, the system needs to be configured so that it doesn't OOM at all.

Also, if we really want to change this direction -- first make sure we want, which I personally doubt -- and start using soft references for all the caches, the change should focus on ensuring that all new caches are soft. I.e. please think about how to automatically ensure that. Modernizer may be helpful here, or some other code analysis.

2022-11-30 12:01 UTC, findepi commented
cc @dain @lukasz-stec

2022-12-01 09:39 UTC, lukasz-stec commented
> Trino caches do not use soft references, to avoid "invalidation storm" when system would otherwise OOM.

Also, there are no guarantees for when soft references are freed other than before OOM. This can cause performance to be very variable.

That said, I see how cache size based on the number of elements can cause issues since the elements have variable lengths.
Generated classes bytecode, which I think is kept in the meta space, can vary between a few hundred bytes to hundreds of kilobytes or more.
One way to mitigate it is to limit the cache by bytes used (e.g. by using `com.google.common.cache.Weigher`).

2022-12-01 12:26 UTC, findepi commented
> That said, I see how cache size based on the number of elements can cause issues since the elements have variable lengths.

good point

This is also visible in https://github.com/trinodb/trino/issues/15232 description where singled out entry is 1/3 in size of the average

> One way to mitigate it is to limit the cache by bytes used (e.g. by using `com.google.common.cache.Weigher`).

let's do that -- unless we know that `max entry size * max entry count` is still acceptable cache occupancy.

cc @dain for function & expression execution
cc @martint for #14237

2022-12-02 03:04 UTC, zhangminglei commented
Thanks to @findepi @lukasz-stec for discussion and related ideas. Limit the cache by bytes used `com.google.common.cache.Weigher` seems to be a more acceptable way to solve this problem.  I'll revisit this issue in the near future and give some feedback or an update on the PR.

2022-12-03 09:24 UTC, zhangminglei commented
If we use ```weigher```  which requires calculate the class size of each entry value in ```int weight(K key, V value) ```. It seems that we can not find a suitable way to get it in currently. After discuss with @lukasz-stec , one possible solution is to modify  ```ClassGenerator``` in airlift that let it return the cached generated classes and its size, etc. In addition to this solution, do we have a better way to get the size of the class ?

2023-04-12 20:12 UTC, electrum commented
@zhangminglei apologies for the delay in responding.

I think the easiest way is to modify `DynamicClassLoader` in https://github.com/airlift/bytecode to have a method `getDefinedClassesBytecodeSize()`. It could track the size in `defineClass()`. We then add a method in `CompilerUtils`:
```java
public static long getBytecodeSize(Class<?> clazz)
{
    if (clazz.getClassLoader() instanceof DynamicClassLoader loader) {
        return loader.getDefinedClassesBytecodeSize();
    }
    throw new IllegalArgumentException("Invalid class loader [%s] for %s".formatted(clazz.getClassLoader(), clazz));
}

2024-01-11 23:24 UTC, mosabua commented
:wave: @zhangminglei  - this PR has become inactive. We hope you are still interested in working on it. Please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

2024-09-05 17:28 UTC, mosabua commented
Is this still relevant @electrum @findepi @rice668 ?

2024-09-05 17:56 UTC, electrum commented
We can close this, as the cache weigher approach discussed above is a better direction.

2024-09-05 17:56 UTC, closed without merging