Homar/support cdf in vacuum in delta lake
trinodb/trino pull request #15663
Opened 2023-01-10 23:37 UTC by homar

## Description

## Additional context and related issues

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-01-20 17:07 UTC, alexjo2144 requested changes
Only reviewing last commit.

If my memory is right that checkpoint files don't contain CDC references, this is not going to work. If the most recent commit was checkpointed `getJsonTransactionLogEntries` is going to return an empty list and you'll miss some valid CDC files.

I would argue that what we have now is good enough, comparing the CDC file timestamp against the cutoff. It doesn't ensure that we keep the CDC files for the most recent checkpoint, but I don't think that's a big deal.

2023-01-20 17:07 UTC, alexjo2144 commented on plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeTransactionLogEntry.java
> +            @JsonProperty("cdc") CDFFileEntry cdfFileEntry)
Why?

2023-01-20 17:07 UTC, alexjo2144 commented on plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
> +        CDC("cdc");
I thought you said checkpoint files don't contain CDC information

2023-02-21 20:12 UTC, bitsondatadev commented
@homar, is this still being actively worked on?

2023-02-21 20:16 UTC, homar commented
> @homar, is this still being actively worked on?

Not actively, but I will work on this soon, this or next week.

2023-02-21 20:18 UTC, bitsondatadev commented
Sounds good :) I'll leave it alone!

2023-03-07 19:40 UTC, alexjo2144 commented
@homar do you want to convert this to a Databricks compatibility test so that it doesn't depend on you other PR?
Or just include it in the table_changes PR?

2023-03-07 20:02 UTC, homar commented
I will include it in table_changes

2023-03-27 12:36 UTC, findepi commented
> I will include it in [table_changes](https://github.com/trinodb/trino/pull/16205)

should this one be closed now?

2023-03-28 11:35 UTC, closed without merging