Provide extra extension point for adding column in BaseJdbcClient
trinodb/trino pull request #15800
Opened 2023-01-20 17:26 UTC by SemionPar

## Description
BaseJdbcClient.beginInsertTable adds additional column when in FTE mode. This will allow connectors to override the way this column is added  (e.g. a part of remote table name) without overriding whole beginInsertTable method.

## Additional context and related issues

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-01-20 17:52 UTC, wendigo requested changes

2023-01-20 17:52 UTC, wendigo commented on plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
> +    protected void addColumn(ConnectorSession session, Connection connection, RemoteTableName table, ColumnMetadata column)
Undo move method position in the class

2023-01-20 17:57 UTC, wendigo approved these changes

2023-01-24 01:59 UTC, ebyhr approved these changes
The commit body is too long. Could you follow this commit message guideline https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#format-git-commit-messages?

2023-01-24 22:57 UTC, merged