olugin manager rewrite as plugin installers
trinodb/trino pull request #16082
Opened 2023-02-13 07:20 UTC by skrzypo987

## Description
This PR rewrites the plugin installation process into smaller installers using mechanism from https://github.com/trinodb/trino/pull/16056. That way the logic of installing plugins i s moved into classes, where they are actually installed, and only guice bindings link the two together.

## Additional context and related issues

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-02-13 13:02 UTC, kokosing commented on core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
> -        newSetBinder(binder, PluginInstaller.class);
extract variable for multi set binder.

2023-02-13 13:02 UTC, kokosing commented on core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
>                  ImmutableSet.of());
I don't think it works now as you need to pass all installers here.

2023-02-14 08:36 UTC, skrzypo987 commented on core/trino-main/src/main/java/io/trino/exchange/ExchangeManagerRegistry.java
> +            log.info("Registering exchange manager %s", exchangeManagerFactory.getName());
A simple example
```
presto-master       | 2023-02-14T13:45:46.700+0545      INFO    main    io.trino.server.PluginManager   -- Loading plugin /var/presto/plugin/exchange-filesystem --
presto-master       | 2023-02-14T13:45:46.720+0545      INFO    main    io.trino.server.PluginManager   Installing io.trino.plugin.exchange.filesystem.FileSystemExchangePlugin
presto-master       | 2023-02-14T13:45:46.727+0545      INFO    main    io.trino.server.PluginManager   Registering exchange manager filesystem
presto-master       | 2023-02-14T13:45:46.728+0545      INFO    main    io.trino.server.PluginManager   -- Finished loading plugin /var/presto/plugin/exchange-filesystem --

presto-master       | 2023-02-14T14:16:08.464+0545      INFO    main    io.trino.server.PluginManager   -- Loading plugin /var/presto/plugin/exchange-filesystem --
presto-master       | 2023-02-14T14:16:08.489+0545      INFO    main    io.trino.server.PluginManager   Installing io.trino.plugin.exchange.filesystem.FileSystemExchangePlugin
presto-master       | 2023-02-14T14:16:08.499+0545      INFO    main    io.trino.exchange.ExchangeManagerRegistry       Registering exchange manager filesystem
presto-master       | 2023-02-14T14:16:08.500+0545      INFO    main    io.trino.server.PluginManager   -- Finished loading plugin /var/presto/plugin/exchange-filesystem --

```

2023-02-14 08:37 UTC, skrzypo987 commented
@kokosing AC

2023-02-14 12:45 UTC, kokosing approved these changes

2023-02-14 12:47 UTC, kokosing commented
Please rebase

2023-02-14 13:26 UTC, ksobolew approved these changes
Just wanted to say that I like it

2023-02-14 16:50 UTC, martint requested changes
Classes such as ResourceGroupManager, TypeRegistry, GlobalFunctionCatalog, etc., should not have to be aware of plugin infrastructure -- it should be the opposite.

2023-02-14 20:27 UTC, kokosing commented
In such case as I understand you, that means that we should have dedicated plugin installers per such entity. For example `ResourceGroupManagerPluginInstaller` that would just glue the plugin infrastructure with `ResourceGroupManager`.

2023-02-18 21:10 UTC, closed without merging