Rewrite `year` function to `date_trunc` for improving performance
trinodb/trino pull request #16106
Opened 2023-02-14 07:09 UTC by ebyhr

## Description

Rewrite `year` function to `date_trunc` for improving performance. 
Continuation of #15306

## Additional context and related issues

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# General
* Improve performance of queries that contain predicates involving `year` function. ({issue}`14078`)
```

2023-02-14 07:45 UTC, martint commented
Why would this rewrite improve performance?

2023-02-14 07:48 UTC, ebyhr commented
@martint We have `UnwrapDateTruncInComparison`. Updated the PR description.

2023-02-14 16:40 UTC, martint requested changes
That's a roundabout way of improving this specific type of expression. The optimization should go the other way -- an expression like `year(date_time) = t` is inherently cheaper than `date_trunc('year', date_time) = ...`, since the `date_trunc` function is more generic and expensive to compute. In general, optimizations should stand on their own (i.e., not depend on other rules to be successful). They should produce a better plan regardless of whether another optimization kicks in later.

2023-02-15 08:57 UTC, ebyhr commented
@martint Changed the implementation not to depend on `UnwrapDateTruncInComparison`.

2023-02-20 11:49 UTC, findinpath approved these changes

2023-02-20 11:52 UTC, findinpath commented on core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapYearInComparison.java
> +                    LocalDateTime dateTime = LocalDateTime.MAX.withYear(year).with(lastDayOfYear());
Is `.with(lastDayOfYear())` still necessary in the context of using `LocalDateTime.MAX` ?

2023-03-16 14:17 UTC, findepi approved these changes

2023-03-16 14:17 UTC, findepi commented on core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapYearInComparison.java
> +                    LocalDateTime dateTime = LocalDateTime.MAX.withYear(year).with(lastDayOfYear());
Personally i find `LocalDateTime.MAX` harder to reason about.
I first need to _assume_ the max value has `.999999999` second fraction (which is obvious if you know LocalDateTime internal representation) and then I need to reason how this behaves for our timestamp with precision > 9.

What about writing this more explicitly

```
long nextYearStartEpochSecond = LocalDateTime.of(year + 1, 1, 1, 0, 0).toEpochSecond(ZoneOffset.UTC);
long nextYearStartEpochMicros = multiplyExact(nextYearStartEpochSecond, MICROSECONDS_PER_SECOND);
if (timestampType.isShort()) {
    // TODO might be off by one
    return nextYearStartEpochMicros - scaleFactor(timestampType.getPrecision(), 6);
}
int picosOfMicro = toIntExact(PICOSECONDS_PER_MICROSECOND - scaleFactor(timestampType.getPrecision(), 12));
return new LongTimestamp(nextYearStartEpochMicros - 1, picosOfMicro);
```

(i hope i didn't screw the math, but not sure, hence the TODO comment; please remove the TODO)

2023-03-16 14:17 UTC, findepi commented on core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapYearInComparison.java
> +    public void testLeapYear()
thanks!

2023-03-16 14:17 UTC, findepi commented on core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapYearInComparison.java
> +        testUnwrap(getQueryRunner().getDefaultSession(), inputType, inputPredicate, expectedPredicate);
can inline, since we always use the default session.

2023-03-16 14:17 UTC, findepi commented on core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapYearInComparison.java
> +            assertPlan(sql,
break line

2023-03-16 14:17 UTC, findepi commented on plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ConstraintExtractor.java
> +    private static Optional<Domain> unwrapYearInComparison(FunctionName functionName, Type argumentType, Constant constant)
`unwrapYearInTimestampTzComparison`

2023-03-16 14:17 UTC, findepi commented on plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ConstraintExtractor.java
> +        // Normalized to UTC because for comparisons the zone is irrelevant
remove (copy&paste error)

2023-03-16 14:17 UTC, findepi commented on plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ConstraintExtractor.java
> +        checkArgument(constant.getValue() != null && argumentType.equals(TIMESTAMP_TZ_MICROS), "Unexpected constant: %s", constant);
we check two arguments but report only one in the message

```
checkArgument(constant.getValue() != null, "Unexpected constant: %s", constant);
checkArgument(type.equals(TIMESTAMP_TZ_MICROS), "Unexpected type: %s", type);
```

2023-03-16 14:17 UTC, findepi commented on plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestConstraintExtractor.java
> +        FunctionCall truncateToYear = new FunctionCall(
`extractYear`

2023-03-16 14:17 UTC, findepi commented on plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestConstraintExtractor.java
> +        Expression someMidnightExpression = LITERAL_ENCODER.toExpression(
`yearExpression`?

2023-03-16 14:17 UTC, findepi commented on plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestConstraintExtractor.java
> +        LongTimestampWithTimeZone startOfNextDateUtc = timestampTzFromEpochMillis(someDate.plusYears(1).withDayOfYear(1).atStartOfDay().toEpochSecond(UTC) * MILLISECONDS_PER_SECOND);
startOfDate -> startOfYear

2023-03-16 14:18 UTC, findepi commented on plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ConstraintExtractor.java
> +        checkArgument(constant.getValue() != null && argumentType.equals(TIMESTAMP_TZ_MICROS), "Unexpected constant: %s", constant);
( https://github.com/trinodb/trino/pull/16594 )

2023-03-17 05:34 UTC, merged