Document DEFLATE codec in Hive docs
trinodb/trino pull request #16336
Opened 2023-03-01 23:39 UTC by colebow

## Description

Docs for #16270 

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

2023-03-02 00:07 UTC, dain approved these changes

2023-03-02 22:25 UTC, mosabua approved these changes

2023-03-02 22:25 UTC, mosabua commented
Can you merge this @dain ?

2023-03-03 02:33 UTC, ebyhr approved these changes

2023-03-03 02:42 UTC, ebyhr requested changes
`hive.compression-codec` refers to [HiveCompressionOption](https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveCompressionOption.java). I don't think we can specify `DEFLATE` in the config property.

2023-03-03 20:05 UTC, closed without merging