Re-cast Google Cloud Storage Tutorial as reference page
trinodb/trino pull request #17178
Opened 2023-04-21 18:03 UTC by m57lyra

## Description

Make Google Cloud Storage page a reference page that is not Hive-centric.

## Additional context and related issues

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-04-21 22:39 UTC, m57lyra commented on docs/src/main/sphinx/connector/hive-gcs-tutorial.rst
> +<https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage>`_.
As discussed, it is existing technical content. I think this needs a technical re-visit after, as I believe that Hive is no longer the only supported connector, and it is unclear where the GCS connector comes into play. The only place it is really mentioned is in the POSIX perms section. Is it where folks get the gs:// URI prefix? It's unclear.

2023-04-24 21:18 UTC, mosabua requested changes
@m57lyra just a few more notes from a bit of a closer look. At this stage I think we need to work on this together. Maybe even swallow the fact that this has to include technical corrections of the

2023-04-24 21:18 UTC, mosabua commented on docs/src/main/sphinx/connector/hive-gcs-tutorial.rst
> +* Run Trino service and Hive service as the same user.
HMS

2023-04-24 21:18 UTC, mosabua commented on docs/src/main/sphinx/connector/hive-gcs-tutorial.rst
> +* Configure Google Cloud Storage with the ``fs.gs.reported.permissions``
where?

2023-05-09 00:07 UTC, electrum approved these changes

2023-05-09 20:28 UTC, mosabua approved these changes
Looks good now.

2023-05-09 20:28 UTC, merged