Refactor Delta testInputDataSize
trinodb/trino pull request #17556
Opened 2023-05-18 13:55 UTC by findepi

2023-05-18 17:19 UTC, electrum commented
We still haven't answered the question of why we need this test. What value does it provide? Is that value worth all of this extra complexity?

This adds additional complication to the Hadoop removal project. I'd rather just remove the test.

2023-05-18 17:21 UTC, electrum commented on plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
> +        try {
```java
try (queryRunner) {

2023-05-18 17:26 UTC, electrum submitted a review, later dismissed
We don't want to combine the storage configuration across connectors, since with #17498 we need to have different configuration in tests between Hive and Delta Lake connectors. This is why I'd rather drop this test entirely.

2023-05-18 20:13 UTC, findepi commented
> What value does it provide? Is that value worth all of this extra complexity?

verifies that Delta connector doesn't read more data then it should, using Hive connector as the baseline

> We don't want to combine the storage configuration across connectors

Hive and Delta need to be able to talk to S3. Hive and Delta need to be able to talk to Azure storage. Hive and Delta need to be able to talk to GCS.  So I expect configuration to be same, unless there is a compelling reason not to be the same.

The test is easy to adapt if eg configuration properties are different, but currently they are not, so I could prepare for that.
Once they are different, it's trivial to update the test accordingly.

2023-05-19 00:53 UTC, electrum commented
The first commit looks good

2023-05-19 00:59 UTC, electrum requested changes
The properties are different in https://github.com/trinodb/trino/pull/17498. Eventually, they will be the same, but that won't happen until Hive is fully converted to the new file system interface. Having all of this infrastructure for a single insignificant test doesn't seem worthwhile.

Why is this test important? Under what type of scenario would the Delta Lake connector read more data? Could we directly test that it reads the expected amount of data? For example, by verifying that the bytes read are in known valid range.

We need to be judicious when writing tests. Our current approach of writing very high level tests for absolutely everything is expensive.

If this test didn't exist and someone proposed to add it using the current approach, would we accept it? Just because someone chose to write this test at some point in the past doesn't mean that we need to keep it forever.

2023-05-19 01:03 UTC, electrum commented
> Once they are different, it's trivial to update the test accordingly.

It may be trivial to update the code, but the development process is absolutely non-trivial, since I can't run the tests locally. They have to run in the CI with secrets. So this one test will add hours to the development process for every round trip.

2023-05-19 15:02 UTC, findepi commented
> Why is this test important? Under what type of scenario would the Delta Lake connector read more data?

In none, but we want to have test coverage for that.

> We need to be judicious when writing tests.

Agreed

Also, we need more testing coverage, especially for file systems x cloud storages.
We constantly struggle with problems around it, and experience shows we don't have enough test coverage. I think it's premature to remove tests just because there is some maintenance cost to them.


>  Our current approach of writing very high level tests for absolutely everything is expensive.

I wish we had tests for everything.

2023-05-20 03:35 UTC, electrum commented
I think we can agree that this input size test is unrelated to the type of file system. Therefore, there’s no need to test it against all cloud storage. That’s complex and wasteful.

So, if you can refactor it as single local test that doesn’t depend on external resources, then we can keep it.

2023-05-20 06:38 UTC, findepi commented
> I think we can agree that this input size test is unrelated to the type of file system.

i agree that ideally the implementation should behave the same for all file systems, and that we should be able to simplify the test.
but how do we verify that?

2023-05-24 13:27 UTC, raunaqmorarka approved these changes

2023-05-24 13:38 UTC, raunaqmorarka commented
TBH this `testInputDataSize` is too basic to satisfy the intended aim of no regressions in data read compared to hive.
It's missing nested types, doesn't have projection pruning, doesn't have predicate pruning, uses `processedInputDataSize` rather than `physicalInputDataSize` (e.g. with projection pruning it's possible that the connector read everything but returned only relevant blocks to the engine, discarding the unnecessary columns).
It would be better to have a standalone test in delta to sanity test processedInputDataSize without relying on hive as a baseline.

2023-05-24 19:25 UTC, findepi commented
> It would be better to have a standalone test in delta to sanity test processedInputDataSize without relying on hive as a baseline.

i don't think we have such baselines tests for hive either.
i think we always use some baseline (eg read with DF vs read with DF disabled, etc.)

2023-05-25 08:20 UTC, findepi commented
I will merge this so that https://github.com/trinodb/trino/pull/17498 doesn't have to remove the test coverage. We can always improve later, replacing the test with something that we agree is better.

2023-05-25 08:20 UTC, merged