Add type mapping section
trinodb/trino pull request #17573
Opened 2023-05-19 18:40 UTC by Jessie212

## Description

Added type mapping section 

## Additional context and related issues

Additional changes needed that are related to closed PR:  https://github.com/trinodb/trino/pull/14331

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-05-19 19:10 UTC, Jessie212 commented
I closed the last PR because Kafka is not getting a new type mapping section and I didn't want to muck up the commits. I think, once this PR is approved and merged, I can apply the fragments with the protobuf format entry to Kafka.

2023-06-23 21:16 UTC, mosabua requested changes
First pass of a bunch of files done. Please address comments and do similar edits on the other files that I have not reviewed yet. Ping me when done.

2023-06-23 21:16 UTC, mosabua commented on docs/src/main/sphinx/connector/avro-decoder.fragment
> +* Column added in new schema:
Can we just make these a item list of normal sentences?

2023-06-23 21:16 UTC, mosabua commented on docs/src/main/sphinx/connector/csv-decoder.fragment
> +string using UTF-8 encoding and then interprets the result as a CSV
as a link of comma-separated values.

2023-06-23 21:16 UTC, mosabua commented on docs/src/main/sphinx/connector/csv-decoder.fragment
> ++-------------------------------------+--------------------------------------------------------------------------------+
Change to list-table and add title

2023-06-23 21:16 UTC, mosabua commented on docs/src/main/sphinx/connector/csv-decoder.fragment
> +Table below lists supported Trino types, which can be used in ``type`` and
Remove this sentence

2023-06-23 21:16 UTC, mosabua commented on docs/src/main/sphinx/connector/json-decoder.fragment
> +The JSON decoder converts the bytes representing a message or key into a JSON
into Javascript Object Notation (JSON)

2023-06-23 21:16 UTC, mosabua commented on docs/src/main/sphinx/connector/json-decoder.fragment
> +according to :rfc:`4627`. Note that the message or key *MUST* convert into a
```suggestion
according to :rfc:`4627`. Note that the message or key must convert into a
```

2023-06-23 21:16 UTC, mosabua commented on docs/src/main/sphinx/connector/json-decoder.fragment
> ++-------------------------------------+--------------------------------------------------------------------------------+
Convert to list-table with title

2023-06-23 21:16 UTC, mosabua commented on docs/src/main/sphinx/connector/json-decoder.fragment
> +timezone information is present in decoded value, it will be used as Trino
```suggestion
timezone information is present in decoded value, it is used as Trino
```

2023-06-23 21:16 UTC, mosabua commented on docs/src/main/sphinx/connector/json-decoder.fragment
> +value. Otherwise result time zone will be set to ``UTC``.
```suggestion
value. Otherwise the result time zone is set to ``UTC``.
```

2023-07-07 17:10 UTC, mosabua commented
I am good with this to merge in terms of wording and such. Content all looks good as well but I have to rely on @hashhar for technical input.

2023-07-18 20:14 UTC, mosabua approved these changes
Good to go. Any final objections @hashhar or @ebyhr or should I go ahead and merge.

2023-07-24 16:21 UTC, merged