Add Trino 421 release notes
trinodb/trino pull request #18075
Opened 2023-06-28 17:48 UTC by colebow

## Description

Assemble the release notes for the upcoming Trino 421 release. Fixes #18021 

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

## Verification for each pull request

Format: maintainer, PR/issue number, ✅ / ❌ rn ✅ / ❌ docs
✅ rn - release note added and verified, or assessed to be not necessary, set to ❌ rn before completion
✅ docs - need for docs assessed and merged, or assessed to be not necessary, set to ❌ docs before completion

2023-07-05 23:07 UTC, mosabua requested changes

2023-07-05 23:07 UTC, mosabua commented on docs/src/main/sphinx/release/release-421.md
> +# Release 421 (28 Jun 2023)
5 Jul

2023-07-05 23:07 UTC, mosabua commented on docs/src/main/sphinx/release/release-421.md
> +* Fix incorrect query results when using S3 Select and a table's null format is
whats a "table's null format" ?

2023-07-05 23:07 UTC, mosabua commented on docs/src/main/sphinx/release/release-421.md
> +* Improve query performance on tables with `row` (struct) columns when only a
can we leave "struct" out?

2023-07-05 23:34 UTC, mosabua approved these changes
Looks good now. We have to fast follow on docs after the release.

2023-07-06 00:44 UTC, martint commented on docs/src/main/sphinx/release/release-421.md
> +* Fix query failure for queries involving the `concat_ws` function on arrays
Fix failure for queries ...

2023-07-06 00:44 UTC, martint commented on docs/src/main/sphinx/release/release-421.md
> +* Fix query failure when cancelling a query with a window function. ({issue}`18061`)
Fix failure when cancelling ...

2023-07-06 00:44 UTC, martint commented on docs/src/main/sphinx/release/release-421.md
> +* Fix loss of timestamp precision when coercing a
This doesn't seem to match what the PR is about. What's the observed behavior before that PR? A failure? Correctness issues? cc @Praveen2112

2023-07-06 00:44 UTC, martint commented on docs/src/main/sphinx/release/release-421.md
> +* Add support for using an alternative hostname for full SSL verification
"when SSLVerification is set to FULL"

2023-07-06 22:59 UTC, merged