Add further clarification about ANSI to docs
trinodb/trino pull request #18363
Opened 2023-07-20 17:22 UTC by colebow

## Description

People don't really know what it means to abide by the ANSI spec, so let's call out that we're compliant, that we haven't fully implemented, and make it clearer why that matters.

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

2023-07-20 20:16 UTC, mosabua requested changes
I think we might have to clarify that ANSI SQL comes in editions over the years, and that we also strive to follow other well adopted conventions when ANSI SQL has gaps. That specifically also applies to functions (think geospatial and PostGIS, and many others). Also maybe this has to be more than one paragraph.

2023-07-20 22:51 UTC, ebyhr commented on docs/src/main/sphinx/language.md
> +language implemented in Trino adheres to the ANSI SQL specification, but not
> all SQL language implemented in Trino adheres to the ANSI SQL specification

This is false. For instance, `COMMENT` statement doesn't exist in ANSI.

2024-01-11 22:35 UTC, mosabua commented
@colebow I assume you will continue on this ;-)

2024-02-02 18:50 UTC, mosabua commented
👋 @colebow ... are you taking this up again some time ?

2024-02-21 22:23 UTC, colebow commented
I'll push an update to this sometime next week and we can get it merged yeah

2024-02-21 22:38 UTC, mosabua commented
Sure .. just let me know when I should look ;-)

2024-04-05 17:31 UTC, closed without merging