Add support for `GROUP BY ALL` aggregation
trinodb/trino pull request #18390
Opened 2023-07-24 21:22 UTC by ebyhr

## Description

Labeled `syntax-needs-review` since this isn't part of SQL standard. 
https://docs.snowflake.com/en/sql-reference/constructs/group-by#label-group-by-all-columns

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# General
* Add support for `GROUP BY ALL` aggregation. ({issue}`issuenumber`)
```

2023-07-31 20:15 UTC, martint requested changes
This conflicts with the standard syntax for GROUP BY:

```
 GROUP BY [ <set quantifier> ] <grouping element list>
```

where `<set quantifier>` can be `ALL` or `DISTINCT` and defaults to `ALL` if omitted. The quantifier affects the semantics for queries involving grouping sets. Overloading the meaning to indicate how the keys are selected instead of how the rows in the result are de-duplicated is confusing and error prone.

Before we could consider such syntax, we'd need to define the precise semantics and how it interacts and relates to the broader `GROUP BY` feature.

2023-07-31 20:31 UTC, martint commented
In particular, here are some inconsistencies:

1)

```
SELECT k, count(*) 
FROM (VALUES 1,2,3) t(k) 
GROUP BY ALL
```

produces a result, but

```
SELECT k, count(*) 
FROM (VALUES 1,2,3) t(k) 
GROUP BY
```

fails with `'k' must be an aggregate expression or appear in GROUP BY clause`, even though `ALL` is implied if missing, per the SQL standard.

2) 

```
SELECT k, count(*) 
FROM (VALUES 1,2,3) t(k) 
GROUP BY DISTINCT
```

fails with `groupingElements must not be empty when type is DISTINCT`. Presumably, it should also work. But, what would the meaning of such a query?

3)

Without precise semantics, it's hard to tell what's the behavior of these queries after this change:


```
SELECt k, count(*) 
FROM (VALUES 1,2,3) t(k) 
GROUP BY ALL k
```

```
SELECT k, v, count(*) 
FROM (VALUES (1,1),(2,2),(3,3)) t(k, v) 
GROUP BY ALL
```

```
SELECT k, v, count(*) 
FROM (VALUES (1,1),(2,2),(3,3)) t(k, v) 
GROUP BY ALL k
```

```
SELECT k, v, count(*) 
FROM (VALUES (1,1),(2,2),(3,3)) t(k, v) 
GROUP BY ALL k, v
```

```
SELECT count(*) 
FROM (VALUES 1,2,3) t(k) 
GROUP BY ALL ()
```

2023-08-01 01:13 UTC, ebyhr commented
1. Since GROUP BY ALL without grouping element list isn't defined in standard, we don't need to default to ALL in a such case and the failure is expected for me. 
2. I don't think it should work. GROUP BY DISTINCT without grouping element list was disallowed even before this change. Also, the standard also disallows it in my understanding. The unclear semantics you mentioned implies the current behavior of throwing an exception is better. 
3. Only 2nd example should be affected in this PR because it's the only example which uses GROUP BY ALL without grouping element list. Other examples should keep the original behavior. This rule is clear to me.

2023-08-18 00:32 UTC, martint commented
To be clear, the ALL and DISTINCT qualifiers control whether grouping sets that have the same combination of keys are deduped.

Therefore, the only way this syntax makes sense is if we give meaning to omitting the grouping set specification. Specifically, to be equivalent to having a single grouping set composed of all the expressions in the group by clause that don’t contain aggregations.

In that case, the qualifier is orthogonal to such feature. Allowing one but not the other looks arbitrary and introduces cognitive load for a user who has to understand that they are somehow connected even though intuitively they should not be.

Another aspect that complicates issues conceptually is that the GROUP BY operation occurs before the SELECT clause is computed, so it’s a chicken-and-egg problem to determine which columns are grouping keys and which ones are derived. Also, the GROUP BY clause operates on input columns (those coming from the FROM clause) not on those from the SELECT clause. The implication arrow goes the other way: an expression in the SELECT clause is valid if it’s functionally dependent on the input columns used for computing the grouping sets.

2024-03-01 01:51 UTC, ebyhr commented
@martint Thank you for your detailed explanation. Can you suggest alternative syntax? Or we don't want to add this feature?

2025-03-22 03:00 UTC, martint commented
The idea is interesting, but the proposed syntax has a number of problems. We need to consider the syntax in the totality 
of the SQL standard and how it interacts with other features. I'm going to attempt to summarize the issues based on a number of separate discussion, and suggest an alternative below. I'll refer to the original proposal of adding support for `GROUP BY ALL`. Using `GROUP BY *` has similar problems, plus the additional issue the `*` in SQL means "the expanded list of all columns".

Problems:
1. Standard SQL already reserves the keyword `ALL` and `DISTINCT` after `GROUP BY` as a quantifier. 
2. Overloading `ALL` to mean "all columns that are not aggregated" would be confusing, as slight variations in syntax
  would lead to vastly different meanings in what the query does. For example, given:
   
    ```sql
    SELECT a, b, c, count(*)
    FROM t
    ```

   * `GROUP BY ALL` means "group by a, b and c"
   * `GROUP BY ALL (a, b, c)` means "group by a, b and c"
   * `GROUP BY ALL ()` means "place everything in a single group"

   This could be rationalized by saying that when the grouping set specification is missing, there's an implicit grouping 
   set that represents all non-aggregate expressions in the `SELECT` clause. However, it introduces conceptual issues when 
   considering the `DISTINCT` qualifier:
 
   * `GROUP BY DISTINCT` -- is that equivalent to `GROUP BY DISTINCT (a, b, c)` just like `GROUP BY ALL` is equivalent to `GROUP BY ALL (a, b, c)`? If not, why not? 
   * Syntactically, it generalizes to `GROUP BY (ALL | DISTINCT) groupingSet?`, so why is one combination special?
   
3. The syntax doesn't compose. It cannot be combine with the quantifiers, and it can't be combined with other grouping sets.

   a. How does it interact with the ALL and DISTINCT quantifiers? The following forms are confusing:
      
      * `GROUP BY DISTINCT ALL` 
      * `GROUP BY ALL ALL` 
                                                                 
   b. It cannot be combined with other grouping sets. For example, this could be a valid and useful query, but it's not possible to express it with the proposed syntax:
    
      ```sql
     SELECT a, b, c, d, count(*)
     FROM t
     GROUP BY ALL, ROLLUP(a, b)
     ```
                                                                                                                     
The argument that we should just add it in that form because that's just how other engines have implemented it is not sufficient. Comparisons with other engines without understanding how they resolve the conflicts with standard SQL features are therefore incomplete and not useful.

DuckDB, BigQuery and Snowflake skirt around the issue because they don't support the ALL and DISTINCT quantifiers. For example, this query is not supported by those engines, but it's valid in Trino:

```sql
SELECT a, count(*)
FROM t
GROUP BY ALL a;
```
                                 
# Alternative proposal

My alternative proposal is to introduce a new grouping set type, `IMPLICIT`, that would represent the implicit grouping of all non-aggregated columns. For example:

```sql
SELECT a, b, c, count(*)
FROM t
GROUP BY IMPLICIT;
```

The advantages of this approach are:

* It composes with GROUP BY (ALL | DISTINCT) …
 
    ```sql 
    SELECT a, b, c, count(*)
    FROM t
    GROUP BY ALL IMPLICIT
    ```

    ```sql 
    SELECT a, b, c, count(*)
    FROM t
    GROUP BY DISTINCT IMPLICIT
    ```

* It composes with other grouping sets, such as `ROLLUP` and `CUBE`. The following query groups by the grouping sets `()`, `(a)`, `(a, b)`, and the implicitly derived `(a, b, c, d)` set.
  
    ```sql
    SELECT a, b, c, d, count(*)
    FROM t
    GROUP BY IMPLICIT, ROLLUP(a, b)
    ```

2025-03-24 01:41 UTC, ebyhr commented
Updated the syntax to `GROUP BY IMPLICIT`.

2025-03-26 00:19 UTC, martint commented
I just had another idea -- instead of `IMPLICIT`, we could use the term `AUTO`. It's shorter, easy to type, and conveys the intention clearly.

2025-03-26 10:42 UTC, martint commented on core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
> +    : setQuantifier? AUTO? (groupingElement (',' groupingElement)*)?
`AUTO` should be a `groupingElement`, just like `CUBE`, `ROLLUP`, etc.

2025-03-26 23:39 UTC, ebyhr commented on core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
> +    : setQuantifier? AUTO? (groupingElement (',' groupingElement)*)?
Changed to `groupingElement`.

2025-03-27 01:42 UTC, martint commented on core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
> +                            case AUTO -> 0;
This should be 1. AUTO implies a single grouping set made up of all the columns that don't have aggregate operations.

2025-03-27 01:42 UTC, martint commented on core/trino-parser/src/main/java/io/trino/sql/tree/GroupingSets.java
> +        AUTO
Create a separate class to represent AUTO. It should extend `GroupingElement` and be parallel to SimpleGroupBy and GroupingSets

2025-03-27 02:07 UTC, ebyhr commented on core/trino-parser/src/main/java/io/trino/sql/tree/GroupingSets.java
> +        AUTO
Added AutoGroupBy class extending GroupingElement.

2025-04-15 01:14 UTC, ebyhr commented
@martint Gentle reminder.

2025-04-16 22:45 UTC, martint commented on core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
> +                        Optional.empty()));
assertStatement is deprecated. Use `assertThat(statement(...))`

2025-04-16 22:45 UTC, martint commented on core/trino-main/src/test/java/io/trino/sql/query/TestGroupBy.java
> +    void testGroupByAuto()
Add tests involving AUTO and other grouping sets (e.g., ROLLUP)

2025-04-16 23:47 UTC, ebyhr commented
Addressed comments.

2025-04-17 00:56 UTC, martint commented on core/trino-main/src/test/java/io/trino/sql/query/TestGroupBy.java
> +        // ROLLUP
Add at least one test that produces mixed groups from AUTO vs the other grouping sets. For instance:

```
SELECT a, b, c, sum(d)
FROM ...
GROUP BY AUTO, ROLLUP(a)
```

It should result in the following grouping sets: `(), (a), (a, b, c)`

2025-04-22 23:12 UTC, martint commented on core/trino-main/src/test/java/io/trino/sql/query/TestGroupBy.java
> +        // ROLLUP
Right, when there are multiple grouping set specifications, their grouping sets are cross joined. I forgot about that. So, in this case, it would be `((a, b, c)) x ((), (a))`, which results in `((a, b, c), (a, b, c))`. That's unfortunate, as it makes `AUTO` not that useful when combined with other grouping sets.

2025-04-23 00:03 UTC, ebyhr commented on core/trino-main/src/test/java/io/trino/sql/query/TestGroupBy.java
> +        // ROLLUP
Added the tests anyway. Let me know if we want to disallow `AUTO` with other grouping sets.

2025-04-23 04:08 UTC, martint commented on core/trino-main/src/test/java/io/trino/sql/query/TestGroupBy.java
> +        // ROLLUP
Let's leave it as is for consistency with other grouping sets. AUTO is just a short hand for a grouping set formed by all the non-aggregate columns.

2025-04-23 04:08 UTC, martint approved these changes
Don't forget to squash the fixup commits.

2025-04-23 04:20 UTC, merged