Convert functions docs to markdown
trinodb/trino pull request #18391
Opened 2023-07-24 21:41 UTC by mosabua

## Description

## Additional context and related issues

Follow up to 

https://github.com/trinodb/trino/pull/17732
https://github.com/trinodb/trino/pull/17742
https://github.com/trinodb/trino/pull/17759

In parallel to https://github.com/trinodb/trino/pull/18375

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

2023-07-25 02:34 UTC, ebyhr requested changes
Some pages look a little broken. e.g. 
<img width="390" alt="Screenshot 2023-07-25 at 11 32 53" src="https://github.com/trinodb/trino/assets/6237050/15a55aa9-79f5-4106-88bb-c48bdc7c7299">

2023-07-25 16:39 UTC, mosabua commented
> Some pages look a little broken. For instance, the leading `\` should be removed. <img alt="Screenshot 2023-07-25 at 11 32 53" width="390" src="https://user-images.githubusercontent.com/6237050/255771365-15a55aa9-79f5-4106-88bb-c48bdc7c7299.png">

yeah .. I found that and some others in my final check round .. will go over it all once more and push

2023-07-25 21:59 UTC, ebyhr commented
> Verified that output HTML is identical, has changes like wrapping with now visual change or are a visual improvment.

Could you share the diff file so reviewers can confirm that?

2023-07-25 22:46 UTC, mosabua commented
> > Verified that output HTML is identical, has changes like wrapping with now visual change or are a visual improvement.
> 
> Could you share the diff file so reviewers can confirm that?

I use a the "Compare folder" extension in Visual Code .. there are LOTS of differences in terms of wrapping, additional unused css classes and such. I am not sure it is worth your time doing that. Where should I share the diff files? Just here in the PR?

2023-07-25 22:54 UTC, ebyhr commented
You can attach the archived file to this PR.

2023-07-25 23:26 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +For example, you can use `\\` to match for `\`.
This was wrong in the original document.

2023-07-25 23:35 UTC, mosabua commented
> You can attach the archived file to this PR.

```


$ diff -qrc ~/tmp/html/functions/ docs/target/html/functions

diff /Users/manfred/tmp/html/functions/comparison.html and docs/target/html/functions/comparison.html differ
diff /Users/manfred/tmp/html/functions/datetime.html and docs/target/html/functions/datetime.html differ
diff /Users/manfred/tmp/html/functions/json.html and docs/target/html/functions/json.html differ
diff /Users/manfred/tmp/html/functions/logical.html and docs/target/html/functions/logical.html differ
diff /Users/manfred/tmp/html/functions/math.html and docs/target/html/functions/math.html differ
diff /Users/manfred/tmp/html/functions/ml.html and docs/target/html/functions/ml.html differ
diff /Users/manfred/tmp/html/functions/regexp.html and docs/target/html/functions/regexp.html differ
diff /Users/manfred/tmp/html/functions/string.html and docs/target/html/functions/string.html differ
diff /Users/manfred/tmp/html/functions/table.html and docs/target/html/functions/table.html differ
diff /Users/manfred/tmp/html/functions/teradata.html and docs/target/html/functions/teradata.html differ


$ diff /Users/manfred/tmp/html/functions/comparison.html docs/target/html/functions/comparison.html
681,682c681
< <p>Note that the value, min, and max parameters to <code class="docutils literal notranslate"><span class="pre">BETWEEN</span></code> and <code class="docutils literal notranslate"><span class="pre">NOT</span>
< <span class="pre">BETWEEN</span></code> must be the same type.  For example, Trino will produce an
---
> <p>Note that the value, min, and max parameters to <code class="docutils literal notranslate"><span class="pre">BETWEEN</span></code> and <code class="docutils literal notranslate"><span class="pre">NOT</span> <span class="pre">BETWEEN</span></code> must be the same type.  For example, Trino will produce an
717,724d715
< <colgroup>
< <col style="width: 13%"/>
< <col style="width: 13%"/>
< <col style="width: 15%"/>
< <col style="width: 15%"/>
< <col style="width: 19%"/>
< <col style="width: 26%"/>
< </colgroup>
880c871
< For example, you can use <code class="docutils literal notranslate"><span class="pre">\\</span></code> to match for ‘’'’.</p>
---
> For example, you can use <code class="docutils literal notranslate"><span class="pre">\\</span></code> to match for <code class="docutils literal notranslate"><span class="pre">\</span></code>.</p>


$ diff /Users/manfred/tmp/html/functions/datetime.html  docs/target/html/functions/datetime.html

623,627d622
< <colgroup>
< <col style="width: 9%"/>
< <col style="width: 60%"/>
< <col style="width: 31%"/>
< </colgroup>
914,917d908
< <colgroup>
< <col style="width: 29%"/>
< <col style="width: 71%"/>
< </colgroup>
971,974d961
< <colgroup>
< <col style="width: 49%"/>
< <col style="width: 51%"/>
< </colgroup>
1052,1055d1038
< <colgroup>
< <col style="width: 35%"/>
< <col style="width: 65%"/>
< </colgroup>
1124,1127d1106
< <colgroup>
< <col style="width: 7%"/>
< <col style="width: 93%"/>
< </colgroup>
1141c1120
< <td><p>Month, numeric (<code class="docutils literal notranslate"><span class="pre">1</span></code> .. <code class="docutils literal notranslate"><span class="pre">12</span></code>) <a class="footnote-reference brackets" href="#z" id="id1" role="doc-noteref"><span class="fn-bracket">[</span>4<span class="fn-bracket">]</span></a></p></td>
---
> <td><p>Month, numeric (<code class="docutils literal notranslate"><span class="pre">1</span></code> .. <code class="docutils literal notranslate"><span class="pre">12</span></code>), this specifier does not support <code class="docutils literal notranslate"><span class="pre">0</span></code> as a month.</p></td>
1147c1126
< <td><p>Day of the month, numeric (<code class="docutils literal notranslate"><span class="pre">01</span></code> .. <code class="docutils literal notranslate"><span class="pre">31</span></code>) <a class="footnote-reference brackets" href="#z" id="id2" role="doc-noteref"><span class="fn-bracket">[</span>4<span class="fn-bracket">]</span></a></p></td>
---
> <td><p>Day of the month, numeric (<code class="docutils literal notranslate"><span class="pre">01</span></code> .. <code class="docutils literal notranslate"><span class="pre">31</span></code>), this specifier does not support <code class="docutils literal notranslate"><span class="pre">0</span></code> as a month or day.</p></td>
1150c1129
< <td><p>Day of the month, numeric (<code class="docutils literal notranslate"><span class="pre">1</span></code> .. <code class="docutils literal notranslate"><span class="pre">31</span></code>) <a class="footnote-reference brackets" href="#z" id="id3" role="doc-noteref"><span class="fn-bracket">[</span>4<span class="fn-bracket">]</span></a></p></td>
---
> <td><p>Day of the month, numeric (<code class="docutils literal notranslate"><span class="pre">1</span></code> .. <code class="docutils literal notranslate"><span class="pre">31</span></code>), this specifier does not support <code class="docutils literal notranslate"><span class="pre">0</span></code> as a day.</p></td>
1153c1132
< <td><p>Fraction of second (6 digits for printing: <code class="docutils literal notranslate"><span class="pre">000000</span></code> .. <code class="docutils literal notranslate"><span class="pre">999000</span></code>; 1 - 9 digits for parsing: <code class="docutils literal notranslate"><span class="pre">0</span></code> .. <code class="docutils literal notranslate"><span class="pre">999999999</span></code>) <a class="footnote-reference brackets" href="#f" id="id4" role="doc-noteref"><span class="fn-bracket">[</span>1<span class="fn-bracket">]</span></a></p></td>
---
> <td><p>Fraction of second (6 digits for printing: <code class="docutils literal notranslate"><span class="pre">000000</span></code> .. <code class="docutils literal notranslate"><span class="pre">999000</span></code>; 1 - 9 digits for parsing: <code class="docutils literal notranslate"><span class="pre">0</span></code> .. <code class="docutils literal notranslate"><span class="pre">999999999</span></code>), timestamp is truncated to milliseconds.</p></td>
1180c1159
< <td><p>Month, numeric (<code class="docutils literal notranslate"><span class="pre">01</span></code> .. <code class="docutils literal notranslate"><span class="pre">12</span></code>) <a class="footnote-reference brackets" href="#z" id="id5" role="doc-noteref"><span class="fn-bracket">[</span>4<span class="fn-bracket">]</span></a></p></td>
---
> <td><p>Month, numeric (<code class="docutils literal notranslate"><span class="pre">01</span></code> .. <code class="docutils literal notranslate"><span class="pre">12</span></code>), this specifier does not support <code class="docutils literal notranslate"><span class="pre">0</span></code> as a month.</p></td>
1213c1192
< <td><p>Day of the week (<code class="docutils literal notranslate"><span class="pre">0</span></code> .. <code class="docutils literal notranslate"><span class="pre">6</span></code>), where Sunday is the first day of the week <a class="footnote-reference brackets" href="#w" id="id6" role="doc-noteref"><span class="fn-bracket">[</span>3<span class="fn-bracket">]</span></a></p></td>
---
> <td><p>Day of the week (<code class="docutils literal notranslate"><span class="pre">0</span></code> .. <code class="docutils literal notranslate"><span class="pre">6</span></code>), where Sunday is the first day of the week, this specifier is not supported,consider using <a class="reference internal" href="#day_of_week" title="day_of_week"><code class="xref py py-func docutils literal notranslate"><span class="pre">day_of_week()</span></code></a> (it uses <code class="docutils literal notranslate"><span class="pre">1-7</span></code> instead of <code class="docutils literal notranslate"><span class="pre">0-6</span></code>).</p></td>
1225c1204
< <td><p>Year, numeric (two digits) <a class="footnote-reference brackets" href="#y" id="id7" role="doc-noteref"><span class="fn-bracket">[</sp [...]

2023-07-25 23:45 UTC, ebyhr commented
"MySQL date functions" is different from the original table. 

Before 
<img width="771" alt="Screenshot 2023-07-26 at 8 45 15" src="https://github.com/trinodb/trino/assets/6237050/ec65898e-a7ef-45c4-95d6-5c5c688f77aa">

After
<img width="783" alt="Screenshot 2023-07-26 at 8 45 30" src="https://github.com/trinodb/trino/assets/6237050/02c82060-06cc-4584-ae1b-828ef5a7d0a0">

2023-07-25 23:47 UTC, ebyhr commented
I see you modified PR description.

2023-07-26 15:39 UTC, mosabua commented
> > Note that the footnotes in the MySQl date functions section were inlined into the related table cells
> 
> Could you share the reason why you inlined?

The markdown render put the footnotes at the bottom of the page and that made things worse. I tried to move it back up but found that even in the original form the footnotes at the bottom of the table as just very much out of context. Since there was not much text anyway moving it into the table made everything better for the reader.

2023-07-26 23:08 UTC, electrum approved these changes

2023-07-27 02:26 UTC, merged