#15424 Documentation for postgres general connector config.
trinodb/trino pull request #18574
Opened 2023-08-07 21:59 UTC by Ankan0011

## Description
Added in general postgreSQL connector configuration in the documentation for support for reading PostgreSQL system tables, e.g., pg_catalog relations. The functionality is disabled by default.

## Additional context and related issues
Fixes for #15424 
Relates to https://trinodb.slack.com/archives/CGB0QHWSW/p1671165424335919

## Release notes

(X) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-08-07 23:47 UTC, ebyhr commented on docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
> +  * - ``postgresql.include-system-tables``
This file is `jdbc-common-configurations.fragment` which is used from several connectors. Please move to `postgresql.rst`.

2023-08-07 23:47 UTC, ebyhr commented on docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
> +    - Supports access to postgres system catalog tables(pg_catalog schemas).
"Supports reading PostgreSQL system tables, e.g., `pg_catalog` relations."

2023-08-07 23:47 UTC, ebyhr commented on docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
> +    - ``false``
Please update the commit title as "Document postgresql.include-system-tables config property"
https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#format-git-commit-messages

2023-08-08 21:11 UTC, ebyhr commented on docs/src/main/sphinx/connector/postgresql.rst
> +The PostgreSQL connector supports reading PostgreSQL system tables, e.g., ``pg_catalog`` relations.
Please rebase on master to resolve conflicts. The file was converted to markdown.

2023-08-11 18:02 UTC, mosabua commented on docs/src/main/sphinx/connector/postgresql.md
> +It also supports reading PostgreSQL system tables, e.g., `pg_catalog` relations.
```suggestion
It also supports reading PostgreSQL system tables, such as `pg_catalog`.
```

2023-08-11 18:05 UTC, mosabua requested changes
This content should be moved up into the Configuration section .. maybe under a separate subtitle "Access to system tables"

2023-08-11 18:05 UTC, mosabua commented on docs/src/main/sphinx/connector/postgresql.md
> +The functionality is disabled by default but this can be enabled using the ``postgresql.include-system-tables`` configuration property.
```suggestion
The functionality is disabled by default, and can be enabled using the ``postgresql.include-system-tables`` configuration property.
```

2023-08-11 18:06 UTC, mosabua commented
Also .. please rebase and send a signed CLA.

2023-08-11 19:18 UTC, Ankan0011 commented
> Also .. please rebase and send a signed CLA.

I have send the CLA multiple times. I have changed my email and sent again.

2023-08-11 21:54 UTC, mosabua commented
> > Also .. please rebase and send a signed CLA.
> 
> I have send the CLA multiple times. I have changed my email and sent again.

Looks like it was not yet added to https://github.com/trinodb/cla/blob/master/contributors
Did you receive the email @martint ?

2023-08-11 21:57 UTC, mosabua requested changes

2023-08-11 21:57 UTC, mosabua commented on docs/src/main/sphinx/connector/postgresql.md
> +The PostgreSQL connector supports reading PostgreSQL system tables, such as `pg_catalog`.
Please wrap at 80

2023-08-11 21:57 UTC, mosabua commented on docs/src/main/sphinx/connector/postgresql.md
> +More details about the PostgreSQL system tables, see the [PostgreSQL system
Empty line after code snippet

2023-08-11 21:57 UTC, mosabua commented on docs/src/main/sphinx/connector/postgresql.md
> +SHOW SCHEMAS FROM pg_catalog;
sorry .. I am confused .. in what schemas are the system tables exposed when this is enabled? 

Also .. should the example not be

show tables from example.notsurewhatschema 

or 

describe example.notsurewhatschema.pg_catalog ?

2023-08-14 18:44 UTC, Ankan0011 commented
@cla-bot

2023-08-20 03:09 UTC, mosabua commented on docs/src/main/sphinx/connector/postgresql.md
> +pg_catalog database using either of the following:
```suggestion
`pg_catalog` schema using either of the following:
```

2023-08-20 03:10 UTC, mosabua commented on docs/src/main/sphinx/connector/postgresql.md
> +catalog documentation](https://www.postgresql.org/docs/current/catalogs.html).
According to that URL there is no pg_tables table...

2023-08-21 16:46 UTC, mosabua approved these changes
Fixed the last issues and the commit message. Merging.

2023-08-21 16:46 UTC, merged