Can't find documentation for 'IN' operator #4791
trinodb/trino pull request #18610
Opened 2023-08-09 21:19 UTC by Ankan0011

## Description
Add IN operator to the comparison section. This is a improvement for the documentation with examples.

## Additional context and related issues
Fixes https://github.com/trinodb/trino/issues/4791

## Release notes

(X) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

2023-08-09 23:46 UTC, ebyhr commented
This is duplicate of #12810

2023-08-10 00:26 UTC, ebyhr commented on docs/src/main/sphinx/functions/comparison.md
> +SELECT * FROM region WHERE name IN ('America', 'Europe');
The actual `name` value is uppercase. Same for others. 
```suggestion
SELECT * FROM region WHERE name IN ('AMERICA', 'EUROPE');
```

2023-08-11 21:50 UTC, mosabua requested changes

2023-08-11 21:50 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +The `IN` operator can be use to fetch multiple records according to mutiple
Remove this sentence or move the content up

2023-08-11 21:50 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +It is shorthand of mutiple `OR` operator. The same query can be modified to
Maybe better to say
```
The values in the clause are used for multiple comparisons that are combined as a logical or. The preceding query is equivalent to the following query:
```

2023-08-11 21:50 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +You can also negate the result by adding `NOT`, and get all other regions except the values in list:
```suggestion
You can negate the comparisons by adding `NOT`, and get all other regions except the values in list:
```

2023-08-11 21:50 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +You can also use the subquery with the IN operator that returns records from the single column.
When using a subquery to determine the values to use in the comparison, the subquery must return a single column and one or more rows.

2023-08-11 21:50 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +    WHERE name IN ('AMERICA', 'EUROPE')
modify to use name startswith A

2023-08-14 22:17 UTC, mosabua commented
Please squash commits

2023-08-15 22:29 UTC, Ankan0011 commented
Messed up the PR. Creating a new PR for the same.

2023-08-15 22:33 UTC, closed without merging