Document IN operator #18610
trinodb/trino pull request #18687
Opened 2023-08-15 22:36 UTC by Ankan0011

## Description
Add IN operator to the comparison section. This is a improvement for the documentation with examples.

## Additional context and related issues
Fixes https://github.com/trinodb/trino/issues/4791

## Release notes

(X) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

2023-08-19 22:07 UTC, Ankan0011 commented
Sorry I messed up the previous branch during rebasing. I am new to the whole rebase with master process and squash. Nevermind, now I have adapted this PR with all the suggested changes in previous observation. Feel free to suggest changes for this issue.

2023-09-21 18:22 UTC, Ankan0011 commented
@ebyhr Can you please have a look at this PR as well. Thanks.

2023-09-21 19:09 UTC, mosabua requested changes

2023-09-21 19:09 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +The `IN` operator can be used to compare values with the following patterns.
```suggestion
The `IN` operator can be used in a `WHERE` clause to compare column values with a list of values. The list of values can be supplied by a subquery or directly as static values in an array:
```

2023-09-21 19:09 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +It can fetch records according to mutiple values specified in WHERE clause. A
Remove this and the next line.

2023-09-21 19:09 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +
Add this:

Use the optional `NOT` keyword to negate the condition.

2023-09-21 19:09 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +```
The following example shows a simple usage with a static array:

2023-09-21 19:09 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +```
add sql hint in all snippets

```
```sql
```

2023-09-21 19:09 UTC, mosabua commented on docs/src/main/sphinx/functions/comparison.md
> +SELECT name FROM nation
```suggestion
SELECT name 
FROM nation 
```

2023-10-02 18:54 UTC, mosabua commented
Added a missing empty line and updated commit message.

2023-10-02 18:54 UTC, mosabua approved these changes
Looks good now. Thank you @Ankan0011

2023-10-02 18:54 UTC, merged