in substring function, change start param 0 to the same as 1
trinodb/trino pull request #18728
Opened 2023-08-18 10:39 UTC by borderlayout

## Description

I run some SQLs in hive and trino, then I find the substring function is difference between hive and trino when the start parameter is 0.
In hive: the start parameter 0 is the same as 1
hive> select substr('20191125',0,4);
OK
_c0
2019
Time taken: 0.134 seconds, Fetched: 1 row(s)
In spark, it is the same as hive.
spark-sql (default)>  select substr('20191125',0,4);
substr(20191125, 0, 4)
2019

But in trino, when the start is 0, the substring return empty string.
before pr:
trino:tpcds_bin_partitioned_orc_2> select substr('20191125',0,4);
_col0

(1 row)

So I change the substring function.
after pr:
trino:tpcds_bin_partitioned_orc_2> select substr('20191125',0,4);
_col0
2019
(1 row)

trino:tpcds_bin_partitioned_orc_2> select substr('20191125',1,4);
_col0
2019
(1 row)

Additional context and related issues
Release notes
(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

The previous PR was closed due to my mistake. Related link: https://github.com/trinodb/trino/pull/15454 ,

2023-08-18 11:35 UTC, hashhar requested changes
Trino follows the ANSI SQL specification and it treats indexes as starting from 1.

The behaviour of `start` when `0` seems to differ across databases. However Postgres at-least seems to also return entire string when first argument is `0`.

2023-08-18 14:11 UTC, martint commented
Please see the related discussion in https://github.com/trinodb/trino/pull/15454

2024-01-11 21:47 UTC, mosabua commented
From looking at the comments I think we should close this PR .. correct @martint ?

2024-01-12 16:54 UTC, martint commented
In its current form, yes. We should update the `substring(x from y)` function to match the SQL spec, as I described in the linked comment above, but we should keep `substr` behavior as today. That will require splitting the implementation of the functions into two.

2024-01-12 17:11 UTC, mosabua commented
Closing this PR based on the the discussion. Thank you for your work @borderlayout .. if you want to help with the effort to split the two functions please send a new PR.

2024-01-12 17:11 UTC, closed without merging