Improve memory usage accounting of parquet writer
trinodb/trino pull request #18756
Opened 2023-08-21 10:19 UTC by raunaqmorarka

## Description
Improve memory usage accounting of parquet writer

## Additional context and related issues
Fixes https://github.com/trinodb/trino/issues/18557

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Hive, Delta, Iceberg
* Improve memory usage accounting of parquet writer. ({issue}`issuenumber`)
```

2023-08-21 10:55 UTC, sopel39 approved these changes

2023-08-22 04:31 UTC, wendigo requested changes

2023-08-22 04:31 UTC, wendigo commented on lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/DictionaryFallbackValuesWriter.java
> +import javax.annotation.Nullable;
Use jakarta.annotation.instead

2023-08-22 04:51 UTC, raunaqmorarka commented
[Insert parquet dictionary memory.pdf](https://github.com/trinodb/trino/files/12404810/Insert.parquet.dictionary.memory.pdf)

<img width="494" alt="Screenshot 2023-08-22 at 10 12 39 AM" src="https://github.com/trinodb/trino/assets/4344846/0dd4ba3f-a2dd-4f1a-ab40-1d49cad202d2">

2023-08-22 06:19 UTC, merged