Add missing serde/inputFormat combination for Hive
trinodb/trino pull request #18989
Opened 2023-09-11 07:47 UTC by homar

## Description
This combination was working before so we should keep supporting it.

## Additional context and related issues

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-09-11 07:50 UTC, findepi approved these changes

2023-09-11 07:51 UTC, findepi commented
> This combination was working before so we should keep supporting it.

add information which release or which code change affected it


> ( ) Release notes are required, with the following suggested text:
> 
> ```
> # Section
> * Fix some things. ({issue}`issuenumber`)
> ```

please feel in

2023-09-11 14:29 UTC, electrum requested changes
This works for reads, but what happens if you attempt to write to such a table? I'm worried that this could silently create corrupted data that is not readable. I'd like to understand writing behavior for such a table with

* Current Trino
* Older version of Trino (before the change that prompted this fix)
* Spark

2023-09-11 15:26 UTC, homar commented
> This works for reads, but what happens if you attempt to write to such a table? I'm worried that this could silently create corrupted data that is not readable. I'd like to understand writing behavior for such a table with
> 
> * Current Trino
> * Older version of Trino (before the change that prompted this fix)
> * Hive
> * Spark

Current trino/previous trino can't write to it as it is a non managed hive table. 
Spark as you can see from tests can read and write.
Hive seems not to able to write to it.

2023-09-11 20:00 UTC, findepi commented
> Current trino/previous trino can't write to it as it is a non managed hive table.

there is a toggle to enable writes to non-managed tables.

2023-09-12 08:03 UTC, electrum commented
When you write from Spark, are the files written in Parquet format?

2023-09-12 08:05 UTC, electrum commented
The test seems to only read with Spark, not write. Can you also read and write with Hive?

2023-09-12 16:17 UTC, homar commented
@electrum sorry, my bad.
I modified the test.
Now it writes and reads with spark and it validates that the created file is parquet.
Reading and writing with hive doesn't really work, I also added code to validate that.
Writing with trino doesn't work with new version and it didn't work with the old. It fails on this line https://github.com/trinodb/trino/blob/029e1a07ae6823b9ce61eac82ebd7bb65daea966/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java#L3582

2023-09-12 18:11 UTC, electrum approved these changes
Thanks for confirming the behavior. This change looks good. Can you also add a test to verify that writing fails with Trino? I'm assuming something similar to the Hive insert would work.

2023-09-14 18:17 UTC, homar commented
@electrum can you merge this ? I don't have the button

2023-09-18 07:50 UTC, merged

2023-09-18 07:51 UTC, findepi commented
> Release notes are required, with the following suggested text:
> 
> ```
> # Section
> * Add back support for ParquetHiveSerDe with TextInputFormat. ({issue}`issuenumber`)
> ```

or maybe "[Hive] Fix reading from certain Parquet tables incorrectly created by Spark"

cc @colebow