Rework SQL support section
trinodb/trino pull request #19000
Opened 2023-09-11 22:57 UTC by Jessie212

## Description

- Removed duplicate content and rearranged SQL section.

## Additional context and related issues

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-09-11 23:37 UTC, mosabua reviewed
The "Updating data" and "Data management" sections are duplicate content we should consolidate under "Data management".

2023-09-11 23:38 UTC, mosabua commented on docs/src/main/sphinx/connector/delta-lake.md
> +- {doc}`/sql/alter-table` , see also {ref}`delta-lake-alter-table`
there are two section .. alter table execute and alter table rename .. maybe consolidate as one with subesctions

2023-09-11 23:39 UTC, mosabua commented on docs/src/main/sphinx/connector/delta-lake.md
> +#### Basic usage examples
This seems to be all about table and schema management .. move it there .. the title is misleading anyway .. nothing basic about creating schemas and tables..

2023-09-11 23:42 UTC, mosabua requested changes
A bit more rejigging needed

2023-09-12 17:32 UTC, mosabua requested changes

2023-09-12 17:32 UTC, mosabua commented on docs/src/main/sphinx/connector/delta-lake.md
> +##### ALTER TABLE RENAME TO
This should stay same level as ALTER TABLE EXECUTE

2023-09-12 17:32 UTC, mosabua commented on docs/src/main/sphinx/connector/delta-lake.md
> +##### ALTER TABLE RENAME TO
And be linked to in the above list

2023-09-12 18:39 UTC, Jessie212 commented
@mosabua Does everything in this section makes sense in this order?

2023-09-12 19:15 UTC, mosabua commented
> @mosabua Does everything in this section makes sense in this order?

Kind of .. proecedures is a bit odd and could be later .. but lets leave it for now

2023-09-13 18:41 UTC, mosabua approved these changes
Looks great now.

2023-09-13 18:42 UTC, merged