Use only table rules from FBAC for catalog & schema visibility
trinodb/trino pull request #19175
Opened 2023-09-27 09:39 UTC by huberty89

When there is no defined rules for:
- schema
- catalog session property
- functions only catalog & table rules are used to filter out catalogs and table rules only to filter out schemas

## Description

## Additional context and related issues

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-09-27 12:17 UTC, ksobolew commented
So I guess the culprit is that `tables:` rule:

```json
        {
            "privileges": []
        }
```

But it has an empty list of privileges, so it should not count towards catalog visibility.

Perhaps if you wrote regression test for this it would be easier to see what's happening...

2023-09-27 12:23 UTC, huberty89 commented
> So I guess the culprit is that `tables:` rule:
> 
> ```json
>         {
>             "privileges": []
>         }
> ```
> 
> But it has an empty list of privileges, so it should not count towards catalog visibility.
> 
> Perhaps if you wrote regression test for this it would be easier to see what's happening...

Deny rules are not used for filtering catalogs and schemas:
https://github.com/huberty89/trino/blob/a9d451fb2dfe83fac5289d727fe9cb16ea5f94f1/lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/CatalogFunctionAccessControlRule.java#L77
https://github.com/huberty89/trino/blob/a9d451fb2dfe83fac5289d727fe9cb16ea5f94f1/lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/CatalogFunctionAccessControlRule.java#L91

2023-09-28 09:17 UTC, huberty89 commented
Need to add tests - no tests fails after my change so this is suspicious

2023-09-29 12:21 UTC, kokosing commented
I am under impression that the fact we `ALLOW_ALL` if there is no specified access is a mistake. If we now have "overlapping" rules where one allows and one denies access to a given resource under catalog, the we will always see a catalog. 

Either we need to introduce backward incompatible change and `DENY_ALL` by default to everything or we need to ask users to specify rules for entities to not to leak any access to things they don't want to leak.

2023-09-29 12:50 UTC, findepi commented
> Fixes:
> #18565
> #18370

write this as

- fixes #18565
- fixes  #18370

so that the issues get closed upon PR merge

2023-10-17 21:13 UTC, dain commented
I don't understand this PR.  The design of file based access control is to explicitly work this way, so this isn't a bug but a design feature. I read over the issues, and the issues are making assumptions that just don't hold for this code.  We could change the docs, but given there are only two issues and I haven't seen many questions on Slack about this, I'm assuming this is a limited problem for these folks.

This is to big of a subject to discuss in text on an github issue.  We can discuss on slack or zoom if you like.

2023-10-17 21:14 UTC, dain requested changes
This code is working as designed, and we should discuss this in detail

2023-11-10 18:07 UTC, brendanstennett commented
+1 for this change.  The docs specifically mention in the [visibility section](https://trino.io/docs/current/security/file-system-access-control.html#visibility) of FBAC that the intended behaviour is to only show tables "that have at least 1 permission on the item" but as @huberty89 points out, that is not actually the case.  Instead, all catalogs/schemas/tables are shown to a user, regardless of the permissions they have on them.

Based on the docs, I would expect that any tables that has a permission in `rules.json` to show up when running `show tables from ...` and any tables that do not have a permission listed do not appear.  This is not the case and all tables show up (even if they are not queryable). 

[1] https://trino.io/docs/current/security/file-system-access-control.html#visibility

2023-11-20 15:57 UTC, ksobolew commented
@brendanstennett does the workaround I mentioned in https://github.com/trinodb/trino/issues/18370#issuecomment-1816710891 work for you?

2023-11-21 15:07 UTC, ksobolew commented
> However, catalogs that do not have at least 1 table permission on them still remain visible and a similar workaround with `"catalogs": []` does not work as it just makes every table inaccessible. This is contrary to the docs as well.

In that case I guess a workaround would be to have a "dummy" rule for each catalog you want to be accessible. Haven't checked that, though. Inconvenient - yes, as is expected of a workaround, not a fix...

2023-11-21 15:09 UTC, brendanstennett commented
> In that case I guess a workaround would be to have a "dummy" rule for each catalog you want to be accessible. Haven't checked that, though. Inconvenient - yes, as is expected of a workaround, not a fix...

Yes, and this is a reasonable workaround in this case I think.

2024-01-11 07:47 UTC, ksobolew commented
We determined that this is actually working as intended. Closing.

2024-01-11 07:47 UTC, closed without merging