Fix BQ query function with projected columns
trinodb/trino pull request #19574
Opened 2023-10-30 12:47 UTC by wendigo

## Description

## Additional context and related issues

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-10-30 14:51 UTC, wendigo commented
BQ module timed out but the new test has passed:
```
2023-10-30T13:40:53.1506173Z 2023-10-30T07:40:53.148-0600	INFO	pool-3-thread-2	io.trino.testng.services.ProgressLoggingListener	[TEST SUCCESS] io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest.testNativeQuerySimpleWithProjectedColumns; (took: 1.8 seconds)

```

2023-10-30 14:51 UTC, wendigo commented
I'm going to restart BQ either way

2023-10-30 23:10 UTC, ebyhr approved these changes

2023-10-30 23:10 UTC, ebyhr commented on plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java
> +        String columns = columnNames.stream().map(column -> format("`%s`", column)).collect(joining(","));
nit: We can use `BigQueryUtil::quote` method. Also, no need to build `columns` when `columnNames` is empty. 
```java
String projection = columnNames.isEmpty() ? "*" : columnNames.stream().map(BigQueryUtil::quote).collect(joining(","));
```

2023-10-30 23:10 UTC, ebyhr commented on plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java
> +        String projection = columnNames.isEmpty() ? "*" : columns;
Is the first condition `columnNames.isEmpty()` covered by any tests?

2023-10-30 23:10 UTC, ebyhr commented on plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
> +                "SELECT z FROM (SELECT x, y, z FROM TABLE(bigquery.system.query(query => 'select 1 x, 2 y, 3 z')))",
nit: Uppercase `select` in query parameter.

2023-10-31 10:19 UTC, ebyhr requested changes
This change causes query failure when the `query` argument contains implicit column names. e.g.
```sql
SELECT * FROM TABLE(bigquery.system.query(query => 'SELECT 1'));
```

2023-10-31 10:35 UTC, wendigo commented
@ebyhr yeah, I've noticed

2023-11-08 17:22 UTC, closed without merging