Fix blob creation in trino file system tests
trinodb/trino pull request #19678
Opened 2023-11-08 20:52 UTC by elonazoulay

## Description

## Additional context and related issues

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-11-08 20:52 UTC, elonazoulay commented
Note: if the root location is not empty then `testDirectoryExists` was double appending the path when calling `createBlob` - lmk if this fix is ok.

2023-11-08 21:24 UTC, elonazoulay commented
I can also add the `RemoteStorageHelper` back, I will need the project id used for ci tests - either way `createBlob` needs to be changed (comment above).

2023-11-08 21:26 UTC, elonazoulay commented on lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
> +                createBlob(closer, "%s/%s".formatted(directoryName, fileName));
Should line 877 be changed as well? i.e. for the equivalent `createBlob` for hierarchical filesystems.

2023-11-08 21:30 UTC, elonazoulay commented on lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java
> +        if (storage.get(bucket) == null) {
Should I just check for the existence of the bucket and not try to create it?

2023-11-09 03:45 UTC, electrum commented
/test-with-secrets sha=08595ccc84d539eadba1fe012114f25181b79e6c

2023-11-09 06:07 UTC, electrum requested changes
We should go with the original approach of creating the bucket in the test, since we want to test that the code works with the root of the bucket. This is what we do for S3 and Azure.

2023-11-16 18:44 UTC, closed without merging