Add a reminder to notify maintainers about SPI changes
trinodb/trino pull request #19724
Opened 2023-11-13 20:51 UTC by kokosing

Add a reminder to notify maintainers about SPI changes

That way maintainers will have a chance to get to know early about SPI
changes, they will be able to respond to them and potentially notify all
other affected SPI consumers they know about.

2023-11-13 22:35 UTC, electrum requested changes
If we want this, we could add a bot that looks for revapi changes and posts them somewhere.

2023-11-13 22:37 UTC, electrum commented
First commit looks good

2023-11-13 22:39 UTC, electrum commented
We could have something automatically tag the PR anytime something changes the SPI POM.

2023-11-13 23:17 UTC, dain commented on core/trino-spi/pom.xml
> +                                <!-- Remember to notify to all Trino maintainers before merging backward incompatible SPI changes -->
This is not a policy we currently have.  Please bring this up with the maintainers group if you would like to add this policy.

2023-11-14 15:41 UTC, kokosing commented
I am sorry, I have should mark this a draft. I posted this to facilitate the discussion. I had no intention to merge it fast.

2023-11-14 15:42 UTC, kokosing commented
> We could have something automatically tag the PR anytime something changes the SPI POM.

Do you mean by posting a comment on github?

2023-11-14 19:11 UTC, electrum commented
Sorry, I meant labels, not tags. For example, we have something that automatically tags PRs as `hive`.

2023-11-14 19:12 UTC, dain commented
> I am sorry, I have should mark this a draft. I posted this to facilitate the discussion. I had no intention to merge it fast.

No problem.  Github is not a good place to have a discussion.  I suggest you post on slack group.

> > We could have something automatically tag the PR anytime something changes the SPI POM.
> 
> Do you mean by posting a comment on github?

I think he means add a label to the issue.

2023-11-14 20:36 UTC, kokosing commented
I was under impression that adding tags does not trigger notifications.

2024-01-02 15:59 UTC, closed without merging