Add document for array_join(x, delimiter)
trinodb/trino pull request #19875
Opened 2023-11-23 14:19 UTC by zivali

## Description
Add additional document for function `array_join(x, delimiter)`

## Additional context and related issues
Fix #17521

## Release notes

( x ) This is not user-visible or is docs only, and no release notes are required.

2023-11-23 18:02 UTC, mosabua requested changes

2023-11-23 18:02 UTC, mosabua commented on docs/src/main/sphinx/functions/array.md
> +Null elements will be omitted in the result.
```suggestion
Null elements are omitted in the result.
```

2023-11-26 23:50 UTC, mosabua approved these changes
Looks good now. I am squashing the commits. In the future please do that yourself @zivali .

2023-11-26 23:50 UTC, merged

2023-12-01 15:38 UTC, zivali commented
Will do. Thank you!