Mention SELinux in README Docker section
trinodb/trino pull request #19938
Opened 2023-11-28 20:58 UTC by dekimir

## Description

Update README to suggest turning SELinux off, to get rid of errors like this:
```
Configuration error:
config directory doesn't contain a conf.py file (/docs/src/main/sphinx)
```

## Additional context and related issues

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2023-11-28 21:14 UTC, mosabua requested changes

2023-11-28 21:14 UTC, mosabua commented on README.md
> +  * Turn SELinux off on the build host, allowing containers to mount parts of the Trino source tree
```suggestion
  * Turn SELinux or other systems disabling write access to the local checkout off, to allow containers to mount parts of the Trino source tree
```

2023-11-28 21:14 UTC, mosabua commented
Will also need a signed CLA @dekimir

2023-11-28 21:23 UTC, dekimir commented
@mosabua I discovered that I can add a `docker` flag to exempt the build container from security policies -- please see [here](https://github.com/dekimir/trino/commit/d2aed30a24bd6340d7de63c4a6a39dfe3f78f784).  It might be preferable to commit that instead of this PR (though it'll need more testing; I only tested it on my Fedora 38 box).

Also, I emailed the signed CLA to the email address mentioned by the bot above.

2023-11-28 22:32 UTC, mosabua commented
That could docker script mod could be another PR .. but given that there are other reasons for disabled write access this PR is still valid

2023-11-28 22:33 UTC, mosabua commented on README.md
> +  * Turn SELinux or other systems disabling write access to the local checkout off, to allow containers to mount parts of the Trino source tree
can you wrap at 80 char column please

2023-11-28 22:38 UTC, dekimir commented on README.md
> +  * Turn SELinux or other systems disabling write access to the local checkout off, to allow containers to mount parts of the Trino source tree
Done in dce1fa8.

2023-11-28 22:43 UTC, dekimir commented
> That could docker script mod could be another PR

#19940

2023-12-07 00:54 UTC, martint commented
@cla-bot check

2023-12-07 00:57 UTC, mosabua approved these changes
Looks good now. Thank you.

2023-12-07 00:57 UTC, merged