Add note about `http-server.https.automatic-shared-secret parameter`
trinodb/trino pull request #19989
Opened 2023-12-01 11:21 UTC by radek-starburst

## Description
Add note about `http-server.https.automatic-shared-secret` parameter

## Release notes

() This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

2023-12-01 23:10 UTC, mosabua commented on docs/src/main/sphinx/security/internal-communication.md
> +Also, note that you need to configure `http-server.https.automatic-shared-secret`
Why not add this to point 4? Or 2 .. or both? .. does this really belong in this note?

2023-12-05 07:44 UTC, electrum requested changes
I'm confused about the purpose of this change. This property is set automatically in `InternalCommunicationModule` as appropriate. It should not be configured manually.

Also, the note is in the section that lists the old properties to be removed. Why would that section list a property that needs to be added?

2023-12-05 08:30 UTC, radek-starburst commented
> This property is set automatically in InternalCommunicationModule as appropriate. It should not be configured manually.

I followed documentation https://trino.io/docs/current/security/internal-communication.html step by step to enable secure internal communication. When I was running Trino it was failing because of parameter `http-server.https.automatic-shared-secret` was not set. This is why I decided to add note about this parameter.

2023-12-21 14:37 UTC, closed without merging

2023-12-21 17:54 UTC, mosabua commented
What was the outcome of you testing @radek-starburst ?

2024-01-02 07:02 UTC, radek-starburst commented
It was my mistake.

> I assume everything is working without this change...

yes