Add an example for listagg with filter
trinodb/trino pull request #20053
Opened 2023-12-07 18:40 UTC by danielyahn

## Description
- Add an example for `listagg` aggregation function with `filter` keyword
   -  Example provided by a test in #19871, which addressed #19869
- Lowercase the function name `LISTAGG` to `listagg` to match the naming convention followed in the other sections of the documentation.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

2023-12-15 17:25 UTC, mosabua commented on docs/src/main/sphinx/functions/aggregate.md
> +SELECT listagg(value, ',') WITHIN GROUP (ORDER BY id) FILTER (WHERE id % 2 = 0) csv_value
Lets break this into multiple lines

2023-12-15 17:26 UTC, mosabua commented on docs/src/main/sphinx/functions/aggregate.md
> +     VALUES (1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')
break down into multiple lines

2023-12-15 17:29 UTC, mosabua requested changes
If we add this example we should also explain what it does..

2023-12-15 17:29 UTC, mosabua commented on docs/src/main/sphinx/functions/aggregate.md
> +results in:
We should explain what is happening in the query - the filter causes only the elements to get included that pass the where condition .. so where the id is an even number due to the modulo operator and the remainder being 0 ..

2023-12-16 14:22 UTC, danielyahn commented
@mosabua thank you for the feedback. pushed a commit to address these comments.

2023-12-18 17:51 UTC, mosabua commented on docs/src/main/sphinx/functions/aggregate.md
> +```
```suggestion
```sql
```

2023-12-18 17:52 UTC, mosabua reviewed
Please address final requested changes and squash all commits into one commit. Then this is good to go

2023-12-18 17:52 UTC, mosabua commented on docs/src/main/sphinx/functions/aggregate.md
> +```
empty line before code snippet

2023-12-18 17:52 UTC, mosabua commented on docs/src/main/sphinx/functions/aggregate.md
> +This aggregation function can be also used with `FILTER` keyword to specify which rows are processed
```suggestion
This aggregation function can be also used with the `FILTER` keyword to specify which rows are processed 
```

2023-12-18 17:53 UTC, mosabua commented on docs/src/main/sphinx/functions/aggregate.md
> +The example aggregates rows that have even-numbered `id` and concatenates `value` to a comma-separated string:
```suggestion
The example aggregates rows that have even-numbered `id`, and concatenates `value` to a comma-separated string:
```

2023-12-19 13:53 UTC, danielyahn commented
@mosabua I think it should be good to go!

2023-12-19 16:40 UTC, mosabua approved these changes
Fixed wrapping, removed whitespace and updated commit message. Looks good now.

2023-12-19 16:40 UTC, merged