Support table comment for Snowflake connector
trinodb/trino pull request #21305
Opened 2024-03-28 10:49 UTC by chenjian2664

Allow create table with comment.
Also allow to set table comment for Snowflake tables.

## Description

## Additional context and related issues

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Snowflake
* Support create table with comment
* Support set table comment
```

2024-03-29 05:30 UTC, ebyhr requested changes

2024-03-29 05:30 UTC, ebyhr commented on plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java
> +        return Optional.ofNullable(emptyToNull(resultSet.getString("REMARKS")));
Please leave comment why using `emptyToNull`.

2024-03-29 05:30 UTC, ebyhr commented on plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java
> +        }
Snowflake accepts a comment in CREATE TABLE statement as far as I know. No need to call COMMENT ON TABLE.

2024-03-31 06:18 UTC, ebyhr commented
/test-with-secrets sha=be5b0035e67d1d06242f3ac33cc3feb4cf53828b

2024-03-31 07:47 UTC, ebyhr approved these changes

2024-03-31 07:47 UTC, merged

2024-04-02 15:12 UTC, mosabua commented
Amazing @chenjian2664 .. you are on a roll!