Fail Driver on exception from processNewSources
trinodb/trino pull request #21397
Opened 2024-04-04 12:37 UTC by losipiuk

Exceptions thrown from processNewSources were not handled correctly. We just logged an error and marked the PrioritizedSplitRunner as finished. The for which the PSR were executing remained RUNNING and query hang indefinitely.

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# General
* Fix rare case when queries could hang.
```

2024-04-04 14:06 UTC, findepi approved these changes

2024-04-04 14:07 UTC, findepi commented
CI
- https://github.com/trinodb/trino/issues/20326
- and something else ([pt (default, suite-iceberg, )](https://github.com/trinodb/trino/actions/runs/8554759250/job/23441149172?pr=21397#logs))

will retry

2024-04-04 18:48 UTC, martint requested changes

2024-04-04 18:48 UTC, martint commented on core/trino-main/src/main/java/io/trino/operator/Driver.java
> +            checkLockHeld("Lock must be held to call processNewSources");
Move this outside the try

2024-04-05 13:08 UTC, losipiuk commented on core/trino-main/src/main/java/io/trino/operator/Driver.java
> +        }
The meaning of that was just we should never reach throw new `AssertionError` as `failure` should be unchecked. I copied this pattern from `tryWithLock` - but it is not necessary. dropping.

2024-04-05 13:50 UTC, losipiuk commented
Thanks for review. 
The change to be effective required also changes in `TimeSharingTaskExecutor`. Updated

2024-04-05 14:02 UTC, findepi approved these changes

2024-04-05 14:02 UTC, findepi commented on core/trino-main/src/main/java/io/trino/execution/executor/timesharing/TimeSharingTaskExecutor.java
> +                                log.debug(t, "Error processing %s: %s: %s", split.getInfo(), trinoException.getErrorCode().getName(), trinoException.getMessage());
in `Decrease logging verbocity`

verbocity -> verbosity

maybe add more color to commit title (like "Decrease logging verbosity for split processing failures")

noun missing in "Getting exception in ??? is a non-rare faililure mode."

> Also excpetion will not be lost as it is propagated to split runner and
eventually will surfase as task failure and also possibly query failure.

Isn't that best effort?

2024-04-05 15:07 UTC, losipiuk commented on core/trino-main/src/main/java/io/trino/operator/Driver.java
> +        try {
The body of commit message was here by incident. Copied from other commit.

2024-04-05 15:08 UTC, losipiuk commented on core/trino-main/src/main/java/io/trino/execution/executor/timesharing/TimeSharingTaskExecutor.java
> +                        split.markFailed(t);
Fixed commit message - not sure about the comment - as I am not sure it really is best effort.

2024-04-05 17:12 UTC, losipiuk commented
CI failure timeouts in `TestMergeOperator`. Cannot reproduce (with high concurrency and repeat count). Does not seem related.

2024-04-08 09:57 UTC, losipiuk commented
@martint PTAL

2024-04-09 07:51 UTC, losipiuk commented
Addressed comments. @martint let me know if I should improve something in followup.+

2024-04-09 07:51 UTC, merged