Remove deprecated method getTableHandle from spi
trinodb/trino pull request #21532
Opened 2024-04-12 08:51 UTC by chenjian2664

## Description

## Additional context and related issues

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

2024-04-12 10:04 UTC, ebyhr requested changes
Connectors that don't support versioned query should deny the operations. Try:
```sql
SELECT * FROM tpch.tiny.region FOR VERSION AS OF 1;
```

2024-05-08 03:43 UTC, ebyhr commented
Please confirm CI failure.

2024-05-08 10:55 UTC, chenjian2664 commented on core/trino-main/src/main/java/io/trino/connector/system/SystemTablesMetadata.java
> +        if (startVersion.isPresent() || endVersion.isPresent()) {
There are tests fail with the the check, such as: `testTrySelectTableVersion`, `testCreateOrReplaceTableSnapshots`, `testReadingFromSpecificSnapshot` in Iceberg.

Add behind is compatible with preview logic, but I am not strongly about it.

2024-05-08 11:05 UTC, chenjian2664 commented on plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
> +    public void testSelectVersionOfNonExistentTable()
How to distinguish the connector support version tables or not, shall we add a testing behavior?

2024-05-09 06:47 UTC, chenjian2664 commented on core/trino-main/src/main/java/io/trino/connector/system/SystemTablesMetadata.java
> +        if (startVersion.isPresent() || endVersion.isPresent()) {
@ebyhr Move this line in front of the calling,  there are all the test failures in Iceberg and Deltalake

2024-05-10 06:26 UTC, chenjian2664 commented on plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
> +    public void testSelectVersionOfNonExistentTable()
Add a testing behavior

2024-05-10 06:42 UTC, chenjian2664 commented on core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
>          throw new TrinoException(NOT_SUPPORTED, "This connector does not support versioned tables");
updated

2024-05-10 06:43 UTC, chenjian2664 commented
https://github.com/trinodb/trino/actions/runs/9028245239/job/24808401292?pr=21532 cc @wendigo

2024-05-10 07:19 UTC, chenjian2664 commented
@ebyhr PTAL

2024-05-20 03:42 UTC, ebyhr commented on testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
> +        if (!hasBehavior(SUPPORTS_VERSIONED_TABLE)) {
We could change the assertion to `hasMessageMatching` instead. 

Introducing `SUPPORTS_VERSIONED_TABLE` requires more work. For instance, javadoc in testTrySelectTableVersion needs update.

2024-05-21 06:34 UTC, ebyhr approved these changes

2024-05-21 06:34 UTC, merged