Remove unused files from Kinesis
trinodb/trino pull request #21769
Opened 2024-04-30 13:34 UTC by ebyhr

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

2024-04-30 14:02 UTC, wendigo approved these changes

2024-04-30 14:19 UTC, wendigo commented
Seems like they are used:
```
 TestKinesisTableDescriptionSupplier.testRelatedObjects:89 » Trino Table description location does not exist or is not a directory
Error:    TestKinesisTableDescriptionSupplier.testTableDefinition:70 » Trino Table description location does not exist or is not a directory
```

2024-04-30 14:19 UTC, wendigo requested changes
Used.

2024-04-30 23:40 UTC, ebyhr commented on plugin/trino-kinesis/src/test/resources/etc/catalog/kinesis.properties
> -
Redundant empty lines cause check style failure.

2024-04-30 23:41 UTC, ebyhr commented
@wendigo Moved the files to resources directory instead. Please take another look.

2024-05-01 04:44 UTC, wendigo approved these changes

2024-05-01 04:44 UTC, merged