Fix use of various deprecated APIs
trinodb/trino pull request #21838
Opened 2024-05-07 14:13 UTC by kabunchi

## Description

## Additional context and related issues

## Release notes

(*) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2024-05-07 17:08 UTC, wendigo requested changes

2024-05-08 05:30 UTC, kabunchi commented
@wendigo Fixed the comments and allowed myself to delete "default" values in other uses of this builder...

2024-05-08 05:31 UTC, wendigo commented
@kabunchi great, thanks!

2024-05-08 05:31 UTC, wendigo approved these changes

2024-05-08 11:54 UTC, merged