Remove deprecated method finishMerge from spi
trinodb/trino pull request #22344
Opened 2024-06-10 07:16 UTC by chenjian2664

## Description

## Additional context and related issues

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

2024-06-11 01:32 UTC, ebyhr requested changes
The method gets deprecated at version 450. We should remove it 451 or later. 
Let me do "requested changes" to mark that this PR isn't ready for merge. You don't need to change anything though.

2024-07-16 18:15 UTC, mosabua commented
We are moving towards 453 now. Should we merge @ebyhr ?

2024-07-16 21:27 UTC, ebyhr approved these changes

2024-07-16 21:27 UTC, merged

2024-07-16 21:55 UTC, mosabua commented
Awesome .. thanks @ebyhr and @chenjian2664 !