Add documentation for Iceberg incremental MV refresh
trinodb/trino pull request #22549
Opened 2024-07-01 11:13 UTC by marton-bod

## Description
Adding documentation for: https://github.com/trinodb/trino/pull/20959

## Additional context and related issues

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2024-07-01 11:14 UTC, marton-bod commented
cc @mosabua @sopel39

2024-07-01 17:08 UTC, mosabua requested changes
A bunch of grammar and style suggestions - also please wrap at 80 char width in the table and the paragraph.

2024-07-01 17:08 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +    subset of the source table(s) needs to be scanned. One caveat is that while incremental refresh may scan less data,
```suggestion
    subset of the source tables needs to be scanned. While incremental refresh may scan less data, 
```

2024-07-01 17:08 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +    it may result in more data files created since it uses the append operation to insert the 'new' records.
```suggestion
    it may result in the creation of more data files, since it uses the append operation to insert the new records.
```

2024-07-01 17:08 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +definition and the snapshot history of the source table(s). For full refresh, the operation deletes the data
```suggestion
definition and the snapshot history of the source tables. For a full refresh, the operation deletes the data 
```

2024-07-01 17:08 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +existing table. For incremental refresh, the existing data is not deleted from the storage table and only the 'delta'
```suggestion
existing table. For incremental refresh, the existing data is not deleted from the storage table and only the delta
```

2024-07-01 17:08 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +existing table. For incremental refresh, the existing data is not deleted from the storage table and only the 'delta'
Or maybe "only the changed records" .. instead of the technical "delta" term

2024-07-01 17:08 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +records are processed from the source table(s) and appended into the storage table (if needed).
```suggestion
records are processed from the source tables and appended into the storage table as needed.
```

2024-07-01 17:08 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +In both cases, data is replaced/appended atomically, so users can continue to query the materialized view while
```suggestion
In both cases, data is replaced or appended atomically, so users can continue to query the materialized view while
```

2024-07-02 13:58 UTC, marton-bod commented
Thanks @mosabua - I agree with your suggestions and have applied them.

2024-07-02 15:38 UTC, mosabua approved these changes
Looks good now. I have fixed the wrapping. I will squash and merge. In the future please just use one commit for simple changes like this.

2024-07-02 15:40 UTC, merged