Fix infinite optimization loop on PreAggregateCaseAggregations
trinodb/trino pull request #22666
Opened 2024-07-14 03:35 UTC by jinyangli34

## Description
In some case, preAggregateCaseAggregations may keep the original case when expression. (like [this condition](https://github.com/trinodb/trino/blob/1c07e6cd5ee87cbe71a21a99e048378cfc04dad6/core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PreAggregateCaseAggregations.java#L301))

The optimized `Aggregation1 -> project1 -> Aggregation2 -> project2` may trigger another optimization on Aggregation2. eventually cause stackoverflow.

Fixing this bug by adding a check to make sure not producing same mappings. 
Added unit test with example query that can trigger the bug.

## Additional context and related issues

## Release notes

(X) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2024-07-19 12:13 UTC, lukasz-stec approved these changes
lgtm

2024-07-19 12:13 UTC, lukasz-stec commented on core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PreAggregateCaseAggregations.java
> +            cumulativeAggregationDefaultValue = caseExpression.defaultValue();
Is this needed in order for `newAssignments.getMap().values().equals(projectAssignments.getMap().values())` to work correctly?
I would add a comment explaining the need for the `if`.

2024-07-19 18:08 UTC, martint requested changes
Some comments. Also, add an explanation in the commit message describing the condition that causes the infinite loop and why this change fixes it.

2024-07-19 18:08 UTC, martint commented on core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPreAggregateCaseAggregations.java
> +    public void testInfiniteOptimizeLoop()
In the future, it won't be clear why this is called "testInfiniteOptimizeLoop". Rename it to `testIssue22666()`

2024-07-19 18:08 UTC, martint commented on core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PreAggregateCaseAggregations.java
> +        if (newAssignments.getMap().values().equals(projectAssignments.getMap().values())) {
This is not going to be good enough for all scenarios. If the order of the assignments changes, they will be considered different by this check, even though, semantically, it's the same operations.

2024-07-23 13:05 UTC, kokosing commented
@jinyangli34 Do you need any help to address the comments? Are you available to continue working on it? Since it is a release blocker and in case you might have no time in near future to work on it, I can try to help and to find a person who might take over this work.

2024-07-25 13:37 UTC, sopel39 commented
alternative approach https://github.com/trinodb/trino/pull/22813

2024-07-25 13:38 UTC, sopel39 commented
Thx for spotting the issue!

2024-07-25 16:55 UTC, martint commented
Fixed by https://github.com/trinodb/trino/pull/22813

2024-07-25 16:55 UTC, closed without merging