Add compatibility note to S3 file system page
trinodb/trino pull request #22755
Opened 2024-07-22 16:56 UTC by michaeleby1

## Description

Add same note as #22711 to S3 file system page, indicating that we do not test all S3-compatible storage systems

## Additional context and related issues

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

2024-07-22 17:45 UTC, mosabua reviewed
Looks good in principal but I think we might want to elaborate some more, depending on the technical feedback.

2024-07-22 17:45 UTC, mosabua commented on docs/src/main/sphinx/object-storage/file-system-s3.md
> +manager is designed to support S3-compatible storage systems, not all such
@electrum @findinpath @ebyhr .. do we want to clarify that we test with S3 and I think also MinIO?

2024-08-23 17:48 UTC, mosabua commented on docs/src/main/sphinx/object-storage/file-system-s3.md
> +manager is designed to support S3-compatible storage systems, not all such
Sounds good .. can you address that @michaeleby1

2024-08-23 18:48 UTC, electrum commented on docs/src/main/sphinx/object-storage/file-system-s3.md
> +using the Delta Lake, Hive, Hudi, or Iceberg connectors. While the exchange
This should not say "exchange manager"

2024-08-23 18:51 UTC, electrum commented
I think we should remove this wording from the exchange manager documentation. It's very unlikely vendor documentation will tell the user about compatibility with Trino.

2024-08-23 18:58 UTC, mosabua commented
> I think we should remove this wording from the exchange manager documentation. It's very unlikely vendor documentation will tell the user about compatibility with Trino.

Fair... maybe we should tell to check vendor docs and basically test themselves or something ..  how do we want to guide users around the "S3-compatibility" from various systems when we just test with s3 and minio .. and even there we just use it in our testing but as open source project obviously dont offer "support"

2024-08-25 19:35 UTC, electrum commented
The user needs to test it themselves and contact the vendor with any questions.

2024-08-26 17:56 UTC, mosabua commented
> The user needs to test it themselves and contact the vendor with any questions.

Ok .. can you reword it along those links here and in the exchange section @michaeleby1 .. and mention what Trino tests run with (S3 and minio) but there should be no perception of "support"

2024-08-29 16:56 UTC, mosabua requested changes
One nit .. and also port these adjustments to the exchange manager section.

2024-08-29 18:55 UTC, mosabua approved these changes
Looks good now. I will merge after release completed.

2024-08-29 21:05 UTC, merged