Fix TrinoConnection.isValid - send a query to server to validate
trinodb/trino pull request #22853
Opened 2024-07-29 07:23 UTC by xsgao-github

## Description

Fix #22684 `TrinoConnection.isValid(long)` that did not validate if the connection is still valid.

## Additional context and related issues

From JDBC API/Javadoc:

> boolean isValid(int timeout) throws SQLException
Returns true if the connection has not been closed and is still valid. The driver shall submit a query on the connection or use some other mechanism that positively verifies the connection is still valid when this method is called.

This fix starts a probe query and deletes it right afterwards. By doing so, the query will not be executed on the server side.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

2024-07-29 07:33 UTC, ebyhr commented
You may want to read the past conversations in #13359

2024-07-29 08:14 UTC, wendigo requested changes
This is a no-go from me. We need a better way than sending a fake query that will pollute history

2024-07-29 14:01 UTC, xsgao-github commented
This fix calls `TrinoConnection.startQuery` without advancing to `nextUri`, so it won't generate an entry in Trino current/post query history.

2024-07-30 16:51 UTC, electrum commented
We should add a new endpoint that can be used to validate authentication and optionally the current session/transaction.

2024-09-11 17:03 UTC, closed without merging