Categorize HDFS quota exceeded exceptions as user errors and provide useful error messages
trinodb/trino pull request #22962
Opened 2024-08-06 21:27 UTC by xkrogen

## Description
Closes #22462. See the issue for context on how this issue manifests and what kind of confusing behavior it can cause.

This PR catches `QuotaExceededException` within the HDFS client, and re-throws them as `TrinoException` with a newly added error code `STORAGE_LIMIT_EXCEEDED` which has category `USER_ERROR`.

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(X) Release notes are required, with the following suggested text:

```markdown
# Hive
* Better categorize HDFS quota exceeded exceptions. ({issue}`issuenumber`)

# Iceberg
* Better categorize HDFS quota exceeded exceptions. ({issue}`issuenumber`)

# Hudi
* Better categorize HDFS quota exceeded exceptions. ({issue}`issuenumber`)

# Delta Lake
* Better categorize HDFS quota exceeded exceptions. ({issue}`issuenumber`)
```

2024-08-12 22:03 UTC, xkrogen commented
Bump @electrum @pajaks

2024-09-03 18:16 UTC, wendigo approved these changes

2024-09-03 18:17 UTC, wendigo commented on core/trino-spi/src/main/java/io/trino/spi/StandardErrorCode.java
> +    STORAGE_LIMIT_EXCEEDED(132, USER_ERROR),
Just STORAGE_QUOTA_EXCEEDED ?

2024-09-03 18:18 UTC, electrum requested changes
My apologies for not following up. We shouldn't throw non-`IOException` from the filesystem. I'll follow up with an alternative.

2024-09-03 18:26 UTC, mosabua commented
Given the comment from @electrum I am closing this PR.

2024-09-03 18:26 UTC, closed without merging