Allow configuring User-ManagedIdentity in AzureFS
trinodb/trino pull request #23447
Opened 2024-09-16 15:15 UTC by Praveen2112

## Description

This PR allows us to configure [User-ManagedIdentity](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview) for Azure FS. 

Since User Managed Identity can be tested only in a environment specified in Azure - we are restricting the test cases to config specific one. I'll be validating this change on AKS to check if the proper APIs are invoked. 

I'm open with testing on additional testing mechanisms if required. 

## Additional context and related issues

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
(x) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Allow configuring User-ManagedIdentity in AzureFS
```

2024-09-16 20:06 UTC, wendigo commented on lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthManagedIdentityConfig.java
> +        return !(getClientId().isPresent() && getResourceId().isPresent());
isEmpty() || isEmpty()

2024-09-16 20:06 UTC, wendigo commented on lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureAuthManagedIdentityConfig.java
> +        assertThat(actual.getClientId()).isEqualTo(expected.getClientId());
can we assert on actual values?

assertThat(...).hasValue()

2024-09-17 07:53 UTC, Praveen2112 commented
@wendigo AC

2024-09-17 09:45 UTC, nineinchnick commented on lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthManagedIdentityConfig.java
> +    @Config("azure.managed-identity.client-id")
Do we also need to update the docs to mention these new config options?

2024-09-17 10:38 UTC, wendigo commented
Aren't Github runners running on Azure 😉 ?

2024-09-17 13:21 UTC, anusudarsan reviewed
the commit title, docs (to be added) and release note entry should say "User-Assigned Managed Identity"

2024-09-17 13:21 UTC, anusudarsan commented
> Aren't Github runners running on Azure 😉 ?

can we trigger test with secrets?

2024-09-17 13:23 UTC, wendigo commented
@anusudarsan there are no new tests here

2024-09-17 16:00 UTC, Praveen2112 commented
I was looking for new recommendations on testing it.  If it sounds good then I could wrap up the docs for the same

2024-10-08 17:14 UTC, mosabua commented
I assume you are all still running with this @Praveen2112 @anusudarsan @wendigo

2024-10-30 08:29 UTC, Praveen2112 commented
@wendigo / @anusudarsan / @findinpath / @nineinchnick Added docs for the same.

2024-10-30 08:37 UTC, nineinchnick approved these changes

2024-10-30 10:01 UTC, krvikash commented on lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthManagedIdentityConfig.java
> +    @AssertTrue(message = "Exactly one of azure.managed-identity.client-id or azure.managed-identity.resource-id must be set")
When `auth-type` is set to `DEFAULT` then
Either 1) Both the properties `client-id` and `resource-id` not set Or 2) Only one of them is set right?

So Here in the description kind of misleading where it is mentioned that for one of the property must be set.

2024-10-30 10:13 UTC, krvikash approved these changes

2024-11-06 19:13 UTC, anusudarsan approved these changes

2024-11-06 19:29 UTC, mosabua requested changes

2024-11-06 19:29 UTC, mosabua commented on docs/src/main/sphinx/object-storage/file-system-azure.md
> +    uses system level credentials or [](user-assigned-managed-identity-authentication).
probably `system-level` but also .. what does "user system level credentials" even mean

2024-11-06 19:29 UTC, mosabua commented on docs/src/main/sphinx/object-storage/file-system-azure.md
> +## User-Assigned Managed Identity authentication
```suggestion
## User-assigned managed identity authentication
```

2024-11-06 19:29 UTC, mosabua commented on docs/src/main/sphinx/object-storage/file-system-azure.md
> +Use the following properties to configure User-Assigned Managed Identity authentication
```suggestion
Use the following properties to configure user-assigned managed identity authentication
```

2024-11-06 19:29 UTC, mosabua commented on docs/src/main/sphinx/object-storage/file-system-azure.md
> +Use the following properties to configure User-Assigned Managed Identity authentication
Probably need to link to some page in the Azure docs that explains what that is

2024-11-06 19:29 UTC, mosabua commented on docs/src/main/sphinx/object-storage/file-system-azure.md
> +  - Specifies the client ID of user assigned managed identity.
```suggestion
  - Specifies the client ID of the user-assigned managed identity.
```

2024-11-06 19:29 UTC, mosabua commented on docs/src/main/sphinx/object-storage/file-system-azure.md
> +  - Specifies the resource ID of user assigned managed identity.
```suggestion
  - Specifies the resource ID of the user-assigned managed identity.
```

2024-11-06 19:29 UTC, mosabua commented on docs/src/main/sphinx/object-storage/file-system-azure.md
> +## User-Assigned Managed Identity authentication
Do we really need the "User-assigned" part .. seems redundant and also you are not using it in the config name.. that makes it look redundant and at least inconsistent

2024-11-06 22:57 UTC, wendigo commented on lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthManagedIdentityConfig.java
> +    private String clientId;
I'd make the field Optional and return it in a getter but use .of() in the setter

2024-12-05 10:44 UTC, nandorKollar commented
When environment variables are set to valid Azure credentials (AZURE_CLIENT_ID/AZURE_CLIENT_SECRET) for the Trino process, then due to the chaining of different auth methods I think managed identity credentials are not used. This is an edge case, but it can cause headache to debug.

2025-01-21 17:49 UTC, mosabua commented
@Praveen2112 @anusudarsan @wendigo @nandorKollar .. there are two closed PRs for this feature now. Maybe we should reopen this PR and continue here?

2025-01-28 22:52 UTC, nandorKollar commented
I think we should at least reopen one of them, for example this one!

2025-01-29 21:29 UTC, mosabua commented
Discussed on Slack .. work on this PR will move towards merge. I am adding the stale-ignore label just in case..

2025-01-31 06:54 UTC, Praveen2112 commented on docs/src/main/sphinx/object-storage/file-system-azure.md
> +    uses system level credentials or [](user-assigned-managed-identity-authentication).
system-level here means loaded from the environment variable if set.

2025-01-31 06:57 UTC, Praveen2112 commented on docs/src/main/sphinx/object-storage/file-system-azure.md
> +## User-Assigned Managed Identity authentication
I guess it is more of a naming terminology used by Azure - In case of Azure ManagedIdentity - it has two types - User assigned and System assigned - so we need to identify them .

2025-04-10 06:23 UTC, Praveen2112 commented
@wendigo Can you PTAL ?

2025-04-25 17:10 UTC, nandorKollar approved these changes

2025-05-14 09:55 UTC, Praveen2112 commented
@wendigo Can you PTAL ?

2025-05-14 10:02 UTC, wendigo approved these changes

2025-05-14 10:04 UTC, merged

2025-12-31 14:33 UTC, eladitzhakian commented
> When environment variables are set to valid Azure credentials (AZURE_CLIENT_ID/AZURE_CLIENT_SECRET) for the Trino process, then due to the chaining of different auth methods I think managed identity credentials are not used. This is an edge case, but it can cause headache to debug.
> 
> Also, note that Azure doc recommends to avoid using DefaultAzureCredential in production: "In production, it's better to use something else". [Here](https://learn.microsoft.com/en-gb/azure/developer/java/sdk/authentication/credential-chains#usage-guidance-for-defaultazurecredential) you can find a great summary why it is recommended to avoid in production scenarios. I recommend using [ManagedIdentityCredential](https://learn.microsoft.com/en-us/java/api/com.azure.identity.managedidentitycredential?view=azure-java-stable) instead for managed identity authentication in Trino.

I think I might have encountered that edge case exactly.
I'm running Trino on-prem over a k3s cluster, and when setting the Azure credentials env vars mentioned above, they're not being picked up and I can't seem to authenticate.
Is there a way I can use the ManagedIdentityCredential instead using a configuration? Or does this require code change?