Add docs for json_table
trinodb/trino pull request #23761
Opened 2024-10-11 19:17 UTC by michaeleby1

## Description

## Additional context and related issues

Replaces #20338 

First released in 435 with https://github.com/trinodb/trino/pull/18017
Fix for being able to test it at all is in 436 - https://github.com/trinodb/trino/pull/20122

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

2024-11-27 20:58 UTC, blvckcoffee commented on docs/src/main/sphinx/functions/json.md
> +`json_path` is a string literal, containing the path mode specification, and
Feels like too many commas. What about `json_path` is a string literal containing the path mode specification and the path expression. It follows the syntax rules...

2024-11-27 20:58 UTC, blvckcoffee commented on docs/src/main/sphinx/functions/json.md
> +The `json_path` value is case-sensitive, while the SQL identifiers are
This is more of a nitpick: I prefer using 'while' when we're referring to time or when we're talking about something that occurs for as long as a condition is true. What if we just split this into two short sentences?

2024-11-27 20:58 UTC, blvckcoffee commented on docs/src/main/sphinx/functions/json.md
> +`FOR ORDINALITY` adds incremental row numbers to the table, starting from `1`.
Another thing that's more of a nitpick: Prefer 'at' over 'from' if we are talking about an initial value of exactly 1.

2024-11-27 20:58 UTC, blvckcoffee commented on docs/src/main/sphinx/functions/json.md
> +You can also process nested JSON objects with multiple levels, without parsing
The comma in this sentence can be removed. By definition, doesn't a nested JSON object have multiple levels? If so, this is redundant. What about 'You can process nested JSON objects without parsing the data multiple times'?

2024-11-27 20:58 UTC, blvckcoffee commented on docs/src/main/sphinx/functions/json.md
> +objects and return them as rows in a table with three columns:
returns

2024-11-27 20:58 UTC, blvckcoffee commented on docs/src/main/sphinx/functions/json.md
> +JSON objects with multiple levels:
As above, 'with multiple levels' might be redundant unless an SME thinks this is an important distinction.

2024-11-27 20:58 UTC, blvckcoffee commented on docs/src/main/sphinx/functions/json.md
> +JSON objects with multiple levels:
As above, 'with multiple levels' might be redundant unless an SME thinks this is an important distinction.

2024-12-03 09:59 UTC, kasiafi reviewed
@michaeleby1 great job! It will be very useful to have `json_table` finally documented.

I left a few comments.

Also, I'm not sure if it's clear to the reader how to use `json_table` in the context of a query. `json_table` is a lateral relation, and typically it will be used as part of a join:
```
SELECT * 
FROM orders, json_table(...)
```
It clarifies where the `json_input` and the `PASSING` parameters come from.

2024-12-03 09:59 UTC, kasiafi commented on docs/src/main/sphinx/functions/json.md
> +    [ { ERROR | NULL | EMPTY { [ARRAY] | OBJECT } | DEFAULT expression } ON EMPTY ]
Columns have one more optional clause:
`(KEEP | OMIT) QUOTES (ON SCALAR STRING)?`

2024-12-16 08:07 UTC, kasiafi reviewed
Hi @michaeleby1 and thank you for applying the comments.

There is one more issue regarding the taxonomy. 
In SQL, `json_table` is not a table function. It is a clause, similar to `lateral` or `unnest`. It does not follow the syntactic rules for table functions. 
As you noticed, `json_table` is indeed implemented using the table functions framework, but that should be considered an implementation detail.

That said, I wonder where `json_table` belongs in the docs. 
I think we can keep it in the `functions/json` section but reword so that we call it a clause, not a table function. Keeping it there would be convenient to the reader. 
Also, `json_table` should be mentioned in the `SELECT` section, along with `unnest` and `lateral`.

2024-12-19 19:06 UTC, michaeleby1 commented
@kasiafi I removed references to `json_table` as a "table function." 
 
When you say "`json_table` should be mentioned in the `SELECT` section," can you confirm if you mean that you'd like me add a new section for `json_table` to [select.md](https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/sql/select.md)?

2025-01-02 14:11 UTC, kasiafi commented
>can you confirm if you mean that you'd like me add a new section for json_table to [select.md](https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/sql/select.md)?

@michaeleby1 yes, that is what I meant. `json_table` should be mentioned somewhere next to `unnest` or `lateral`. The mention does not have to be very verbose. A one-sentence summary and a link to the full description in `functions/json.md`

2025-01-06 18:48 UTC, michaeleby1 commented
> `json_table` should be mentioned somewhere next to `unnest` or `lateral`. The mention does not have to be very verbose. A one-sentence summary and a link to the full description in `functions/json.md` should suffice.

I added a short description to select.md

2025-01-15 07:42 UTC, kasiafi approved these changes
LGTM

@mosabua do you want to take a final look?

2025-01-15 16:31 UTC, mosabua commented
Sure .. let me give it a final review

2025-01-15 16:49 UTC, mosabua requested changes

2025-01-15 16:49 UTC, mosabua commented on docs/src/main/sphinx/functions/json.md
> +analyze. Use `json_table` in the `FROM` clause of a `SELECT` statement to create
```suggestion
analyze. Use `json_table` in the `FROM` clause of a `SELECT` statement to create
```

Link the SELECT to the docs for it

2025-01-15 16:49 UTC, mosabua commented on docs/src/main/sphinx/functions/json.md
> +{ref}`json-path-syntax-and-semantics`.
Use markdown syntax for ref links everywhere 

```suggestion
[](json-path-syntax-and-semantics).
```

2025-01-15 16:49 UTC, mosabua commented on docs/src/main/sphinx/functions/json.md
> +`FOR ORDINALITY` adds incremental row numbers to the table, starting at `1`.
How ... as a separate column .. if so .. whats the column name or how can you access it?

2025-01-15 16:49 UTC, mosabua commented on docs/src/main/sphinx/sql/select.md
> +more information, see {ref}`JSON_TABLE <json-table>`.
markdown link

2025-01-15 16:49 UTC, mosabua commented on docs/src/main/sphinx/functions/json.md
> +SELECT
can we reduce the indentation on all this .. max 4 spaces in my opinion

2025-01-15 16:49 UTC, mosabua commented on docs/src/main/sphinx/functions/json.md
> +The following query uses `json_table` to extract values from an array of JSON
Should we just call it an "JSON array" .. so there is no confusion since the whole value is basically valid JSON ..

2025-01-15 16:49 UTC, mosabua commented on docs/src/main/sphinx/functions/json.md
> +JSON objects:
We should says something more here.. how the continent value is used multiple times and essentially the two JSON tables (nested) are transformed into one flat table and point out the syntax that achieves this after the snippet.

2025-01-15 16:49 UTC, mosabua commented on docs/src/main/sphinx/functions/json.md
> +The following query uses `PLAN` to specify an `OUTER` join between a parent path
Given that the next two examples use and empty array of input and the whole syntax is not really explained I think we either have to update these now .. or revisit in a follow up PR (I prefer that so we can ship this PR) .. but as it stands I think the two examples are basically a headscratcher for the reader and barely useful unless you know and understand already.

2025-01-15 16:49 UTC, mosabua commented
Great job .. just a couple of small things and then we probably need a follow up PR or two to complete this.

2025-01-16 18:57 UTC, michaeleby1 commented on docs/src/main/sphinx/functions/json.md
> +SELECT
I followed the spacing in the examples on the rest of the page. Do we want to reduce the spacing on all examples on the page?

2025-01-17 16:40 UTC, mosabua commented on docs/src/main/sphinx/functions/json.md
> +SELECT
Ultimately yes .. but lets leave it for now

2025-01-17 16:40 UTC, mosabua approved these changes
Let ship this!

2025-01-17 16:40 UTC, merged