Add missing breaking change for http client property removal
trinodb/trino pull request #23762
Opened 2024-10-11 21:45 UTC by jhlodin

## Description

The linked airlift PR removed the `http-client.max-connections` property. This was reflected in the Trino documentation with #20101 but should have been given a breaking change since the property was applied by some users.

## Additional context and related issues

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text: Note in PR contents

```markdown
## Section
* Fix some things. ({issue}`issuenumber`)
```

2024-10-11 23:02 UTC, mosabua requested changes
Update the commit message as well please

How about 

"Add note about removed `*.http-client.max-connections`"

2024-10-11 23:02 UTC, mosabua commented on docs/src/main/sphinx/release/release-440.md
> +  ([Airlift PR #1118](https://github.com/airlift/airlift/pull/1118))
```suggestion
  ({issue}`20966`)
```

2024-10-11 23:07 UTC, mosabua commented on docs/src/main/sphinx/release/release-440.md
> +  ([Airlift PR #1118](https://github.com/airlift/airlift/pull/1118))
I added relevant comments to that PR that updates Trino to airlift 241

2024-10-18 19:23 UTC, mosabua commented
Ping @jhlodin

2024-10-24 17:12 UTC, jhlodin commented
Addressed comments @mosabua

2024-10-24 17:51 UTC, mosabua approved these changes
Looks good now. Thank you.

2024-10-24 17:52 UTC, merged