Add documentation for iceberg memory file system caching properties
trinodb/trino pull request #24061
Opened 2024-11-07 20:05 UTC by sheajamba

## Description

This PR adds a section to the Iceberg connector documentation for memory file system cache. The following properties are documented:

- `fs.memory-cache.ttl`
- `fs.memory-cache.max-size`
- `fs.memory-cache.max-content-length`

## Additional context and related issues

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
## Section
* Fix some things. ({issue}`issuenumber`)
```

2024-11-07 20:06 UTC, sheajamba commented
@mosabua Does this need its own memory file caching page similar to file system cache?

2024-11-07 20:07 UTC, sheajamba commented
@raunaqmorarka Can you help me fill out the default values for these properties? Thanks!

2024-11-07 21:46 UTC, mosabua commented
> @mosabua Does this need its own memory file caching page similar to file system cache?

It definitely should go into the object-storage folder and documentation since it is NOT specific to a connector. Its is part of the file system support in Trino. 

However I dont know for sure how it relates to the S3, GCS, and Azure storage docs .. I think it is a separate file system support but it is also somehow related and used by all of them.. at least optionally.


The memory-cache config stuff is only part of the overall memory file system .. we might have to collect all that info from @electrum and @raunaqmorarka and the code and figure out how it all hangs together and how to best document that.

2024-11-07 21:46 UTC, mosabua requested changes
We definitely need to understand this better and put it into the object storage section.. details to be determined.

2024-11-18 08:04 UTC, raunaqmorarka commented on docs/src/main/sphinx/connector/iceberg.md
> +    `?`.
200mb

2024-11-18 08:04 UTC, raunaqmorarka commented on docs/src/main/sphinx/connector/iceberg.md
> +`iceberg.metadata-cache.enabled` configuration property to `true`.
This is already `true` by default, so we should rather say set this to `false` to disable it

2024-11-18 08:04 UTC, raunaqmorarka commented on docs/src/main/sphinx/connector/iceberg.md
> +The connector supports configuring and using memory file system caching. To
`The connector supports configuring and using memory file system caching` -> `The connector supports caching iceberg metadata in coordinator memory`.

2024-11-18 08:04 UTC, raunaqmorarka commented on docs/src/main/sphinx/connector/iceberg.md
> +enable memory file system caching, you must set the
`memory file system caching` -> `in-memory iceberg metadata caching`

2024-11-18 08:04 UTC, raunaqmorarka commented on docs/src/main/sphinx/connector/iceberg.md
> +### Memory file system cache
Use `in-memory iceberg metadata cache` instead of `memory file system cache` everywhere

2024-11-18 08:06 UTC, raunaqmorarka commented
> We definitely need to understand this better and put it into the object storage section.. details to be determined.

I think this is documented in the right place. Although the implementation is written to be connector agnostic, it is used only within iceberg connector at the moment and the fact that it is a "memory filesystem cache" is an implementation detail.

2024-11-18 18:02 UTC, raunaqmorarka commented on docs/src/main/sphinx/connector/iceberg.md
> +This cache is not used when `fs.cache.enabled` is set to `true.`
I would add a line that when filesystem caching from `fs.cache.enabled` is enabled, iceberg metadata is cached on local disks using the filesystem caching implementation.

2024-11-18 18:10 UTC, mosabua commented
> > We definitely need to understand this better and put it into the object storage section.. details to be determined.
> 
> I think this is documented in the right place. Although the implementation is written to be connector agnostic, it is used only within iceberg connector at the moment and the fact that it is a "memory filesystem cache" is an implementation detail.

.. how do we make sure we dont forget when we add it to another connector. Also .. what about all the other properties? I would want to make sure it is at least in a separate fragment file and not in the connector docs file itself.

2025-01-02 02:14 UTC, mosabua commented
@electrum the property names kinda indicate that this is a generic feature .. but then the docs are iceberg only .. should this be in a fragment and generically worded and then use in Iceberg only and later in other connectors? Or should the properties be renamed?

2025-01-02 14:01 UTC, raunaqmorarka commented
> @electrum the property names kinda indicate that this is a generic feature .. but then the docs are iceberg only .. should this be in a fragment and generically worded and then use in Iceberg only and later in other connectors? Or should the properties be renamed?

I think it makes sense for the code to be generic and we wouldn't want to rename properties in future if we choose to use it in another connector. But the documentation should treat it as an iceberg connector feature, the genericness is an implementation detail.

2025-01-13 21:38 UTC, mosabua requested changes

2025-01-13 21:38 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +:::{list-table} In-memory Iceberg metadata caching configuration properties
```suggestion
:::{list-table} Metadata caching configuration properties
```

2025-01-13 21:38 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +    starts the moment an entry is saved in the cache. The minimum value of `0s`
Remove the sentence "Time starts..."

2025-01-13 21:38 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +  - The maximum total size of the cache. This value can be set higher for a
Data size and link

2025-01-13 21:38 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +    large number of tables if you have sufficient coordinator memory. Defaults to
Reword the sentence to just say something like "When raising this value .. keep in mind that the coordinator memory is used.."

2025-01-13 21:38 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +This cache is not used when `fs.cache.enabled` is set to `true.`
@sheajamba .. dont forget this one

2025-01-15 17:37 UTC, sheajamba commented
Sorry for the delay. I have updated the PR with feedback.

2025-01-15 18:00 UTC, mosabua requested changes

2025-01-15 18:00 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +When file system caching from `fs.cache.enabled` is enabled, Iceberg metadata is
Move this up into the intro of this section and add this info first. Then talk about the in-memory stuff

2025-01-15 18:00 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +### In-memory Iceberg metadata caching
Lets make it broader

```suggestion
### Iceberg metadata caching
```

2025-01-15 18:00 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +The connector supports caching Iceberg metadata in memory. This caching is
Reword this so it fits with the moved up content

2025-01-15 18:10 UTC, sheajamba commented
I moved this sentence to a warning/note:

` In-memory caching is not used when `fs.cache.enabled` is set to `true`.`

If you think it fits better outside a warning let me know.

2025-01-17 14:25 UTC, raunaqmorarka approved these changes

2025-01-17 16:27 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +cached on local disks using the files system caching implementation. The Iceberg
I think this is wrong now ... here is what I understood from @raunaqmorarka 

fs.cache.enabled=true - metadata (and data) is cached with the file system caching (so on disk or whatever is configured there), AND .. memory metadata caching is deactivated

fs.cache.enabled=false - memory metadata caching is automatically activated, and uses coordinator memory only (hence planning and such is done on coordinator so thats where that metadata is needed)

2025-01-27 06:11 UTC, raunaqmorarka commented on docs/src/main/sphinx/connector/iceberg.md
> +cached on local disks using the files system caching implementation. The Iceberg
@mosabua yes the above is correct, but I think what is written now also conveys the same thing. Maybe the sentence in the warning should move up to make that clearer.

2025-01-27 17:18 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +cached on local disks using the files system caching implementation. The Iceberg
I think the current wording is wrong order of things and should be reworded.

2025-04-07 17:17 UTC, raunaqmorarka approved these changes

2025-04-07 17:50 UTC, merged