Document caching impersonation configuration options
trinodb/trino pull request #24191
Opened 2024-11-20 05:17 UTC by findinpath

## Description

2024-11-20 05:25 UTC, ebyhr approved these changes

2024-11-20 05:25 UTC, ebyhr commented on docs/src/main/sphinx/object-storage/metastores.md
> +  - `10`
Could you change `10` to `1000`? 
https://github.com/trinodb/trino/blob/b519bdf7d90aeb414121788999b48930cef6d934/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/ImpersonationCachingConfig.java#L26

2024-11-20 05:25 UTC, ebyhr commented on docs/src/main/sphinx/object-storage/metastores.md
> +  - `10`
Could you change `10` to `0s`? 
https://github.com/trinodb/trino/blob/b519bdf7d90aeb414121788999b48930cef6d934/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/ImpersonationCachingConfig.java#L25

2024-11-20 05:25 UTC, ebyhr commented on docs/src/main/sphinx/object-storage/metastores.md
> +    which are user specific in user impersonation scenarios .
```suggestion
    which are user specific in user impersonation scenarios.
```

2024-11-20 05:25 UTC, ebyhr commented on docs/src/main/sphinx/object-storage/metastores.md
> +  - Duration of how long cached metastore statistics which are user specific
Could you change `Duration` to `[Duration](prop-type-duration)`?

2024-11-20 20:14 UTC, mosabua requested changes

2024-11-20 20:14 UTC, mosabua commented on docs/src/main/sphinx/object-storage/metastores.md
> +  - [Duration](prop-type-duration) of how long cached metastore statistics which are user specific
```suggestion
  - [Duration](prop-type-duration) of how long cached metastore statistics, which are user specific
```

2024-11-20 20:14 UTC, mosabua commented on docs/src/main/sphinx/object-storage/metastores.md
> +    in user impersonation scenarios are considered valid.
```suggestion
    in user impersonation scenarios, are considered valid.
```

2024-11-20 20:14 UTC, mosabua commented on docs/src/main/sphinx/object-storage/metastores.md
> +  - Maximum number of metastore data objects in the Hive metastore cache
```suggestion
  - Maximum number of metastore data objects in the Hive metastore cache,
```

2024-11-25 14:50 UTC, findinpath commented
@mosabua  pls review again this PR

2024-11-25 17:49 UTC, mosabua approved these changes

2024-11-25 17:49 UTC, merged