Add failure event for queries that were posted but not submitted
trinodb/trino pull request #24205
Opened 2024-11-20 18:12 UTC by mduggan-starburst

## Description

## Additional context and related issues

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
## Section
* Fix some things. ({issue}`issuenumber`)
```

2024-11-27 10:52 UTC, losipiuk commented on core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
> +    private static QueryStatistics createEmptyStatistics(Duration queuedTime)
unrelated change. Fine on its own but move to separate commit

2024-11-27 10:53 UTC, losipiuk commented on core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
> +            if (!dispatchManager.cancelQuery(queryId)) {
why can't we have event logic in `dispatchManager.cancelQuery`? 
Is that lack of session or the fact that is used from QueryResource too? Or ... ?

2024-11-27 10:54 UTC, losipiuk commented
Looks generally good. @wendigo PTAL too.
Sorry for late review. I did not notice. Please ping me if I am not responsive.

2024-11-27 13:22 UTC, hashhar commented
IMO @electrum should also take a look because from my discussion with him in the past this was intentional part of protocol.

https://github.com/trinodb/trino-python-client/pull/394#discussion_r1314923811

2024-12-02 19:52 UTC, electrum requested changes
This seems like a bad change, as it will cause bogus events for query resubmission. The query doesn't exist until the client fetches the first next URI.

What problem are you trying to solve? If this is for administrators to debug broken clients, you could add a debug log line for abandoned queries.

2024-12-03 18:55 UTC, mduggan-starburst commented
Closed due to conflicts with the Trino protocol

2024-12-03 18:55 UTC, closed without merging