Document $entries table in Iceberg
trinodb/trino pull request #24542
Opened 2024-12-20 07:12 UTC by ebyhr

## Description

Follow-up of https://github.com/trinodb/trino/pull/24172

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

2024-12-20 16:58 UTC, mosabua requested changes

2024-12-20 16:58 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +```text
I think we can cut this output down .. for data_file and readable_metrics just start with the first bit and then use ...

2024-12-20 16:58 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +```text
and above the table say something like

Abbreviated sample output:

2024-12-20 16:58 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +  - Used to track additions and deletions. Deletes are informational only and
```suggestion
  - Numeric status indication to track additions and deletions. Deletes are informational only and 
```

2024-12-20 16:58 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +  - Data sequence number of the file. Inherited when null and status is 1 (added).
```suggestion
  - Data sequence number of the file. Inherited when null and status is 1.
```

2024-12-20 16:58 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +  - The snapshot ID of the reference.
what reference? I might not know about this enough..

2024-12-20 16:58 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +    and status is 1 (added).
```suggestion
    and status is 1.
```

2024-12-20 16:58 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +  - File path, partition tuple, metrics, ...
JSON formatted metadata including file path, file format, file size and other information.

2024-12-20 16:58 UTC, mosabua commented on docs/src/main/sphinx/connector/iceberg.md
> +  - File metrics in human-readable form.
JSON-formatted file metrics such as column size, value count and others.

2025-01-07 01:14 UTC, ebyhr commented on docs/src/main/sphinx/connector/iceberg.md
> +  - File path, partition tuple, metrics, ...
`data_file` field isn't JSON.

2025-01-09 17:54 UTC, mosabua approved these changes

2025-01-09 17:55 UTC, merged

2025-01-09 17:56 UTC, mosabua commented
Do we need another PR for all_entries .. or just expand this section?