[WIP] Prune unnest mappings using lambda expressions
trinodb/trino pull request #4270
Opened 2020-06-30 04:44 UTC by phd3

2020-09-01 01:32 UTC, martint commented on presto-main/src/test/java/io/prestosql/sql/planner/assertions/ExpressionVerifier.java
> +        Node getExpectedNode()
public

2020-09-01 01:32 UTC, martint commented on presto-main/src/test/java/io/prestosql/sql/planner/assertions/ExpressionVerifier.java
> +        SymbolAliases getSymbolAliases()
public

2020-09-01 01:32 UTC, martint commented on presto-main/src/test/java/io/prestosql/sql/planner/assertions/ExpressionVerifier.java
> +        Context replaceExpectedNode(Expression expected)
public

2020-09-10 00:38 UTC, martint requested changes
The rule should not apply if all fields from a row are being referenced. E.g.,

```sql
WITH t(a) AS (
    VALUES (ARRAY[CAST(ROW(ROW(1, 2)) AS ROW(a ROW(f1 INTEGER, f2 INTEGER)))])
)
SELECT x.f1, x.f2
FROM t, UNNEST(t.a) t(x)
```

2020-09-10 00:38 UTC, martint commented on presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneUnnestMappings.java
> + *              Source(A, B_ARAAY)
Typo: B_ARAAY

2020-09-10 00:38 UTC, martint commented on presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneUnnestMappings.java
> +        }
Why do we need this?

2020-09-10 00:38 UTC, martint commented on presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneUnnestMappings.java
> +            Symbol lambdaSymbol,
`lambdaArgument`

2020-09-10 00:38 UTC, martint commented on presto-main/src/test/java/io/prestosql/sql/query/TestUnnest.java
> +        assertThat(assertions.query(
Can you add some more tests?

* One that references all unnested fields
* One that references some fields from both arrays
* One that references a whole row column (e.g., `z` in the query below)

2022-10-19 21:02 UTC, colebow commented
:wave: @phd3 - this PR is inactive and doesn't seem to be under development. If you'd like to continue work on this at any point in the future, feel free to re-open.

2022-10-19 21:02 UTC, closed without merging