Add varchar and varbinary replicate function
trinodb/trino pull request #5674
Opened 2020-10-23 11:06 UTC by wendigo

2020-10-23 11:12 UTC, losipiuk commented on presto-main/src/main/java/io/prestosql/operator/scalar/VarbinaryFunctions.java
> +    @Description("Repeats a given varbinary a number of times")
```suggestion
    @Description("Repeats a varbinary given number of times")
```

2020-10-23 11:14 UTC, losipiuk reviewed
@martint please take a look if syntax looks good to you

2020-10-23 11:14 UTC, losipiuk commented on presto-main/src/main/java/io/prestosql/operator/scalar/StringFunctions.java
> +        checkCondition(times >= 0, INVALID_FUNCTION_ARGUMENT, "Invalid number of string repetitions: " + times);
Is 0 valid?

2020-10-23 11:14 UTC, losipiuk commented on presto-main/src/main/java/io/prestosql/operator/scalar/StringFunctions.java
> +    private static Slice repeat(Slice text, long times)
Inline?

2020-10-23 11:14 UTC, losipiuk commented on presto-main/src/main/java/io/prestosql/operator/scalar/VarbinaryFunctions.java
> +        checkCondition(times >= 0, INVALID_FUNCTION_ARGUMENT, "Invalid number of string repetitions: " + times);
is 0 valid?

2020-10-23 11:15 UTC, losipiuk commented
Also please add documentation as we settle that we want this function.

2020-10-23 15:22 UTC, martint requested changes
I'd call the function `repeat`, but I'd like to hear other's thoughts.

2020-10-23 15:22 UTC, martint commented on presto-main/src/main/java/io/prestosql/operator/scalar/StringFunctions.java
> +            throw new PrestoException(EXCEEDED_FUNCTION_MEMORY_LIMIT, e.getMessage());
We should cap the size at a more reasonable value. A 1GB allocation might work, for instance, but a page that big will cause all sorts of problems. I would pick a limit in the order of megabytes to align with the target size for a page. See PageBuilderStatus.DEFAULT_MAX_PAGE_SIZE_IN_BYTES

2020-10-23 15:29 UTC, wendigo commented
> I'd call the function `repeat`, but I'd like to hear other's thoughts.

@martint we already have repeat function for array creation with same signature

2020-10-28 01:08 UTC, martint commented
> @martint we already have repeat function for array creation with same signature

Ugh, that's unfortunate, especially since other databases like MySQL, PostgreSQL and Oracle have a `repeat` function that works exactly like the one proposed by this change. The existing function should've never been added in that form.

We may want to deprecate the existing function and give it a different name, and introduce a new `repeat` that produces a varchar instead (similar to when we had to replace the `log` function after it was specified in SQL 2016). This will require waiting some time, as we need to give users enough time to adjust. It could also be gated behind a config option.

cc @prestosql/maintainers

2020-10-28 08:55 UTC, findepi commented
@martint i agree.
Ideally, during the transition period we should have _no_ `repeat` function (at least by default).
The roadmap could look like

1. get agreement on the new name for `repeat(element, count) → array`  function
1. introduce new function as a replacement for `repeat(element, count) → array` and deprecate the existing one
    - then  users caring about warnings will have smooth upgrade path
1. (after some wait time) put deprecated `repeat(element, count) → array`  behind a toggle
    - then users not reading/getting warnings will have more rocky, but still manageable upgrade path 
    - when toggle is off, we can still expose `repeat(element, count) → array`, with some actionable err msg
1. (after some wait time) remove deprecated `repeat(element, count) → array`
1. (perhaps with no further delay) introduce new `repeat(varchar, count) → varchar` function

2021-11-22 14:39 UTC, closed without merging