Fix JdbcRecordCursor.isNull for types mapped to slice
trinodb/trino pull request #5711
Opened 2020-10-27 19:27 UTC by elonazoulay

This fixes an issue when the postgresql plugin is
used to connect to cockroachdb: https://go.crdb.dev/issue-v/40195/v20.1

2020-10-27 20:10 UTC, electrum submitted a review, later dismissed

2020-10-27 20:11 UTC, electrum commented
Is that link right? I don't see how it relates to this issue.

2020-10-27 20:17 UTC, electrum commented
I'm not sure this is the correct fix. There are various types mapped to `Slice` including long decimal, varbinary, etc., for which calling `getString()` actually seems less appropriate than `getObject()`. Which data types require calling `getString()` rather than `getObject()`? It might be better to add a specific PostgreSQL fix for just those types.

2020-10-27 20:19 UTC, findepi requested changes

2020-10-27 20:19 UTC, findepi commented on presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/SliceReadFunction.java
> +        resultSet.getString(columnIndex);
I do not see a reason why resultSet.getString() should be better than resultSet.getObject().
The code is redundant and can easily be accidentally removed with a refactor.
Can we have a test for this?

Also, if this is cockrach specific behavior, the correct approach is to provide `SliceReadFunction` and implement `isNull` for that case.

2020-10-27 20:43 UTC, findepi commented
@elonazoulay would it be possible to have a real cockroachdb connector?
For example, we have a a Redshift connector even though PostgreSQL connector "somewhat works" for Redshift.
Or, we're adding Yugabyte connector even though Cassandra connector "mostly works" for Yugabyte (https://github.com/prestosql/presto/issues/5352).
I think Cockroach DB is a similar story.

2020-10-27 20:44 UTC, findepi commented
It seems it should be pretty straightforward to test too, given https://www.testcontainers.org/modules/databases/cockroachdb/ exists.

2020-10-28 09:50 UTC, elonazoulay commented
@findepi, yes! We were thinking to add time travel as well, so queries via the presto connector minimize contention with operational queries: https://www.cockroachlabs.com/docs/stable/as-of-system-time.html

2022-11-11 22:13 UTC, closed without merging