Document for assume canonical hive partition key
trinodb/trino pull request #6599
Opened 2021-01-14 08:06 UTC by allendang001

2021-01-14 08:48 UTC, findepi commented
Does this supersede https://github.com/trinodb/trino/pull/6438 ?

2021-02-11 18:28 UTC, mosabua requested changes
A bit lengthy but ok after the change to not use future tense

2021-02-11 18:28 UTC, mosabua commented on docs/src/main/sphinx/connector/hive.rst
> +                                                                on value 42, then the Hive connector will ask the metastore
connectors asks the metastore

2021-02-11 18:28 UTC, mosabua commented on docs/src/main/sphinx/connector/hive.rst
> +                                                                for partitions matching the string '42', which will fail to
which fails to ..

2022-10-21 20:57 UTC, bitsondatadev commented
:wave: @allendang001 - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

2022-11-18 20:08 UTC, bitsondatadev commented
Gonna close this one out due to inactivity, please reopen if you would like to continue doing work here.

2022-11-18 20:08 UTC, closed without merging