Remove restriction
trinodb/trino pull request #6647
Opened 2021-01-19 21:11 UTC by mosabua

2021-01-20 12:15 UTC, findepi commented on docs/src/main/sphinx/optimizer/pushdown.rst
> -* adding a condition to the query
This is correct

2021-01-20 12:20 UTC, sopel39 approved these changes

2021-01-20 12:35 UTC, findepi requested changes
I think the removed wording was factually correct. Can you please add some more context why do you think we should remove it?

2021-01-20 17:30 UTC, mosabua commented
Supposedly it was correct in the past but no longer applies.

2021-01-22 00:20 UTC, mosabua commented
Turns out everything is as it should be after all

2021-01-22 00:20 UTC, closed without merging