Add shell checks to CI
trinodb/trino pull request #6687
Opened 2021-01-22 08:58 UTC by Praveen2112

Reference https://github.com/koalaman/shellcheck

2021-01-22 09:06 UTC, hashhar commented on .github/workflows/ci.yml
> +        uses: azohra/shell-linter@latest
`latest` causes issues with CI stability IMO.

2021-01-22 10:42 UTC, kokosing commented
@Praveen2112 Are you going to fix all the issues?

2021-01-22 10:43 UTC, kokosing commented
How to exclude scripts that we do not own?

2021-01-22 12:22 UTC, Praveen2112 commented
I'm planning to use this action https://github.com/marketplace/actions/shellcheck which provides a way to ignore these actions and also ignore a few checks. WDYT ?

2021-01-22 16:32 UTC, findepi requested changes

2021-01-22 16:32 UTC, findepi commented on core/docker/bin/run-trino
> +exec /usr/lib/trino/bin/launcher run --etc-dir /etc/trino "${NODE_ID}" "$@"
that's not correct. the `"` was _intentionally_ missing here

to be even better, you'd need to make the variable an array

2021-01-28 11:47 UTC, kokosing commented on .github/bin/retry
>  max_retry_time_seconds=$(( 30 * 60 ))
Commits should be order in the following order:
 - fix stuff
 - add CI job
 
 That way all commits have a chance to pass the CI.
 
 Also please extract more commits. I see that you are adding `"` frequently, please extract separate commit with only this so we could see other changes not mixed with it. It is easier to not to overlook things.

2021-01-28 11:47 UTC, kokosing commented on core/trino-main/bin/check_webui.sh
> +yarn --cwd "${WEBUI_ROOT}"/src/ install
put entire path to `"`. i.e. `"${WEBUI_ROOT}/src/"`, please do the same for others.

2021-01-28 11:47 UTC, kokosing commented on plugin/trino-hive-hadoop2/bin/common.sh
> +    for file in "${files[@]}"; do
does it work? Will get a list of values or a single value?

2022-10-21 20:59 UTC, bitsondatadev commented
:wave: @Praveen2112 - this PR is inactive and doesn't seem to be under development. If you'd like to continue work on this at any point in the future, feel free to re-open.

2022-10-21 20:59 UTC, closed without merging