Add doc for optimizer.plan-with-table-node-partitioning
trinodb/trino pull request #7323
Opened 2021-03-17 16:01 UTC by sopel39

2021-03-20 05:30 UTC, raunaqmorarka commented on docs/src/main/sphinx/admin/properties-optimizer.rst
> +Use connector provided table node partitioning when reading tables.
What is "connector provided table node partitioning" ?
Maybe a concrete example of a connector would help

2021-03-20 05:33 UTC, raunaqmorarka commented on docs/src/main/sphinx/admin/properties-optimizer.rst
> +When set to ``true`` each table partition is read by a separate node.
When should a user consider setting it to false ?

2021-03-22 10:53 UTC, raunaqmorarka commented on docs/src/main/sphinx/admin/properties-optimizer.rst
> +parallel processing. Using of table scan node partitioning can improve
Using of -> Use of

2021-03-22 10:54 UTC, raunaqmorarka approved these changes

2021-03-22 10:54 UTC, raunaqmorarka approved these changes

2021-03-22 21:22 UTC, mosabua requested changes

2021-03-24 16:34 UTC, mosabua requested changes
Update to avoid using e.g. and () ..

2021-03-24 16:34 UTC, mosabua commented on docs/src/main/sphinx/admin/properties-optimizer.rst
> +query performance by reducing query complexity (e.g cluster wide data reshuffle
complexity. For example, cluster wide data reshuffling might not be needed when processing an aggregation query. However, ..

2021-03-24 16:47 UTC, mosabua approved these changes

2021-03-25 18:48 UTC, electrum approved these changes

2021-03-25 18:48 UTC, merged