Add doc for table-scan-node-partitioning-min-bucket-to-task-ratio
trinodb/trino pull request #7325
Opened 2021-03-17 16:20 UTC by sopel39

to be landed after: https://github.com/trinodb/trino/pull/7257

2021-03-20 05:42 UTC, raunaqmorarka commented on docs/src/main/sphinx/admin/properties-optimizer.rst
> +to use table scan node partitioning. When there is not enough buckets
We should explain what is "table scan node partitioning"

2021-03-20 05:45 UTC, raunaqmorarka commented on docs/src/main/sphinx/admin/properties-optimizer.rst
> +to use table scan node partitioning. When there is not enough buckets
When there is not enough buckets... -> When the number of buckets is small compared to the number of table scan tasks then the table scan will be ...

2021-03-24 16:32 UTC, mosabua requested changes
Please update grammar and usage of "workers" as requested

2021-03-24 16:32 UTC, mosabua commented on docs/src/main/sphinx/admin/properties-optimizer.rst
> +compared to number of nodes then the table scan will be distributed
to the number of workers, then the table scan is distributed across all workers for improved parallelism.

2021-03-24 16:47 UTC, mosabua approved these changes

2021-03-25 18:49 UTC, electrum approved these changes

2021-03-26 11:51 UTC, merged