Add external/SSO authentication
trinodb/trino pull request #7713
Opened 2021-04-22 20:40 UTC by mosabua

2021-04-22 21:17 UTC, m57lyra approved these changes
LGTM

2021-04-22 21:17 UTC, m57lyra commented on docs/src/main/sphinx/installation/cli.rst
> +* Further queries in the CLI session do not require additional logins, while the
remove the comma before while

2021-04-22 21:20 UTC, Ordinant commented on docs/src/main/sphinx/installation/cli.rst
> +the CLI displays a URL that you have to open in a web browser for
s/have to/must

2021-04-22 21:21 UTC, Ordinant commented on docs/src/main/sphinx/installation/cli.rst
> +* Further queries in the CLI session do not require additional logins, while the
> remove the comma before while

What she said

2021-04-22 21:22 UTC, Ordinant commented on docs/src/main/sphinx/installation/cli.rst
> +  authentication token remains valid. Token expiry depends on the external
Token expiration depends on ...

2021-04-22 21:23 UTC, Ordinant requested changes
Comments interspersed.

2021-04-22 23:00 UTC, mosabua commented on docs/src/main/sphinx/installation/cli.rst
> +* Further queries in the CLI session do not require additional logins, while the
Done

2021-04-22 23:00 UTC, mosabua commented on docs/src/main/sphinx/installation/cli.rst
> +the CLI displays a URL that you have to open in a web browser for
done

2021-04-22 23:01 UTC, mosabua commented on docs/src/main/sphinx/installation/cli.rst
> +  authentication token remains valid. Token expiry depends on the external
done

2021-04-23 07:27 UTC, kokosing approved these changes
@s2lomon Please take a look.

2021-04-23 07:27 UTC, kokosing commented on docs/src/main/sphinx/installation/cli.rst
> +The  ``--external-authentication`` option is used for browser-based SSO
nit: double space after `The`

2021-04-23 11:13 UTC, s2lomon approved these changes
lgtm

2021-04-23 16:20 UTC, mosabua commented on docs/src/main/sphinx/installation/cli.rst
> +The  ``--external-authentication`` option is used for browser-based SSO
Fixed

2021-04-26 16:30 UTC, mosabua commented
Can we get this merged please @electrum?

2021-04-26 19:03 UTC, merged