Added example for map_union and fixed link
trinodb/trino pull request #7880
Opened 2021-05-10 21:16 UTC by ckodonnell

@mosabua @Ordinant @rosewms @m57lyra

2021-05-10 21:21 UTC, mosabua requested changes
Great start!

2021-05-10 21:21 UTC, mosabua commented on docs/src/main/sphinx/functions/aggregate.rst
> +        SELECT histogram(floor(petal_length_cm)) x
use a better column name than x

2021-05-10 21:21 UTC, mosabua commented on docs/src/main/sphinx/functions/aggregate.rst
> +                    x
add empty line to make it more readable

2021-05-10 21:28 UTC, mosabua commented
Fixes https://github.com/trinodb/trino/issues/7663

2021-05-10 22:37 UTC, ckodonnell commented
Sorry, I had some issues merging and they all submitted! Is there any way to "squash" these together?

2021-05-10 22:47 UTC, mosabua commented
you can rebase all these commits . For example see this

https://www.ksharifbd.com/blog/git-rebase-how-to-squash-multiple-commits-into-single-commit/#How-to-squash

and then force push

```
git push -f
```

2021-05-11 15:24 UTC, mosabua approved these changes
Excellent update. Good to go after the signed CLA is submitted.

2021-05-12 00:32 UTC, martint commented
@cla-bot check

2021-05-13 01:14 UTC, martint commented
Merged as 4c9c6d7c82d4bde81f44cf66dbb59cf44c958653. Thanks!

2021-05-13 01:14 UTC, closed without merging