Add JDBC URL parameter for MySQL
trinodb/trino pull request #8579
Opened 2021-07-16 15:20 UTC by Jessie212

2021-07-16 15:28 UTC, mosabua requested changes

2021-07-16 15:28 UTC, mosabua commented on docs/src/main/sphinx/connector/mysql.rst
> +    connection-url=jdbc:mysql://example.net:3306?serverTimezone=UTC
remove this change here

2021-07-16 15:28 UTC, mosabua commented on docs/src/main/sphinx/connector/mysql.rst
> +For known issues and limitations, see `known issues and limitations
change this to be talking about connetion url parameters. Something like

```
For example, you can configure the JDBC driver to interpret any time values based on UTC as 
timezone on the server as `workaround for a known issue <>`_ with the following ``connection-url``:

connection-url=jdbc:mysql://example.net:3306?serverTimezone=UTC
```

2021-07-16 17:48 UTC, mosabua commented on docs/src/main/sphinx/connector/mysql.rst
> +connection-url=jdbc:mysql://example.net:3306?serverTimezone=UTC allows you to
move this into a code block ..

2021-07-16 17:48 UTC, mosabua commented on docs/src/main/sphinx/connector/mysql.rst
> +
code block here

2021-07-16 19:18 UTC, mosabua approved these changes
Looks good now. Text is mostly identical to the existing (already approved) text in sqlserver.rst

2021-07-23 01:08 UTC, ebyhr approved these changes

2021-07-23 01:09 UTC, merged

2021-07-23 01:09 UTC, ebyhr commented
Merged, thanks!