Mark TestHiveStorageFormats:: testTimestampCreatedFromTrino as flaky
trinodb/trino pull request #8632
Opened 2021-07-21 19:51 UTC by CodyLeeWhite

Test fails with "Failed to translate Hive view 'test_list_failing_views.failing_view': At line 0, column 0: Object 'table_dropped' not found within 'hive.test_list_failing_views'"

Not sure how to set up the stress tests on this one. Since the test does not have a group assigned I'm not sure if its a product test or if it runs in another section of the ci

2021-07-22 00:25 UTC, electrum requested changes

2021-07-22 00:25 UTC, electrum commented on testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
> +    @Flaky(issue = "https://starburstdata.atlassian.net/browse/SEP-5855", match = "Failed to translate Hive view")
Please file a GitHub issue for this

2021-07-22 06:50 UTC, hashhar requested changes

2021-07-22 06:50 UTC, hashhar commented on testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
> +    @Flaky(issue = "todo", match = "Failed to translate Hive view")
The match shouldn't be on `Failed to translate Hive view`. That can mask bugs in the view translation layer.

Instead match on maybe `Object 'table_dropped' not found within 'hive.test_list_failing_views'`?

2021-07-26 14:05 UTC, hashhar commented
@CodyLeeWhite Please stress-test CI to make sure fix is effective. (See https://github.com/trinodb/trino/pull/7593/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR28 for example)

Looks good otherwise.

2021-07-26 22:15 UTC, CodyLeeWhite commented
<img width="249" alt="Screen Shot 2021-07-26 at 5 14 57 PM" src="https://user-images.githubusercontent.com/19784739/127066143-913dce1f-481e-4d7f-90b1-490d059783e0.png">

2021-07-27 11:07 UTC, hashhar approved these changes

2021-07-27 11:08 UTC, hashhar commented
The all-green run for reference - https://github.com/trinodb/trino/actions/runs/1068823573

2021-07-27 11:17 UTC, hashhar requested changes
Held for https://github.com/trinodb/trino/issues/8662#issuecomment-887427095.

Seems like there's more to this than just flakiness.

2022-08-09 16:57 UTC, closed without merging