Throw by default in Connector::rollback()
trinodb/trino pull request #8694
Opened 2021-07-28 12:32 UTC by kokosing

Throw by default in Connector::rollback()

So far rolback() method was not a no-op. That could lead to a false
impression that connector supports `ROLLBACK` statement while it is
be not true, as this implementation does not differ from commit() method
implementation.

2021-07-28 14:46 UTC, findepi commented
Is it still a draft?

2021-07-29 00:53 UTC, electrum commented
I don't understand why rollback is different than commit. This is going to cause errors (or at least spam the logs) for read-only connectors. If this is something we want to enforce, we should rethink how the APIs work.

2021-07-30 12:05 UTC, kokosing commented
> Is it still a draft?

I think it is more a discussion and proof of concept.

> I don't understand why rollback is different than commit. This is going to cause errors (or at least spam the logs) for read-only connectors. If this is something we want to enforce, we should rethink how the APIs work.

To me it is a correctness issue. When user does:
```
BEGIN;
CREATE ... x;
ROLLBACK;
SHOW ... ; -- should not return x, while today it is not the case.
```

I think disabling `ROLLBACK` is poor man approach as it is a bit too late. I think we should disallow calling `BEGIN` for connectors that do not support transaction (most of the connectors).

2021-07-30 12:06 UTC, kokosing commented
Also it is a pity that CI passed.

2021-07-30 12:12 UTC, kokosing commented
Relates to https://github.com/trinodb/trino/issues/8725

2021-08-12 23:31 UTC, electrum requested changes
This is a bug in the connector implementation: it returns `false` from `isSingleStatementWritesOnly()` even though it only supports single statement writes. However, we should fix that by changing the default implementation of that method to be `true` since Hive is currently the only connector that legitimately returns `false` and implementing multi-statement writes is extensive work.

2021-08-13 00:20 UTC, electrum commented
Replaced by #8872

2021-08-13 00:20 UTC, closed without merging