Update PostgreSQL driver to 42.2.23
trinodb/trino pull request #8770
Opened 2021-08-03 20:36 UTC by electrum

The PostgreSQL connector is not yet updated due to incompatibilities.

2021-08-03 20:39 UTC, findepi requested changes
So we're upgrading ... without upgrading?
Looks like the new version is not being picked outside of tests

2021-08-03 22:47 UTC, dain commented
Related to https://github.com/trinodb/trino/issues/7823

2021-08-03 22:47 UTC, electrum commented
Yes, this updates usages for tests, and other future usages such as DB-based resource groups (which has been started in #8530). CockroachDB (#8317) is another usage that requires a newer driver.

Additionally, this adds a comment to the PostgreSQL connector that explains why the driver cannot be updated, which was attempted in #7241 due to CVEs in the older driver version.

2021-08-03 23:48 UTC, dain approved these changes

2021-08-04 05:29 UTC, hashhar reviewed
I'm not sure what this benefits since the only thing using the driver directly in tests is testcontainers and queries that are executed directly on PostgreSQL. Trino would still be using the older driver even within tests (or does it not?)

2021-08-04 05:29 UTC, hashhar commented on plugin/trino-postgresql/pom.xml
> +            numeric types (>= 42.2.11) (Trino #7823)
Use a link that we can click instead. And maybe make this a TODO.

```suggestion
            numeric types (>= 42.2.11) (https://github.com/trinodb/trino/issues/7823)
```

2021-08-04 15:17 UTC, findepi commented
> Yes, this updates usages for tests, and other future usages such as DB-based resource groups (which has been started in #8530). CockroachDB (#8317) is another usage that requires a newer driver.

Looks like we're solving a problem that we do not have yet.

> Additionally, this adds a comment to the PostgreSQL connector that explains why the driver cannot be updated, which was attempted in #7241 due to CVEs in the older driver version.

I agree that it is a good idea to have a comment!

2021-08-04 17:12 UTC, merged