Document setdigest type
trinodb/trino pull request #9064
Opened 2021-08-31 20:56 UTC by findinpath

2021-09-01 12:57 UTC, kasiafi commented on docs/src/main/sphinx/language/types.rst
> +SetDigest
Put this section between `HyperLogLog` and `Quantile digest`.

2021-09-03 18:37 UTC, mosabua requested changes
One minor nit .. then good to go imho

2021-09-03 18:37 UTC, mosabua commented on docs/src/main/sphinx/language/types.rst
> +Set Digest encapsulates the following components:
SetDigest

2021-09-08 06:06 UTC, hashhar approved these changes

2021-09-08 06:06 UTC, merged