Extend UNNEST documentation with usage examples
trinodb/trino pull request #9555
Opened 2021-10-07 21:44 UTC by findinpath

This PR addresses:

fixes #3812
fixes #8471

documentation  issues

2021-11-02 13:28 UTC, kasiafi approved these changes
LGTM. @mosabua could you please take a look?

2021-11-03 18:43 UTC, mosabua requested changes
Minor tweaks only .. then good to go imho

2021-11-03 18:43 UTC, mosabua commented on docs/src/main/sphinx/sql/select.rst
> +``UNNEST`` will return 0 entries when the array/map to be expanded is empty::
returns zero entries when

2021-11-03 18:43 UTC, mosabua commented on docs/src/main/sphinx/sql/select.rst
> +``UNNEST`` will return 0 entries when the array/map to be expanded is empty::
.. could also leave "to be expanded" out altogether

2021-11-03 18:43 UTC, mosabua commented on docs/src/main/sphinx/sql/select.rst
> +``UNNEST`` will return 0 entries when the array/map to be expanded is null::
returns zero entries when

2021-11-03 18:43 UTC, mosabua commented on docs/src/main/sphinx/sql/select.rst
> +``UNNEST`` is normally used with a ``JOIN`` and can reference columns
```
``JOIN``, and can 
```

2021-12-06 08:17 UTC, findinpath commented
@mosabua  can you please have another look on this one?

2021-12-07 00:20 UTC, mosabua approved these changes
Content is great. Ideally you could wrap the paragraphs at 80 column widths... but thats source code cosmetics..

2021-12-09 13:53 UTC, merged