Implement contains function for IP address (continuation)
trinodb/trino pull request #9654
Opened 2021-10-15 13:28 UTC by pellicano

Developed by: @ebyhr
Contributed by: @pellicano

2021-10-15 13:44 UTC, pellicano commented
@martint signed CLA has been sent through my BlueCat's e-mail.

> Thank you for your pull request and welcome to our community. We require contributors to sign our [Contributor License Agreement](https://github.com/trinodb/cla/raw/master/Trino%20Foundation%20Individual%20CLA.pdf), and we don't seem to have you on file. In order for us to review and merge your code, please submit the signed CLA to [cla@trino.io](mailto:cla@trino.io). For more information, see https://github.com/trinodb/cla.

2021-11-05 19:10 UTC, martint requested changes
Can you squash all the commits?

2021-11-05 19:10 UTC, martint commented on core/trino-main/src/main/java/io/trino/operator/scalar/IpAddressFunctions.java
> +    private static boolean isValidIpV4Cidr(byte[] address, int prefix)
This method can be simplified to:

```java
long mask = 0xFFFFFFFFL >>> prefix;
return (Ints.fromByteArray(address) & mask) == 0;
```

2021-11-05 19:10 UTC, martint commented on docs/src/main/sphinx/functions/ipaddress.rst
> +        SELECT contains('10.0.0.0/8', IPADDRESS '11.255.255.255'); -- false
Add an example with IPv6

2021-11-08 19:26 UTC, pellicano commented on core/trino-main/src/main/java/io/trino/operator/scalar/IpAddressFunctions.java
> +    private static boolean isValidIpV4Cidr(byte[] address, int prefix)
Done.

2021-11-08 19:28 UTC, pellicano commented
@martint commits squashed into 9e6d202217cad9380514a010786921ed4f1ada9d.

2021-11-08 19:38 UTC, martint commented
Merged as 4ca945f469532a6d116bcf51f805ac1c6b608a5c. Thanks!

2021-11-08 19:38 UTC, closed without merging